#!/usr/bin/env python3
"""Fix JSON-LD schema translations in Italian breed pages."""

import os
import re
import json
from pathlib import Path

IT_BREEDS_DIR = Path(__file__).parent / "it" / "breeds"

# Translation mappings for common English phrases to Italian
TRANSLATIONS = [
    # Round 6 fixes
    (r"work-oriented", "orientato al lavoro"),
    (r"exuberant", "esuberante"),
    (r"rendere addestramento piacevole", "rendono l'addestramento piacevole"),
    (r"Bred per fox caccia in packs", "Allevati per cacciare volpi in muta"),
    (r"who prosperano con company", "che prosperano con compagnia"),
    (r"Sono rarely kept come pets", "Sono raramente tenuti come animali domestici"),
    (r"'Little Lion Dog' ottiene la sua name da la sua tradizionale leone-piacere trim",
     "'Little Lion Dog' (cagnolino leone) ottiene il nome dalla sua tradizionale tosatura simile a un leone"),
    (r"Once one di rarest razze, sono ora prized per il loro allegri, amichevoli natura",
     "Un tempo una delle razze più rare, ora sono apprezzati per la loro natura allegra e amichevole"),
    (r"\bfox\b", "volpe"),
    (r"\bfoxes\b", "volpi"),
    (r"\bpacks\b", "muta"),
    (r"\bcompany\b", "compagnia"),
    (r"\brarely\b", "raramente"),
    (r"\bkept\b", "tenuti"),
    (r"\bprized\b", "apprezzati"),
    (r"\btrim\b", "tosatura"),
    (r"\bname\b", "nome"),
    
    # Full sentences/phrases needing complete replacement
    (r"Border Collies sono considered most intelligente razza canina\. Loro were developed per conducendo pecore e hanno incredibile work ethic e energy\.",
     "I Border Collie sono considerati la razza canina più intelligente. Furono sviluppati per condurre le pecore e hanno un'incredibile etica del lavoro ed energia."),
    (r"Flat Coated Retriever è Peter Pan di retrievers—loro mai sembrare to crescere su\. Questi allegri, optimistic cani mantengono il loro da cucciolo enthusiasm well in adulthood\.",
     "Il Flat-Coated Retriever è il Peter Pan dei retriever—non sembrano mai crescere. Questi cani allegri e ottimisti mantengono il loro entusiasmo da cucciolo fino all'età adulta."),
    (r"Il Lakeland Terrier fu allevato to proteggere pecore da foxes in Inghilterra Lake District\.",
     "Il Lakeland Terrier fu allevato per proteggere le pecore dalle volpi nel Lake District inglese."),
    (r"Il Norwich Terrier ha pricked orecchie \(unlike folded-ear Norfolk\) e fu allevato to cacciare vermin\.",
     "Il Norwich Terrier ha orecchie erette (a differenza del Norfolk con orecchie piegate) e fu allevato per cacciare i parassiti."),
    (r"Il Sealyham Terrier è un raro Welsh razza that was una volta darling di Hollywood celebrities\.",
     "Il Sealyham Terrier è una rara razza gallese che un tempo era la beniamina delle celebrità di Hollywood."),
    
    # Multi-word phrases first (order matters!)
    
    # Very specific full sentence fixes
    (r"Nonostante il nome, Labrador Retrievers actually originario di Terranova, Canada, where loro aiutavano i pescatori a recuperare le reti e catturare i pesci in fuga\. nobili britannici in visita in Canada si innamorarono della razza e li portarono in Inghilterra\.", 
     "Nonostante il nome, i Labrador Retriever sono in realtà originari di Terranova, in Canada, dove aiutavano i pescatori a recuperare le reti e catturare i pesci in fuga. I nobili britannici in visita in Canada si innamorarono della razza e li portarono in Inghilterra."),
    (r"But non confondete il loro personalità tranquilla con poca energia\.", 
     "Ma non confondete la loro personalità tranquilla con poca energia."),
    (r"Il loro amichevoli, atteggiamento tollerante li rende favolosi", 
     "Il loro atteggiamento amichevole e tollerante li rende favolosi"),
    (r"Il loro pazienti, gentili la loro natura li rende eccellenti",
     "La loro natura paziente e gentile li rende eccellenti"),
    (r"Perdono molto pelo requiring spazzolatura regolare",
     "Perdono molto pelo e richiedono spazzolatura regolare"),
    (r"che incrociò a yellow retriever con un",
     "che incrociò un retriever giallo con un"),
    (r"per creare perfetti cane da caccia per recuperare",
     "per creare il perfetto cane da caccia per recuperare"),
    (r"d'America più popolari razza canina per buone ragioni",
     "la razza canina più popolare d'America per buone ragioni"),
    (r"per tutti per una famiglia che cerca a di taglia medio-grande cane",
     "per tutti, per una famiglia che cerca un cane di taglia medio-grande"),
    
    # Additional missing translations
    (r"\bactually\b", "in realtà"),
    (r"\bwhere\b", "dove"),
    (r"\bBut\b", "Ma"),
    (r"\bbut\b", "ma"),
    (r"\brequiring\b", "che richiede"),
    (r"\byellow\b", "giallo"),
    (r"\ba yellow\b", "un giallo"),
    
    # More specific phrase fixes - Round 5
    (r"iconic 'wiener cane'", "iconico 'cane salsiccia'"),
    (r"notoriamente lungo e basso", "notoriamente lungo e basso"),
    (r"Curious, vivaci, e affascinante con un grande-cane abbaiare", "Curiosi, vivaci e affascinanti con un abbaio da cane grande"),
    (r"a volte to point di rashness", "a volte al punto di essere avventati"),
    (r"to cacciare badgers", "per cacciare tassi"),
    (r"'dachshund' means 'badger cane'", "'dachshund' significa 'cane da tasso'"),
    (r"Il loro unico forma allowed them to scavare in burrows e confront prey underground",
     "La loro forma unica permetteva loro di scavare nelle tane e affrontare le prede sottoterra"),
    (r"fu allevato da Sami people to condurre reindeer in harsh Arctic climate",
     "fu allevato dai Sami per condurre le renne nel rigido clima artico"),
    (r"Requires regular grooming appropriate for their dense double coat coat",
     "Richiede toelettatura regolare appropriata per il loro denso doppio mantello"),
    (r"Requires regular grooming appropriate for their dense double coat",
     "Richiede toelettatura regolare appropriata per il loro denso doppio mantello"),
    (r"High energy razza requiring vigorous daily exercise—at least an hour of activity\. They thrive with attivo families who enjoy outdoor activities\. Mental stimulation through training and puzzle toys is equally important\. Without adequate exercise, they may develop behavioral issues\.",
     "Razza ad alta energia che richiede esercizio quotidiano intenso—almeno un'ora di attività. Prosperano con famiglie attive che amano le attività all'aperto. La stimolazione mentale attraverso l'addestramento e i giocattoli rompicapo è altrettanto importante. Senza esercizio adeguato, possono sviluppare problemi comportamentali."),
    (r"High energy razza requiring vigorous daily exercise—at least an hour of activity",
     "Razza ad alta energia che richiede esercizio quotidiano intenso—almeno un'ora di attività"),
    (r"They thrive with attivo families who enjoy outdoor activities",
     "Prosperano con famiglie attive che amano le attività all'aperto"),
    (r"Mental stimulation through training and puzzle toys is equally important",
     "La stimolazione mentale attraverso l'addestramento e i giocattoli rompicapo è altrettanto importante"),
    (r"Without adequate exercise, they may develop behavioral issues",
     "Senza esercizio adeguato, possono sviluppare problemi comportamentali"),
    (r"Descended da English Bullcanes brought to Francia da lace workers",
     "Discendenti dai Bulldog Inglesi portati in Francia dai merlettai"),
    (r"French allevatori developed distintivo bat orecchie e compatti taglia that define razza oggi",
     "Gli allevatori francesi svilupparono le distintive orecchie a pipistrello e la taglia compatta che definiscono la razza oggi"),
    (r"Easy to groom—spazzolatura settimanale e regolare facial fold cleaning",
     "Facile da toelettare—spazzolatura settimanale e pulizia regolare delle pieghe facciali"),
    (r"Keep wrinkles asciutto to prevent infezioni",
     "Mantenere le rughe asciutte per prevenire infezioni"),
    (r"Very facile to groom", "Molto facile da toelettare"),
    (r"Bassa manutenzione mantello", "Mantello a bassa manutenzione"),
    (r"Il majestic Cane da Montagna dei Pirenei fu allevato to guard sheep in mountains",
     "Il maestoso Cane da Montagna dei Pirenei fu allevato per proteggere le pecore in montagna"),
    (r"Sono gentili giants con un calmo demeanor ma forti guardiano istinti",
     "Sono giganti gentili con un comportamento calmo ma forti istinti da guardiano"),
    (r"Il Leonberger fu allevato to resemble a lion e servire come a versatili cane da lavoro e famiglia compagno",
     "Il Leonberger fu allevato per assomigliare a un leone e servire come versatile cane da lavoro e compagno di famiglia"),
    (r"Thè unffascinante Dutch razza was usato per lure ducks in traps",
     "L'affascinante razza olandese veniva usata per attirare le anatre nelle trappole"),
    (r"Il loro fluente mantello e felice demeanor li rendono attrattivo compagni e agility cani",
     "Il loro mantello fluente e il comportamento felice li rendono attraenti compagni e cani da agility"),
    (r"Il 'Toller' è più piccolo retriever ma packed con energy e intelligenza",
     "Il 'Toller' è il retriever più piccolo ma pieno di energia e intelligenza"),
    (r"Loro furono allevati to lure e riportare uccelli acquatici con il loro giocoso antics",
     "Furono allevati per attirare e riportare uccelli acquatici con le loro buffonate giocose"),
    (r"An antica razza developed per Chinese royalty",
     "Un'antica razza sviluppata per la nobiltà cinese"),
    (r"maintains il loro dignitoso, indipendente natura",
     "mantiene la sua natura dignitosa e indipendente"),
    (r"Sono devoto to il loro proprietari ma può essere distaccato con estranei",
     "Sono devoti ai loro proprietari ma possono essere distaccati con gli estranei"),
    (r"Brought to Wales da Flemish weavers intorno 1100 AD",
     "Portati in Galles dai tessitori fiamminghi intorno al 1100 d.C."),
    (r"Bred to condurre cattle da nipping at il loro heels—il loro basso stature helped them avoid kicks",
     "Allevati per condurre il bestiame mordendo i loro talloni—la loro bassa statura li aiutava a evitare i calci"),
    (r"Corgè unre intelligente, affettuoso, e surprisingly atletici",
     "I Corgi sono intelligenti, affettuosi e sorprendentemente atletici"),
    (r"Loro hanno grande-cane personalities in compatti bodies",
     "Hanno personalità da cane grande in corpi compatti"),
    (r"Can be vocal e may provare to condurre bambini",
     "Possono essere vocali e possono provare a condurre i bambini"),
    (r"Descended da Roman drover cani",
     "Discendenti dai cani da pastore romani"),
    (r"Rottweilers were usato per condurre bestiame e tirare carts in German town di Rottweil",
     "I Rottweiler venivano usati per condurre il bestiame e tirare i carri nella città tedesca di Rottweil"),
    (r"Loro later became police, militare, e cani da guardia",
     "In seguito divennero cani da polizia, militari e da guardia"),
    (r"Easy to groom\. Weekly brushing\. Moderate shedding con heavier periods due volte a year",
     "Facile da toelettare. Spazzolatura settimanale. Perdita di pelo moderata con periodi più intensi due volte all'anno"),
    (r"An antica North African levriero",
     "Un antico levriero nordafricano"),
    (r"eleganti e riservati",
     "elegante e riservato"),
    (r"Sono deeply devoto to il loro famiglie ma distaccato con estranei",
     "Sono profondamente devoti alle loro famiglie ma distaccati con gli estranei"),
    (r"A close cousin to smooth Vizsla ma con un protettivo wiry mantello",
     "Un cugino stretto del Vizsla liscio ma con un protettivo mantello ruvido"),
    (r"Sono equally affettuoso e atletici, con migliore protection da freddo weather",
     "Sono altrettanto affettuosi e atletici, con migliore protezione dal freddo"),
    (r"Sviluppato in Yorkshire, Inghilterra durante 1800s da Scottish weavers who brought terrier south",
     "Sviluppato nello Yorkshire, in Inghilterra, durante gli anni 1800 da tessitori scozzesi che portarono i terrier al sud"),
    (r"Originariamente usato to catch rats in textile mills",
     "Originariamente usato per catturare i topi nei mulini tessili"),
    (r"\bweavers\b", "tessitori"),
    (r"\bmills\b", "mulini"),
    (r"\brats\b", "topi"),
    (r"\bcarts\b", "carri"),
    (r"\bsheep\b", "pecore"),
    (r"\bducks\b", "anatre"),
    (r"\blion\b", "leone"),
    (r"\breindeer\b", "renne"),
    (r"\bbadgers\b", "tassi"),
    (r"\bburrows\b", "tane"),
    (r"\bprey\b", "prede"),
    (r"\bmajestic\b", "maestoso"),
    (r"\bgiants\b", "giganti"),
    (r"\bdemeanor\b", "comportamento"),
    (r"\bguardiano\b", "da guardiano"),
    (r"\broyalty\b", "nobiltà"),
    (r"\bdignitoso\b", "dignitosa"),
    (r"\bmaintains\b", "mantiene"),
    (r"\bdevoto\b", "devoti"),
    (r"\bheels\b", "talloni"),
    (r"\bstature\b", "statura"),
    (r"\bkicks\b", "calci"),
    (r"\bvocal\b", "vocali"),
    (r"\bprovare\b", "provare"),
    (r"\bdrover\b", "da pastore"),
    (r"\bbestiame\b", "bestiame"),
    (r"\bpolice\b", "polizia"),
    (r"\bmilitare\b", "militari"),
    (r"\bshedding\b", "perdita di pelo"),
    (r"\bperiods\b", "periodi"),
    (r"\bsmooth\b", "liscio"),
    (r"\bwiry\b", "ruvido"),
    (r"\bprotection\b", "protezione"),
    (r"\bweather\b", "tempo"),
    (r"\bbrought\b", "portarono"),
    (r"\bcatch\b", "catturare"),
    (r"\btextile\b", "tessili"),
    
    # More specific phrase fixes - Round 4
    (r"antica Turkish razza used to proteggere livestock da predators piacere wolves e bears", 
     "antica razza turca usata per proteggere il bestiame dai predatori come lupi e orsi"),
    (r"were developed in American West", "furono sviluppati nel West americano"),
    (r"work-oriented cani", "cani orientati al lavoro"),
    (r"con bello coats", "con bei mantelli"),
    (r"spesso striking blue o multicolored occhi", "spesso sorprendenti occhi blu o multicolori"),
    (r"An antica African levriero bred da nomads", "Un antico levriero africano allevato dai nomadi"),
    (r"eleganti yet rugged", "elegante ma robusto"),
    (r"deeply leale to il loro famiglie ma aloof con strangers", "profondamente leale alla propria famiglia ma distaccato con gli estranei"),
    (r"Easy to mantengono", "Facile da mantenere"),
    (r"occasional baths", "bagni occasionali"),
    (r"due to il loro floppy orecchie", "a causa delle loro orecchie pendenti"),
    (r"most potente naso di qualsiasi razza canina", "il naso più potente di qualsiasi razza canina"),
    (r"able to seguire trails sopra 300 hours vecchio", "in grado di seguire tracce vecchie di oltre 300 ore"),
    (r"Low to moderate exercise ha bisogno con brevi passeggiate giornaliere e indoor giocare", 
     "Basse o moderate necessità di esercizio con brevi passeggiate giornaliere e giochi in casa"),
    (r"Loro adattarsi well to vita in appartamento quando il loro basic ha bisogno sono met", 
     "Si adattano bene alla vita in appartamento quando le loro esigenze di base sono soddisfatte"),
    (r"attraverso interattivo toys tiene them engaged", 
     "attraverso giocattoli interattivi li tiene coinvolti"),
    (r"Gentle activities adattarsi this razza calmoo temperament", 
     "Attività dolci si adattano al temperamento calmo di questa razza"),
    (r"calmoo", "calmo"),
    (r"bull-baiting in Inghilterra", "combattimenti con i tori in Inghilterra"),
    (r"When sport was banned in 1835, razzaers worked to transform aggressive fighter in a gentili compagno",
     "Quando lo sport fu vietato nel 1835, gli allevatori lavorarono per trasformare il combattente aggressivo in un gentile compagno"),
    (r"Daily wrinkle cleaning to prevent infections", "Pulizia quotidiana delle pieghe per prevenire infezioni"),
    (r"Keep facial folds asciutto e pulito", "Mantenere le pieghe del muso asciutte e pulite"),
    (r"più piccolo razza canina ma hanno huge personalities", "la più piccola razza canina ma hanno enormi personalità"),
    (r"leale to il loro proprietari e può essere feisty nonostante il loro tiny taglia",
     "leali ai loro proprietari e possono essere combattivi nonostante la loro piccola taglia"),
    (r"\bused to\b", "usato per"),
    (r"\blivestock\b", "bestiame"),
    (r"\bpredators\b", "predatori"),
    (r"\bwolves\b", "lupi"),
    (r"\bbears\b", "orsi"),
    (r"\bnomads\b", "nomadi"),
    (r"\brugged\b", "robusto"),
    (r"\baloof\b", "distaccato"),
    (r"\bstrangers\b", "estranei"),
    (r"\bfloppy\b", "pendenti"),
    (r"\btrails\b", "tracce"),
    (r"\bhours\b", "ore"),
    (r"\bvecchio\b", "vecchio"),
    (r"\bindoor\b", "in casa"),
    (r"\bengaged\b", "coinvolti"),
    (r"\bbanned\b", "vietato"),
    (r"\brazzaers\b", "allevatori"),
    (r"\bfighter\b", "combattente"),
    (r"\bwrinkle\b", "piega"),
    (r"\binfections\b", "infezioni"),
    (r"\bfolds\b", "pieghe"),
    (r"\bhuge\b", "enormi"),
    (r"\bproperties\b", "proprietari"),
    (r"\bfeisty\b", "combattivo"),
    (r"\btiny\b", "piccola"),
    (r"\bstriking\b", "sorprendenti"),
    (r"\bmulticolored\b", "multicolori"),
    (r"\bAmerican West\b", "West americano"),
    (r"\bWest\b", "West"),
    
    # More specific phrase fixes - Round 3
    (r"buono-natured", "di buon carattere"),
    (r"good-natured", "di buon carattere"),
    (r"desiderosoness to please", "desiderio di compiacere"),
    (r"creare per la velocità", "create per la velocità"),
    (r"Il loro intelligenza e desiderosoness to please rendere addestramento piacevole", "La loro intelligenza e il desiderio di compiacere rendono l'addestramento piacevole"),
    (r"Originally bred as", "Originariamente allevato come"),
    (r"Originally bred", "Originariamente allevato"),
    (r"Originally developed", "Originariamente sviluppato"),
    (r"Originally used", "Originariamente usato"),
    (r"Originally created", "Originariamente creato"),
    (r"were originally bred", "furono originariamente allevati"),
    (r"was originally bred", "fu originariamente allevato"),
    (r"were bred", "furono allevati"),
    (r"was bred", "fu allevato"),
    (r"bred to", "allevato per"),
    (r"bred for", "allevato per"),
    (r"designed for", "progettato per"),
    (r"designed to", "progettato per"),
    (r"created for", "creato per"),
    (r"created to", "creato per"),
    (r"built for", "costruito per"),
    (r"built to", "costruito per"),
    (r"Despite il loro", "Nonostante il loro"),
    (r"Despite la loro", "Nonostante la loro"),
    (r"Despite their", "Nonostante il loro"),
    
    # More specific phrase fixes - Round 2
    (r"muscular, stocky cane con un sicuri di sé indole", "cane muscoloso e robusto con un'indole sicura di sé"),
    (r"tough aspetto", "aspetto duro"),
    (r"affettuoso famiglia compagni", "affettuosi compagni di famiglia"),
    (r"delle più piccolo da lavoro terrier", "dei più piccoli terrier da lavoro"),
    (r"cani coraggiosi who sono eccellenti compagni", "cani coraggiosi che sono eccellenti compagni"),
    (r"leale, affascinante compagni", "compagni leali e affascinanti"),
    (r"Known per il loro", "Conosciuto per il suo"),
    (r"pazienti, intelligente cani da pastore", "cani da pastore pazienti e intelligenti"),
    (r"A raro pezzato", "Una rara varietà pezzata"),
    (r"Il loro flowing tricolore mantello e natura allegra li rendono", "Il loro mantello tricolore fluente e la natura allegra li rendono"),
    (r"Developed da Soviet military", "Sviluppato dai militari sovietici"),
    (r"powerful, intelligente guardian", "guardiano potente e intelligente"),
    (r"sicuri di sé, trainable cani che legano closely con il loro famiglie", "cani sicuri di sé e addestrabili che legano strettamente con le loro famiglie"),
    (r"intelligentee", "intelligente"),
    (r"\bstocky\b", "robusto"),
    (r"\bmuscular\b", "muscoloso"),
    (r"\bguardian\b", "guardiano"),
    (r"\btrainable\b", "addestrabile"),
    (r"\bclosely\b", "strettamente"),
    (r"\bflowing\b", "fluente"),
    (r"\bpowerful\b", "potente"),
    (r"\bSoviet\b", "sovietico"),
    (r"\bmilitary\b", "militare"),
    (r"\baspetto\b", "aspetto"),
    (r"\bindole\b", "indole"),
    
    # More specific phrase fixes
    (r"Royal Dog di Scozia", "Cane Reale di Scozia"),
    (r"house cani", "cani da casa"),
    (r"house dog", "cane da casa"),
    (r"il loro impressionante taglia", "la loro impressionante taglia"),
    (r"well-rounded compagni", "compagni equilibrati"),
    (r"harsh, wiry mantello", "mantello ruvido e duro"),
    (r"Requires regolare grooming appropriate per il loro", "Richiede toelettatura regolare appropriata per il loro"),
    (r"con giornaliero passeggiate", "con passeggiate giornaliere"),
    (r"e regolare giocare sessions", "e sessioni di gioco regolari"),
    (r"a mix di physical activity e relaxation time", "un mix di attività fisica e tempo di relax"),
    (r"Interattivo giochi e addestramento sessions provide", "Giochi interattivi e sessioni di addestramento forniscono"),
    (r"A consistent exercise routine tiene them sano e felice", "Una routine di esercizio costante li tiene sani e felici"),
    (r"aiuta them sviluppare in", "li aiuta a svilupparsi in"),
    (r"e rendere meravigliosi", "e sono meravigliosi"),
    (r"Sono eccellenti con i bambini e rendere", "Sono eccellenti con i bambini e sono"),
    (r"Loro amano", "Amano"),
    (r"\bsighthounds\b", "levrieri"),
    (r"\bsighthound\b", "levriero"),
    
    # Common remaining English patterns
    (r"\bOne di\b", "Una delle"),
    (r"\bIl most\b", "Il più"),
    (r"\bmost energici\b", "più energico"),
    (r"\breliable\b", "affidabili"),
    (r"\bimpavidi\b", "impavidi"),
    (r"\bsmallest\b", "più piccolo"),
    (r"\blargest\b", "più grande"),
    (r"\bancient\b", "antica"),
    (r"\brazza known per being\b", "razza conosciuta per essere"),
    (r"\bknown per\b", "conosciuto per"),
    (r"\bknown come\b", "conosciuto come"),
    (r"\bknown for\b", "conosciuto per"),
    (r"\bNamed per\b", "Chiamato per"),
    (r"\bbarkless\b", "senza abbaiare"),
    (r"\binstead loro make\b", "invece emettono"),
    (r"\bunique yodel-like sound\b", "suono unico simile a uno yodel"),
    (r"\bdouble dewclaws\b", "doppi speroni"),
    (r"\bsheepcane\b", "cane da pastore"),
    (r"\bda lavoro ability\b", "capacità lavorativa"),
    (r"\bversatili da lavoro\b", "versatile lavorativa"),
    (r"\bWith il loro\b", "Con il loro"),
    (r"\blamb-like appearance\b", "aspetto simile a un agnello"),
    (r"\bdeceptively gentili-looking\b", "dall'aspetto ingannevolmente gentile"),
    (r"\bretain true terrier spirit\b", "mantengono il vero spirito terrier"),
    (r"\btrue terrier\b", "vero terrier"),
    (r"\ball-black\b", "completamente nero"),
    (r"\bversatility\b", "versatilità"),
    (r"\bunique felted coat\b", "mantello infeltrito unico"),
    (r"\bnatural mats called flocks\b", "stuoie naturali chiamate ciocche"),
    (r"\brare piebald\b", "raro pezzato"),
    (r"\btricolor\b", "tricolore"),
    (r"\bvariety\b", "varietà"),
    (r"\bflowing tricolor coat\b", "mantello tricolore fluente"),
    (r"\ballegri natura\b", "natura allegra"),
    (r"\bdelightful pets\b", "animali deliziosi"),
    (r"\bbeautiful mottled blue coat\b", "bel mantello blu screziato"),
    (r"\bhunting cani\b", "cani da caccia"),
    (r"\bhunting\b", "caccia"),
    (r"\bcompact\b", "compatti"),
    (r"\btuxedo-like markings\b", "marcature simili a uno smoking"),
    (r"\bAmerican Gentleman\b", "Gentiluomo Americano"),
    (r"\bloro're\b", "sono"),
    (r"\bprotettivo instincts\b", "istinti protettivi"),
    (r"\bimpressive physique\b", "fisico imponente"),
    (r"\bolder di two\b", "più vecchia delle due"),
    (r"\ba tail\b", "una coda"),
    (r"\brounder ears\b", "orecchie più rotonde"),
    (r"\bwere bred to herd cattle\b", "furono allevati per condurre il bestiame"),
    (r"\bda nipping at heels\b", "mordendo i talloni"),
    (r"\bnipping at heels\b", "mordendo i talloni"),
    (r"\bda China\b", "dalla Cina"),
    (r"\blion-like mane\b", "criniera simile a un leone"),
    (r"\bblue-black tongue\b", "lingua blu-nera"),
    (r"\bheaviest spaniel\b", "spaniel più pesante"),
    (r"\bless energici than\b", "meno energici di"),
    (r"\bother spaniels\b", "altri spaniel"),
    (r"\bstill amano\b", "amano ancora"),
    (r"\bimmortalized da\b", "immortalati da"),
    (r"\bdevotion to\b", "devozione verso"),
    (r"\bto bambini\b", "i bambini"),
    
    # Common sentence patterns
    (r"\bunn ancient\b", "un'antica"),
    (r"\bunn eleganti\b", "un elegante"),
    (r"\bunn\b", "un"),
    (r"\bun large\b", "una grande"),
    (r"\bItalian mastiff\b", "mastino italiano"),
    (r"\bSwiss Mountain Dogs\b", "Cani da Montagna Svizzeri"),
    (r"\bMountain Dog\b", "Cane da Montagna"),
    (r"\bterriers\b", "terrier"),
    (r"\bspaniels\b", "spaniel"),
    (r"\bshepherd\b", "pastore"),
    (r"\bretriever\b", "retriever"),
    (r"\bTerrier Australianos\b", "Terrier Australiani"),
    (r"\bvivace\b", "vivaci"),
    (r"\bcoraggioso cani\b", "cani coraggiosi"),
    (r"\beccellenti compagni\b", "eccellenti compagni"),
    (r"\baffettuoso ma\b", "affettuosi ma"),
    (r"\btypical terrier spunk\b", "tipica vivacità terrier"),
    (r"\bAfrican razza\b", "razza africana"),
    (r"\bFrancia largest\b", "più grande di Francia"),
    
    # Dog breed terms
    (r"\bdog breeds\b", "razze canine"),
    (r"\bdog breed\b", "razza canina"),
    (r"\bcane razzas\b", "razze canine"),
    (r"\bcane razza\b", "razza canina"),
    (r"\bdog razza\b", "razza canina"),
    (r"\bfamily pets\b", "animali domestici"),
    (r"\bfamily pet\b", "animale domestico"),
    (r"\bfamily dogs\b", "cani da famiglia"),
    (r"\bfamily dog\b", "cane da famiglia"),
    (r"\bfamily canes\b", "cani da famiglia"),
    (r"\bfamily cane\b", "cane da famiglia"),
    (r"\bworking dogs\b", "cani da lavoro"),
    (r"\bworking dog\b", "cane da lavoro"),
    (r"\bworking canes\b", "cani da lavoro"),
    (r"\bworking cane\b", "cane da lavoro"),
    (r"\btherapy dogs\b", "cani da terapia"),
    (r"\btherapy dog\b", "cane da terapia"),
    (r"\btherapy canes\b", "cani da terapia"),
    (r"\btherapy cane\b", "cane da terapia"),
    (r"\bguard dogs\b", "cani da guardia"),
    (r"\bguard dog\b", "cane da guardia"),
    (r"\bguard canes\b", "cani da guardia"),
    (r"\bguard cane\b", "cane da guardia"),
    (r"\bwatchdogs\b", "cani da guardia"),
    (r"\bwatchdog\b", "cane da guardia"),
    (r"\bguncane\b", "cane da caccia"),
    (r"\bguncanes\b", "cani da caccia"),
    (r"\bgundog\b", "cane da caccia"),
    (r"\bgundogs\b", "cani da caccia"),
    (r"\bherding cane\b", "cane da pastore"),
    (r"\bherding canes\b", "cani da pastore"),
    (r"\bherding dog\b", "cane da pastore"),
    (r"\bherding dogs\b", "cani da pastore"),
    (r"\bneighbor canes\b", "cani del vicinato"),
    (r"\bneighbor dogs\b", "cani del vicinato"),
    (r"\bnational cane\b", "cane nazionale"),
    (r"\bnational dog\b", "cane nazionale"),
    
    # Health-related phrases
    (r"\bRegular dental care is essential due to\b", "Le cure dentali regolari sono essenziali a causa di"),
    (r"\bRegular dental care\b", "Cure dentali regolari"),
    (r"\bis essential due to\b", "è essenziale a causa di"),
    (r"\bflat face can cause breathing issues\b", "muso piatto può causare problemi respiratori"),
    (r"\bflat face\b", "muso piatto"),
    (r"\bcan cause breathing issues\b", "può causare problemi respiratori"),
    (r"\bbreathing issues\b", "problemi respiratori"),
    (r"\bextreme temperatures\b", "temperature estreme"),
    (r"\bProne to\b", "Predisposto a"),
    (r"\bprone to\b", "predisposto a"),
    (r"\bpatellar luxation\b", "lussazione rotulea"),
    (r"\bheart murmurs\b", "soffi cardiaci"),
    (r"\bheart disorders\b", "disturbi cardiaci"),
    (r"\bsmall mouth\b", "bocca piccola"),
    (r"\bsmall size\b", "piccola taglia"),
    (r"\bhip dysplasia\b", "displasia dell'anca"),
    (r"\bhip and elbow dysplasia\b", "displasia dell'anca e del gomito"),
    (r"\belbow dysplasia\b", "displasia del gomito"),
    (r"\beye conditions\b", "problemi oculari"),
    (r"\bexercise-induced collapse\b", "collasso indotto dall'esercizio"),
    (r"\bObesity is common\b", "L'obesità è comune"),
    (r"\bwatch their diet\b", "controllate la loro dieta"),
    (r"\bGenerally healthy\b", "Generalmente sani"),
    (r"\bGenerally healthy with a lifespan of\b", "Generalmente sani con un'aspettativa di vita di"),
    (r"\bwith a lifespan of\b", "con un'aspettativa di vita di"),
    (r"\bCommon concerns include\b", "Le problematiche più comuni includono"),
    (r"\bRegular veterinary checkups\b", "Visite veterinarie regolari"),
    (r"\bpreventive care\b", "cure preventive"),
    (r"\bare important\b", "sono importanti"),
    (r"\bis important\b", "è importante"),
    (r"\bMaintaining a healthy weight\b", "Mantenere un peso sano"),
    (r"\bhelps prevent\b", "aiuta a prevenire"),
    (r"\bhealth issues\b", "problemi di salute"),
    (r"\bmany health issues\b", "molti problemi di salute"),
    (r"\bbloat\b", "torsione gastrica"),
    (r"\blifespan of\b", "aspettativa di vita di"),
    
    # Exercise-related phrases
    (r"\bModerate exercise needs\b", "Necessità di esercizio moderate"),
    (r"\bshort daily walks\b", "brevi passeggiate giornaliere"),
    (r"\bindoor play sessions\b", "sessioni di gioco in casa"),
    (r"\bis ideal\b", "è ideale"),
    (r"\binteractive toys\b", "giocattoli interattivi"),
    (r"\bmental stimulation\b", "stimolazione mentale"),
    (r"\bMental stimulation\b", "Stimolazione mentale"),
    (r"\bHigh energy razza requiring vigorous daily exercise\b", "Razza ad alta energia che richiede esercizio quotidiano intenso"),
    (r"\bHigh energy\b", "Alta energia"),
    (r"\bhigh-vivace\b", "molto vivaci"),
    (r"\bhigh-spirited\b", "molto vivaci"),
    (r"\brequiring vigorous daily exercise\b", "che richiede esercizio quotidiano intenso"),
    (r"\brequiring daily exercise\b", "che richiede esercizio quotidiano"),
    (r"\bat least an hour\b", "almeno un'ora"),
    (r"\bof activity\b", "di attività"),
    (r"\bThey thrive with\b", "Prosperano con"),
    (r"\bthrive with\b", "prosperano con"),
    (r"\battivo families\b", "famiglie attive"),
    (r"\bactive families\b", "famiglie attive"),
    (r"\boutdoor activities\b", "attività all'aperto"),
    (r"\bthrough training\b", "attraverso l'addestramento"),
    (r"\bpuzzle toys\b", "giocattoli rompicapo"),
    (r"\bis equally important\b", "è altrettanto importante"),
    (r"\bWithout adequate exercise\b", "Senza esercizio adeguato"),
    (r"\bthey may develop\b", "possono sviluppare"),
    (r"\bbehavioral issues\b", "problemi comportamentali"),
    (r"\bbursts of energy\b", "esplosioni di energia"),
    (r"\blove to play\b", "adorano giocare"),
    (r"\bescape artists\b", "artisti della fuga"),
    (r"\bfenced yard\b", "cortile recintato"),
    
    # Grooming section
    (r"\bHeavy shedders\b", "Perdono molto pelo"),
    (r"\bHeavy shedders—brush several times a week\b", "Perdono molto pelo—spazzolare diverse volte a settimana"),
    (r"\bbrush several times a week\b", "spazzolare diverse volte a settimana"),
    (r"\bThey 'blow' their coat twice a year when daily brushing is needed\b", "Cambiano pelo due volte l'anno quando è necessaria la spazzolatura quotidiana"),
    (r"\bRegular nail, ear, and dental care\b", "Cure regolari per unghie, orecchie e denti"),
    (r"\bregular brushing\b", "spazzolatura regolare"),
    (r"\bdaily during shedding season\b", "quotidiana durante la muta"),
    (r"\bfeathered coat\b", "mantello frangiato"),
    (r"\bneeds attention\b", "richiede attenzione"),
    (r"\bto prevent matting\b", "per evitare nodi"),
    (r"\bLow maintenance\b", "Bassa manutenzione"),
    (r"\blow maintenance\b", "bassa manutenzione"),
    (r"\bminimal grooming\b", "toelettatura minima"),
    (r"\boccasional brushing\b", "spazzolatura occasionale"),
    (r"\bweekly brushing\b", "spazzolatura settimanale"),
    (r"\bWeekly brushing keeps coat healthy\b", "La spazzolatura settimanale mantiene il mantello sano"),
    (r"\bThey shed heavily, especially during seasonal changes\b", "Perdono molto pelo, soprattutto durante i cambi di stagione"),
    (r"\bRegular nail trimming and ear cleaning needed\b", "Necessari taglio regolare delle unghie e pulizia delle orecchie"),
    (r"\bHigh maintenance coat requiring professional grooming every 4-6 weeks\b", "Mantello ad alta manutenzione che richiede toelettatura professionale ogni 4-6 settimane"),
    (r"\bDaily brushing to prevent matting\b", "Spazzolatura quotidiana per evitare nodi"),
    (r"\bThe trade-off is minimal shedding\b", "Il lato positivo è la perdita minima di pelo"),
    
    # History section
    (r"\bDeveloped in\b", "Sviluppato in"),
    (r"\bOriginated in\b", "Originario di"),
    (r"\boriginated in\b", "originario di"),
    (r"\bactually originated in\b", "in realtà è originario di"),
    (r"\bBred in\b", "Allevato in"),
    (r"\bmid-19th century\b", "metà del XIX secolo"),
    (r"\b19th century\b", "XIX secolo"),
    (r"\b20th century\b", "XX secolo"),
    (r"\blate 1800s\b", "fine del 1800"),
    (r"\bwho crossed\b", "che incrociò"),
    (r"\bto create\b", "per creare"),
    (r"\bfor retrieving\b", "per recuperare"),
    (r"\bwaterfowl\b", "uccelli acquatici"),
    (r"\bScotland\b", "Scozia"),
    (r"\bEngland\b", "Inghilterra"),
    (r"\bGermany\b", "Germania"),
    (r"\bFrance\b", "Francia"),
    (r"\bCanada\b", "Canada"),
    (r"\bNewfoundland\b", "Terranova"),
    (r"\bNewfoundland, Canada\b", "Terranova, Canada"),
    (r"\bBritish nobles\b", "nobili britannici"),
    (r"\bvisiting Canada\b", "in visita in Canada"),
    (r"\bfell in love with\b", "si innamorarono della"),
    (r"\bfell in love with razza\b", "si innamorarono della razza"),
    (r"\bbrought them to\b", "li portarono in"),
    (r"\bbrought them to England\b", "li portarono in Inghilterra"),
    (r"\bhelped fishermen\b", "aiutavano i pescatori a"),
    (r"\bretrieve nets\b", "recuperare le reti"),
    (r"\bcatch escaping fish\b", "catturare i pesci in fuga"),
    (r"\bescaping fish\b", "pesci in fuga"),
    (r"\bperfect guncane\b", "cane da caccia perfetto"),
    (r"\bperfect gundog\b", "cane da caccia perfetto"),
    (r"\bideal herding cane\b", "cane da pastore ideale"),
    (r"\bwho wanted to create\b", "che voleva creare"),
    (r"\bThe razza quickly proved versatile\b", "La razza si dimostrò rapidamente versatile"),
    (r"\bbecame popular worldwide\b", "divenne popolare in tutto il mondo"),
    (r"\bfor various working roles\b", "per vari ruoli lavorativi"),
    (r"\bOriginally bred in Germany as water retrievers\b", "Originariamente allevati in Germania come cani da riporto acquatico"),
    (r"\bThe razza became associated with France\b", "La razza divenne associata alla Francia"),
    (r"\bwhere it was refined\b", "dove fu raffinata"),
    (r"\bbecame national cane\b", "divenne il cane nazionale"),
    (r"\bThe elaborate clips were functional\b", "Le elaborate tosature erano funzionali"),
    (r"\bdesigned to protect joints and organs in cold water\b", "progettate per proteggere articolazioni e organi in acqua fredda"),
    
    # Temperament section
    (r"\bmature slowly\b", "maturano lentamente"),
    (r"\benergy well into adulthood\b", "energia fino all'età adulta"),
    (r"\bGreat with kids\b", "Ottimi con i bambini"),
    (r"\bgreat with kids\b", "ottimi con i bambini"),
    (r"\bGreat with children\b", "Ottimi con i bambini"),
    (r"\bgreat with children\b", "ottimi con i bambini"),
    (r"\bcon bambini\b", "con i bambini"),
    (r"\bwith children\b", "con i bambini"),
    (r"\bloyal to family\b", "leali alla famiglia"),
    (r"\bto family\b", "alla famiglia"),
    (r"\bnature makes them\b", "la loro natura li rende"),
    (r"\bterrier-like personality\b", "personalità tipo terrier"),
    (r"\btoy size\b", "taglia toy"),
    (r"\bcomedic expressions\b", "espressioni comiche"),
    (r"\bearned them\b", "gli ha fatto guadagnare"),
    (r"\bhave earned them\b", "gli hanno fatto guadagnare"),
    (r"\bnickname\b", "soprannome"),
    (r"\bwonderful with children\b", "meravigliosi con i bambini"),
    (r"\bwonderful con bambini\b", "meravigliosi con i bambini"),
    (r"\bcompagnoable housemates\b", "compagni di casa"),
    (r"\bcompanionable housemates\b", "compagni di casa"),
    (r"\bdon't mistake\b", "non confondete"),
    (r"\bDon't mistake\b", "Non confondete"),
    (r"\beasygoing personality\b", "personalità tranquilla"),
    (r"\bfor low energy\b", "con poca energia"),
    (r"\bsocialize well\b", "socializzano bene"),
    (r"\bhumans alike\b", "anche gli umani"),
    (r"\band humans alike\b", "e anche gli umani"),
    (r"\bwith whole family\b", "con tutta la famiglia"),
    (r"\bbond with whole family\b", "legano con tutta la famiglia"),
    (r"\bThey are compagnoable housemates who bond with whole family\b", "Sono compagni di casa che legano con tutta la famiglia"),
    (r"\band they socialize well with neighbor canes and humans alike\b", "e socializzano bene con i cani del vicinato e con gli umani"),
    (r"\bBut don't mistake their easygoing personality for low energy\b", "Ma non confondete la loro personalità tranquilla con poca energia"),
    
    # Socialization
    (r"\bEarly socialization\b", "La socializzazione precoce"),
    (r"\bearly socialization\b", "la socializzazione precoce"),
    (r"\bare recommended\b", "sono raccomandati"),
    (r"\bis recommended\b", "è raccomandato"),
    
    # Sentence starters and common phrases
    (r"\bThe Labrador Retriever is America's most popular cane razza for good reason\b", "Il Labrador Retriever è la razza canina più popolare d'America per buone ragioni"),
    (r"\bThe Golden Retriever is one of most popular cane razzas\b", "Il Golden Retriever è una delle razze canine più popolari"),
    (r"\bis one of most popular\b", "è una delle più popolari"),
    (r"\bDespite name, Labrador Retrievers actually originated in\b", "Nonostante il nome, i Labrador Retriever sono in realtà originari di"),
    (r"\bDespite name\b", "Nonostante il nome"),
    (r"\bLabs are famously amichevole\b", "I Lab sono notoriamente amichevoli"),
    (r"\bGoldens are\b", "I Golden sono"),
    (r"\bLabs are\b", "I Lab sono"),
    (r"\bThey're\b", "Sono"),
    (r"\bThey are\b", "Sono"),
    (r"\bTheir\b", "Il loro"),
    (r"\bThey\b", "Loro"),
    (r"\bthey\b", "loro"),
    (r"\bThe\b", "Il"),
    (r"\bThis\b", "Questo"),
    (r"\bThese\b", "Questi"),
    (r"\bDespite\b", "Nonostante"),
    (r"\bdespite\b", "nonostante"),
    
    # Common phrases
    (r"\bis one of\b", "è una delle"),
    (r"\bare one of\b", "sono una delle"),
    (r"\bmost popular\b", "più popolari"),
    (r"\bmakes them\b", "li rende"),
    (r"\bmake them\b", "li rendono"),
    (r"\bmake excellent\b", "sono eccellenti"),
    (r"\bmakes excellent\b", "è eccellente come"),
    (r"\bis known for being\b", "è conosciuto per essere"),
    (r"\bare known for being\b", "sono conosciuti per essere"),
    (r"\bis known for\b", "è conosciuto per"),
    (r"\bare known for\b", "sono conosciuti per"),
    (r"\bwho enjoy\b", "che amano"),
    (r"\bwho love\b", "che amano"),
    (r"\bwho want\b", "che vogliono"),
    (r"\bwho need\b", "che hanno bisogno di"),
    (r"\bwho have\b", "che hanno"),
    (r"\bwho bond\b", "che legano"),
    (r"\btheir intelligence\b", "la loro intelligenza"),
    (r"\balways entertaining\b", "sempre divertenti"),
    (r"\bfor good reason\b", "per buone ragioni"),
    (r"\bfor a family looking for\b", "per una famiglia che cerca"),
    (r"\bmore than enough\b", "più che abbastanza"),
    (r"\bto go around\b", "per tutti"),
    (r"\bform strong bonds\b", "formano legami forti"),
    (r"\bstrong bonds\b", "legami forti"),
    (r"\bwith their family\b", "con la loro famiglia"),
    (r"\bwith other pets\b", "con altri animali"),
    (r"\bother pets\b", "altri animali"),
    
    # Adjectives - mixed Italian words in English context
    (r"\bamichevole\b", "amichevoli"),
    (r"\bfriendly\b", "amichevoli"),
    (r"\bfriendly, tolerant attitude\b", "atteggiamento amichevole e tollerante"),
    (r"\btolerant attitude\b", "atteggiamento tollerante"),
    (r"\btolerant\b", "tolleranti"),
    (r"\bfabulous\b", "favolosi"),
    (r"\bintelligent\b", "intelligenti"),
    (r"\bhighly capable\b", "molto capaci"),
    (r"\boutgoing\b", "estroversi"),
    (r"\btrustworthy\b", "affidabili"),
    (r"\bdesideroso to please\b", "desiderosi di compiacere"),
    (r"\beager to please\b", "desiderosi di compiacere"),
    (r"\bwonderful\b", "meravigliosi"),
    (r"\bpaziente\b", "pazienti"),
    (r"\bpatient\b", "pazienti"),
    (r"\bgentile\b", "gentili"),
    (r"\bgentle\b", "gentili"),
    (r"\bexcellent\b", "eccellenti"),
    (r"\bfun-loving\b", "amanti del divertimento"),
    (r"\bplayful\b", "giocherelloni"),
    (r"\bloyal\b", "leali"),
    (r"\bprotective\b", "protettivi"),
    (r"\baffectionate\b", "affettuosi"),
    (r"\balert\b", "vigili"),
    (r"\bbrave\b", "coraggiosi"),
    (r"\bcalm\b", "calmi"),
    (r"\bconfident\b", "sicuri di sé"),
    (r"\bcurious\b", "curiosi"),
    (r"\bdetermined\b", "determinati"),
    (r"\bdignified\b", "dignitosi"),
    (r"\benergetic\b", "energici"),
    (r"\bindependent\b", "indipendenti"),
    (r"\bstubborn\b", "testardi"),
    (r"\bsensitive\b", "sensibili"),
    (r"\breserved\b", "riservati"),
    (r"\bspirited\b", "vivaci"),
    (r"\bsweet\b", "dolci"),
    (r"\bversatile\b", "versatili"),
    (r"\battivo\b", "attive"),
    (r"\bactive\b", "attive"),
    (r"\bstrong\b", "forti"),
    (r"\bathletic\b", "atletici"),
    (r"\bgraceful\b", "aggraziati"),
    (r"\belegant\b", "eleganti"),
    (r"\bwary\b", "diffidenti"),
    (r"\bclever\b", "intelligenti"),
    (r"\bsmart\b", "intelligenti"),
    (r"\bbold\b", "audaci"),
    (r"\bfearless\b", "impavidi"),
    (r"\bnoble\b", "nobili"),
    (r"\bdevoted\b", "devoti"),
    (r"\bsociable\b", "socievoli"),
    (r"\bfrisky\b", "vivaci"),
    (r"\blively\b", "vivaci"),
    (r"\bquiet\b", "tranquilli"),
    (r"\bmellow\b", "tranquilli"),
    (r"\brelaxed\b", "rilassati"),
    (r"\bcheerful\b", "allegri"),
    (r"\bhappy\b", "felici"),
    (r"\bcharming\b", "affascinanti"),
    (r"\bcourageous\b", "coraggiosi"),
    (r"\badaptable\b", "adattabili"),
    (r"\bobedient\b", "obbedienti"),
    (r"\bresponsive\b", "ricettivi"),
    (r"\bperfect\b", "perfetti"),
    (r"\bentertaining\b", "divertenti"),
    (r"\bfamously\b", "notoriamente"),
    
    # Common verbs and phrases
    (r"\bmaintain\b", "mantengono"),
    (r"\bcan be\b", "può essere"),
    
    # Dog-related terms
    (r"\bdogs\b", "cani"),
    (r"\bdog\b", "cane"),
    (r"\bcanes\b", "cani"),
    (r"\bcane\b", "cane"),
    (r"\bpuppies\b", "cuccioli"),
    (r"\bpuppy-like\b", "da cucciolo"),
    (r"\bpuppy\b", "cucciolo"),
    (r"\bpups\b", "cuccioli"),
    (r"\bpup\b", "cucciolo"),
    (r"\brazza\b", "razza"),
    (r"\brazzas\b", "razze"),
    (r"\bbreed\b", "razza"),
    (r"\bbreeds\b", "razze"),
    (r"\bcompagnos\b", "compagni"),
    (r"\bcompagno\b", "compagno"),
    
    # More English words found in files
    (r"\bOne of\b", "Una delle"),
    (r"\bone of\b", "una delle"),
    (r"\blargest of\b", "più grande di"),
    (r"\bsmallest of\b", "più piccolo di"),
    (r"\boldest of\b", "più antico di"),
    (r"\bof the\b", "delle"),
    (r"\bof two\b", "delle due"),
    (r"\bof all\b", "di tutti"),
    (r"\bmost popular\b", "più popolari"),
    (r"\bmost energetic\b", "più energici"),
    (r"\bmost intelligent\b", "più intelligenti"),
    (r"\bmost loyal\b", "più leali"),
    (r"\bwho are\b", "che sono"),
    (r"\bwho were\b", "che furono"),
    (r"\bwho make\b", "che sono"),
    (r"\bwho still\b", "che ancora"),
    (r"\bthat forms\b", "che forma"),
    (r"\bthat makes\b", "che rende"),
    (r"\blike a\b", "come un"),
    (r"\blike an\b", "come un"),
    (r"\bat heels\b", "ai talloni"),
    (r"\bat the\b", "al"),
    (r"\bthe true\b", "il vero"),
    (r"\ba true\b", "un vero"),
    (r"\bthe same\b", "lo stesso"),
    (r"\bthe most\b", "il più"),
    (r"\bthe largest\b", "il più grande"),
    (r"\bthe smallest\b", "il più piccolo"),
    (r"\bthe oldest\b", "il più antico"),
    (r"\bthe only\b", "l'unico"),
    (r"\bonly one\b", "l'unico"),
    (r"\bonly\b", "solo"),
    (r"\bcalled\b", "chiamati"),
    (r"\binstead\b", "invece"),
    (r"\bdespite\b", "nonostante"),
    (r"\bbecause\b", "perché"),
    (r"\balthough\b", "sebbene"),
    (r"\bwhile\b", "mentre"),
    (r"\bwhen\b", "quando"),
    (r"\bafter\b", "dopo"),
    (r"\bbefore\b", "prima"),
    (r"\bmore\b", "più"),
    (r"\bless\b", "meno"),
    (r"\bthan\b", "di"),
    (r"\bother\b", "altri"),
    (r"\ball\b", "tutti"),
    (r"\bboth\b", "entrambi"),
    (r"\beach\b", "ogni"),
    (r"\bevery\b", "ogni"),
    (r"\bany\b", "qualsiasi"),
    (r"\bsome\b", "alcuni"),
    (r"\bmuch\b", "molto"),
    (r"\bvery\b", "molto"),
    (r"\btoo\b", "troppo"),
    (r"\bstill\b", "ancora"),
    (r"\balso\b", "anche"),
    (r"\beven\b", "anche"),
    (r"\bjust\b", "solo"),
    (r"\boften\b", "spesso"),
    (r"\balways\b", "sempre"),
    (r"\bnever\b", "mai"),
    (r"\bsometimes\b", "a volte"),
    (r"\busually\b", "di solito"),
    (r"\bparticularly\b", "particolarmente"),
    (r"\bespecially\b", "soprattutto"),
    (r"\bextremely\b", "estremamente"),
    (r"\bhighly\b", "molto"),
    (r"\bvery\b", "molto"),
    (r"\bquite\b", "piuttosto"),
    (r"\brather\b", "piuttosto"),
    (r"\benough\b", "abbastanza"),
    (r"\baround\b", "intorno"),
    (r"\babout\b", "circa"),
    (r"\bnearly\b", "quasi"),
    (r"\balmost\b", "quasi"),
    (r"\bentirely\b", "interamente"),
    (r"\bcompletely\b", "completamente"),
    (r"\btotally\b", "totalmente"),
    (r"\babsolutely\b", "assolutamente"),
    (r"\bdefinitely\b", "sicuramente"),
    (r"\bcertainly\b", "certamente"),
    (r"\bprobably\b", "probabilmente"),
    (r"\bpossibly\b", "possibilmente"),
    (r"\bmaybe\b", "forse"),
    (r"\bperhaps\b", "forse"),
    (r"\bhowever\b", "tuttavia"),
    (r"\btherefore\b", "quindi"),
    (r"\bthus\b", "così"),
    (r"\botherwise\b", "altrimenti"),
    (r"\bmeanwhile\b", "nel frattempo"),
    (r"\bfinally\b", "infine"),
    (r"\beventually\b", "alla fine"),
    (r"\binitially\b", "inizialmente"),
    (r"\boriginally\b", "originariamente"),
    (r"\btraditionally\b", "tradizionalmente"),
    (r"\bhistorically\b", "storicamente"),
    (r"\btoday\b", "oggi"),
    (r"\bnow\b", "ora"),
    (r"\bthen\b", "poi"),
    (r"\bonce\b", "una volta"),
    (r"\btwice\b", "due volte"),
    (r"\bagain\b", "di nuovo"),
    (r"\bback\b", "indietro"),
    (r"\baway\b", "via"),
    (r"\bup\b", "su"),
    (r"\bdown\b", "giù"),
    (r"\bout\b", "fuori"),
    (r"\binto\b", "in"),
    (r"\bover\b", "sopra"),
    (r"\bunder\b", "sotto"),
    (r"\bbetween\b", "tra"),
    (r"\bamong\b", "tra"),
    (r"\bacross\b", "attraverso"),
    (r"\bthrough\b", "attraverso"),
    (r"\balong\b", "lungo"),
    (r"\baround\b", "intorno"),
    (r"\babove\b", "sopra"),
    (r"\bbelow\b", "sotto"),
    (r"\bnear\b", "vicino"),
    (r"\bfar\b", "lontano"),
    (r"\bhigh\b", "alto"),
    (r"\blow\b", "basso"),
    (r"\blarge\b", "grande"),
    (r"\bbig\b", "grande"),
    (r"\blong\b", "lungo"),
    (r"\btall\b", "alto"),
    (r"\bwide\b", "largo"),
    (r"\bthick\b", "spesso"),
    (r"\bthin\b", "sottile"),
    (r"\bheavy\b", "pesante"),
    (r"\blight\b", "leggero"),
    (r"\bsoft\b", "morbido"),
    (r"\bhard\b", "duro"),
    (r"\bwarm\b", "caldo"),
    (r"\bcool\b", "fresco"),
    (r"\bcold\b", "freddo"),
    (r"\bhot\b", "caldo"),
    (r"\bwet\b", "bagnato"),
    (r"\bdry\b", "asciutto"),
    (r"\bclean\b", "pulito"),
    (r"\bdirty\b", "sporco"),
    (r"\bfresh\b", "fresco"),
    (r"\bold\b", "vecchio"),
    (r"\bnew\b", "nuovo"),
    (r"\byoung\b", "giovane"),
    (r"\bearly\b", "presto"),
    (r"\blate\b", "tardi"),
    (r"\bfast\b", "veloce"),
    (r"\bslow\b", "lento"),
    (r"\bquick\b", "veloce"),
    (r"\beasy\b", "facile"),
    (r"\bhard\b", "difficile"),
    (r"\bsimple\b", "semplice"),
    (r"\bcomplex\b", "complesso"),
    (r"\bdifficult\b", "difficile"),
    (r"\bpossible\b", "possibile"),
    (r"\bimpossible\b", "impossibile"),
    (r"\bnecessary\b", "necessario"),
    (r"\bimportant\b", "importante"),
    (r"\bspecial\b", "speciale"),
    (r"\bcommon\b", "comune"),
    (r"\brare\b", "raro"),
    (r"\boriginal\b", "originale"),
    (r"\breal\b", "reale"),
    (r"\btrue\b", "vero"),
    (r"\bfalse\b", "falso"),
    (r"\bright\b", "giusto"),
    (r"\bwrong\b", "sbagliato"),
    (r"\bgood\b", "buono"),
    (r"\bbad\b", "cattivo"),
    (r"\bbest\b", "migliore"),
    (r"\bworst\b", "peggiore"),
    (r"\bbetter\b", "migliore"),
    (r"\bworse\b", "peggiore"),
    (r"\bfull\b", "pieno"),
    (r"\bempty\b", "vuoto"),
    (r"\bopen\b", "aperto"),
    (r"\bclosed\b", "chiuso"),
    (r"\bfree\b", "libero"),
    (r"\bsafe\b", "sicuro"),
    (r"\bdangerous\b", "pericoloso"),
    (r"\bhealthy\b", "sano"),
    (r"\bsick\b", "malato"),
    (r"\bbeautiful\b", "bello"),
    (r"\bugly\b", "brutto"),
    (r"\bpretty\b", "carino"),
    (r"\bhandsome\b", "bello"),
    (r"\bcute\b", "carino"),
    (r"\bfine\b", "fine"),
    (r"\bnice\b", "bello"),
    (r"\bgorgeous\b", "splendido"),
    (r"\blovely\b", "adorabile"),
    (r"\bstunning\b", "stupendo"),
    (r"\bamazing\b", "straordinario"),
    (r"\bwonderful\b", "meraviglioso"),
    (r"\bfantastic\b", "fantastico"),
    (r"\bincredible\b", "incredibile"),
    (r"\bunbelievable\b", "incredibile"),
    (r"\bextraordinary\b", "straordinario"),
    (r"\bremarkable\b", "notevole"),
    (r"\bimpressive\b", "impressionante"),
    (r"\bounstanding\b", "eccezionale"),
    (r"\bexceptional\b", "eccezionale"),
    (r"\bunique\b", "unico"),
    (r"\bdistinctive\b", "distintivo"),
    (r"\bcharacteristic\b", "caratteristico"),
    (r"\btypical\b", "tipico"),
    (r"\busual\b", "usuale"),
    (r"\bnormal\b", "normale"),
    (r"\bstandard\b", "standard"),
    (r"\bregular\b", "regolare"),
    (r"\bfrequent\b", "frequente"),
    (r"\bconstant\b", "costante"),
    (r"\bcontinuous\b", "continuo"),
    (r"\bsteady\b", "costante"),
    (r"\bstable\b", "stabile"),
    (r"\bsecure\b", "sicuro"),
    (r"\breliable\b", "affidabile"),
    (r"\btrustworthy\b", "fidato"),
    (r"\bfaithful\b", "fedele"),
    (r"\bloyal\b", "leale"),
    (r"\bdevoted\b", "devoto"),
    (r"\bdedicated\b", "dedicato"),
    (r"\bcommitted\b", "impegnato"),
    (r"\bserious\b", "serio"),
    (r"\bfunny\b", "divertente"),
    (r"\bhilarious\b", "esilarante"),
    (r"\bamusing\b", "divertente"),
    (r"\binteresting\b", "interessante"),
    (r"\bboring\b", "noioso"),
    (r"\bexciting\b", "eccitante"),
    (r"\bthrilling\b", "emozionante"),
    (r"\bfascinating\b", "affascinante"),
    (r"\bcaptivating\b", "affascinante"),
    (r"\bengaging\b", "coinvolgente"),
    (r"\bentertaining\b", "divertente"),
    (r"\benjoyable\b", "piacevole"),
    (r"\bpleasant\b", "piacevole"),
    (r"\bdelightful\b", "delizioso"),
    (r"\blovable\b", "adorabile"),
    (r"\bcharming\b", "affascinante"),
    (r"\bappealing\b", "attraente"),
    (r"\battractive\b", "attraente"),
    (r"\bbeautiful\b", "bello"),
    (r"\belegant\b", "elegante"),
    (r"\bgraceful\b", "aggraziato"),
    (r"\bstylish\b", "elegante"),
    (r"\bsophisticated\b", "sofisticato"),
    (r"\brefined\b", "raffinato"),
    (r"\bpolished\b", "raffinato"),
    (r"\bpolite\b", "educato"),
    (r"\bcourteous\b", "cortese"),
    (r"\brespectful\b", "rispettoso"),
    (r"\bhonest\b", "onesto"),
    (r"\bsincere\b", "sincero"),
    (r"\bgenuine\b", "genuino"),
    (r"\bauthentic\b", "autentico"),
    (r"\bnatural\b", "naturale"),
    (r"\borganic\b", "organico"),
    (r"\btraditional\b", "tradizionale"),
    (r"\bclassic\b", "classico"),
    (r"\bmodern\b", "moderno"),
    (r"\bcontemporary\b", "contemporaneo"),
    (r"\bcurrent\b", "attuale"),
    (r"\brecent\b", "recente"),
    (r"\blatest\b", "ultimo"),
    (r"\bfuture\b", "futuro"),
    (r"\bpast\b", "passato"),
    (r"\bpresent\b", "presente"),
    
    # Animal-specific terms
    (r"\bcoat\b", "mantello"),
    (r"\bfur\b", "pelo"),
    (r"\bmane\b", "criniera"),
    (r"\btail\b", "coda"),
    (r"\bears\b", "orecchie"),
    (r"\beyes\b", "occhi"),
    (r"\bnose\b", "naso"),
    (r"\bmuzzle\b", "muso"),
    (r"\bjaws\b", "mascelle"),
    (r"\bteeth\b", "denti"),
    (r"\bpaws\b", "zampe"),
    (r"\blegs\b", "zampe"),
    (r"\bfeet\b", "piedi"),
    (r"\bclaws\b", "artigli"),
    (r"\bnails\b", "unghie"),
    (r"\bbody\b", "corpo"),
    (r"\bhead\b", "testa"),
    (r"\bneck\b", "collo"),
    (r"\bback\b", "schiena"),
    (r"\bchest\b", "petto"),
    (r"\bstomach\b", "stomaco"),
    (r"\bsize\b", "taglia"),
    (r"\bweight\b", "peso"),
    (r"\bheight\b", "altezza"),
    (r"\blength\b", "lunghezza"),
    (r"\bshape\b", "forma"),
    (r"\bcolor\b", "colore"),
    (r"\bcolour\b", "colore"),
    (r"\bmarkings\b", "marcature"),
    (r"\bspots\b", "macchie"),
    (r"\bstripes\b", "strisce"),
    (r"\bpattern\b", "pattern"),
    (r"\btexture\b", "texture"),
    (r"\bappearance\b", "aspetto"),
    (r"\blook\b", "aspetto"),
    (r"\blooks\b", "aspetto"),
    (r"\bstyle\b", "stile"),
    (r"\bfeatures\b", "caratteristiche"),
    (r"\bfeature\b", "caratteristica"),
    (r"\btraits\b", "tratti"),
    (r"\btrait\b", "tratto"),
    (r"\bcharacteristics\b", "caratteristiche"),
    (r"\bqualities\b", "qualità"),
    (r"\bquality\b", "qualità"),
    (r"\bstrengths\b", "punti di forza"),
    (r"\bstrength\b", "forza"),
    (r"\bweaknesses\b", "debolezze"),
    (r"\bweakness\b", "debolezza"),
    (r"\bability\b", "capacità"),
    (r"\babilities\b", "capacità"),
    (r"\bskill\b", "abilità"),
    (r"\bskills\b", "abilità"),
    (r"\btalent\b", "talento"),
    (r"\btalents\b", "talenti"),
    (r"\binstinct\b", "istinto"),
    (r"\binstincts\b", "istinti"),
    (r"\bdrive\b", "impulso"),
    (r"\burge\b", "impulso"),
    (r"\bbehavior\b", "comportamento"),
    (r"\bbehaviour\b", "comportamento"),
    (r"\bhabits\b", "abitudini"),
    (r"\bhabit\b", "abitudine"),
    (r"\bpersonality\b", "personalità"),
    (r"\bcharacter\b", "carattere"),
    (r"\bspirit\b", "spirito"),
    (r"\bsoul\b", "anima"),
    (r"\bheart\b", "cuore"),
    (r"\bmind\b", "mente"),
    (r"\btemper\b", "temperamento"),
    (r"\bmood\b", "umore"),
    (r"\battitude\b", "attitudine"),
    (r"\bdisposition\b", "indole"),
    
    # Action words
    (r"\brun\b", "correre"),
    (r"\bruns\b", "corre"),
    (r"\brunning\b", "correndo"),
    (r"\bwalk\b", "camminare"),
    (r"\bwalks\b", "cammina"),
    (r"\bwalking\b", "camminando"),
    (r"\bjump\b", "saltare"),
    (r"\bjumps\b", "salta"),
    (r"\bjumping\b", "saltando"),
    (r"\bplay\b", "giocare"),
    (r"\bplays\b", "gioca"),
    (r"\bplaying\b", "giocando"),
    (r"\bswim\b", "nuotare"),
    (r"\bswims\b", "nuota"),
    (r"\bswimming\b", "nuotando"),
    (r"\bfetch\b", "riportare"),
    (r"\bretrieves\b", "riporta"),
    (r"\bretrieve\b", "riportare"),
    (r"\bretrieving\b", "riportando"),
    (r"\bhunt\b", "cacciare"),
    (r"\bhunts\b", "caccia"),
    (r"\bherd\b", "condurre"),
    (r"\bherds\b", "conduce"),
    (r"\bherding\b", "conducendo"),
    (r"\bguards\b", "fa la guardia"),
    (r"\bguarding\b", "facendo la guardia"),
    (r"\bprotect\b", "proteggere"),
    (r"\bprotects\b", "protegge"),
    (r"\bprotecting\b", "proteggendo"),
    (r"\bwatch\b", "sorvegliare"),
    (r"\bwatches\b", "sorveglia"),
    (r"\bwatching\b", "sorvegliando"),
    (r"\bbark\b", "abbaiare"),
    (r"\bbarks\b", "abbaia"),
    (r"\bbarking\b", "abbaiando"),
    (r"\bhowl\b", "ululare"),
    (r"\bhowls\b", "ulula"),
    (r"\bhowling\b", "ululando"),
    (r"\bbite\b", "mordere"),
    (r"\bbites\b", "morde"),
    (r"\bbiting\b", "mordendo"),
    (r"\bchew\b", "masticare"),
    (r"\bchews\b", "mastica"),
    (r"\bchewing\b", "masticando"),
    (r"\bdig\b", "scavare"),
    (r"\bdigs\b", "scava"),
    (r"\bdigging\b", "scavando"),
    (r"\bsniff\b", "annusare"),
    (r"\bsniffs\b", "annusa"),
    (r"\bsniffing\b", "annusando"),
    (r"\btrack\b", "seguire le tracce"),
    (r"\btracks\b", "segue le tracce"),
    (r"\btracking\b", "seguendo le tracce"),
    (r"\blearn\b", "imparare"),
    (r"\blearns\b", "impara"),
    (r"\blearning\b", "imparando"),
    (r"\bteach\b", "insegnare"),
    (r"\bteaches\b", "insegna"),
    (r"\bteaching\b", "insegnando"),
    (r"\btrain\b", "addestrare"),
    (r"\btrains\b", "addestra"),
    (r"\blove\b", "amare"),
    (r"\bloves\b", "ama"),
    (r"\bloving\b", "amando"),
    (r"\blike\b", "piacere"),
    (r"\blikes\b", "piace"),
    (r"\bliking\b", "piacendo"),
    (r"\bprefer\b", "preferire"),
    (r"\bprefers\b", "preferisce"),
    (r"\bpreferring\b", "preferendo"),
    (r"\bneed\b", "bisogno"),
    (r"\bneeds\b", "ha bisogno"),
    (r"\bneeding\b", "avendo bisogno"),
    (r"\brequire\b", "richiedere"),
    (r"\brequires\b", "richiede"),
    (r"\bdemand\b", "richiedere"),
    (r"\bdemands\b", "richiede"),
    (r"\bdemanding\b", "esigente"),
    (r"\bexcel\b", "eccellere"),
    (r"\bexcels\b", "eccelle"),
    (r"\bexcelling\b", "eccellendo"),
    (r"\bthrive\b", "prosperare"),
    (r"\bthrives\b", "prospera"),
    (r"\bthriving\b", "prosperando"),
    (r"\badapt\b", "adattarsi"),
    (r"\badapts\b", "si adatta"),
    (r"\badapting\b", "adattandosi"),
    (r"\badjust\b", "adattarsi"),
    (r"\badjusts\b", "si adatta"),
    (r"\badjusting\b", "adattandosi"),
    (r"\bfit\b", "adattarsi"),
    (r"\bfits\b", "si adatta"),
    (r"\bfitting\b", "adattandosi"),
    (r"\bsuit\b", "adattarsi"),
    (r"\bsuits\b", "si adatta"),
    (r"\bsuiting\b", "adattandosi"),
    (r"\bbond\b", "legare"),
    (r"\bbonds\b", "lega"),
    (r"\bbonding\b", "legando"),
    (r"\bconnect\b", "connettersi"),
    (r"\bconnects\b", "si connette"),
    (r"\bconnecting\b", "connettendosi"),
    (r"\battach\b", "attaccarsi"),
    (r"\battaches\b", "si attacca"),
    (r"\battaching\b", "attaccandosi"),
    (r"\bcling\b", "aggrapparsi"),
    (r"\bclings\b", "si aggrappa"),
    (r"\bclinging\b", "aggrappandosi"),
    (r"\bfollow\b", "seguire"),
    (r"\bfollows\b", "segue"),
    (r"\bfollowing\b", "seguendo"),
    (r"\blead\b", "guidare"),
    (r"\bleads\b", "guida"),
    (r"\bleading\b", "guidando"),
    (r"\bshow\b", "mostrare"),
    (r"\bshows\b", "mostra"),
    (r"\bshowing\b", "mostrando"),
    (r"\bdisplay\b", "mostrare"),
    (r"\bdisplays\b", "mostra"),
    (r"\bdisplaying\b", "mostrando"),
    (r"\bexhibit\b", "mostrare"),
    (r"\bexhibits\b", "mostra"),
    (r"\bexhibiting\b", "mostrando"),
    (r"\bdemonstrate\b", "dimostrare"),
    (r"\bdemonstrates\b", "dimostra"),
    (r"\bdemonstrating\b", "dimostrando"),
    (r"\bpossess\b", "possedere"),
    (r"\bpossesses\b", "possiede"),
    (r"\bpossessing\b", "possedendo"),
    (r"\bhave\b", "avere"),
    (r"\bhas\b", "ha"),
    (r"\bhaving\b", "avendo"),
    (r"\bget\b", "ottenere"),
    (r"\bgets\b", "ottiene"),
    (r"\bgetting\b", "ottenendo"),
    (r"\bgive\b", "dare"),
    (r"\bgives\b", "dà"),
    (r"\bgiving\b", "dando"),
    (r"\bbring\b", "portare"),
    (r"\bbrings\b", "porta"),
    (r"\bbringing\b", "portando"),
    (r"\btake\b", "prendere"),
    (r"\btakes\b", "prende"),
    (r"\btaking\b", "prendendo"),
    (r"\bkeep\b", "tenere"),
    (r"\bkeeps\b", "tiene"),
    (r"\bkeeping\b", "tenendo"),
    (r"\bhold\b", "tenere"),
    (r"\bholds\b", "tiene"),
    (r"\bholding\b", "tenendo"),
    (r"\bcarry\b", "portare"),
    (r"\bcarries\b", "porta"),
    (r"\bcarrying\b", "portando"),
    (r"\bpull\b", "tirare"),
    (r"\bpulls\b", "tira"),
    (r"\bpulling\b", "tirando"),
    (r"\bpush\b", "spingere"),
    (r"\bpushes\b", "spinge"),
    (r"\bpushing\b", "spingendo"),
    (r"\bmove\b", "muovere"),
    (r"\bmoves\b", "muove"),
    (r"\bmoving\b", "muovendo"),
    (r"\bstop\b", "fermarsi"),
    (r"\bstops\b", "si ferma"),
    (r"\bstopping\b", "fermandosi"),
    (r"\bstart\b", "iniziare"),
    (r"\bstarts\b", "inizia"),
    (r"\bstarting\b", "iniziando"),
    (r"\bbegin\b", "iniziare"),
    (r"\bbegins\b", "inizia"),
    (r"\bbeginning\b", "iniziando"),
    (r"\bend\b", "finire"),
    (r"\bends\b", "finisce"),
    (r"\bending\b", "finendo"),
    (r"\bfinish\b", "finire"),
    (r"\bfinishes\b", "finisce"),
    (r"\bfinishing\b", "finendo"),
    (r"\bcomplete\b", "completare"),
    (r"\bcompletes\b", "completa"),
    (r"\bcompleting\b", "completando"),
    (r"\bdo\b", "fare"),
    (r"\bdoes\b", "fa"),
    (r"\bdoing\b", "facendo"),
    (r"\bmake\b", "rendere"),
    (r"\bmakes\b", "rende"),
    (r"\bmaking\b", "rendendo"),
    (r"\bcreate\b", "creare"),
    (r"\bcreates\b", "crea"),
    (r"\bcreating\b", "creando"),
    (r"\bbuild\b", "costruire"),
    (r"\bbuilds\b", "costruisce"),
    (r"\bbuilding\b", "costruendo"),
    (r"\bform\b", "formare"),
    (r"\bforms\b", "forma"),
    (r"\bforming\b", "formando"),
    (r"\bdevelop\b", "sviluppare"),
    (r"\bdevelops\b", "sviluppa"),
    (r"\bdeveloping\b", "sviluppando"),
    (r"\bgrow\b", "crescere"),
    (r"\bgrows\b", "cresce"),
    (r"\bgrowing\b", "crescendo"),
    (r"\bchange\b", "cambiare"),
    (r"\bchanges\b", "cambia"),
    (r"\bchanging\b", "cambiando"),
    (r"\bbecome\b", "diventare"),
    (r"\bbecomes\b", "diventa"),
    (r"\bbecoming\b", "diventando"),
    (r"\bstay\b", "rimanere"),
    (r"\bstays\b", "rimane"),
    (r"\bstaying\b", "rimanendo"),
    (r"\bremain\b", "rimanere"),
    (r"\bremains\b", "rimane"),
    (r"\bremaining\b", "rimanendo"),
    (r"\bcontinue\b", "continuare"),
    (r"\bcontinues\b", "continua"),
    (r"\bcontinuing\b", "continuando"),
    (r"\blast\b", "durare"),
    (r"\blasts\b", "dura"),
    (r"\blasting\b", "durando"),
    (r"\bseem\b", "sembrare"),
    (r"\bseems\b", "sembra"),
    (r"\bseeming\b", "sembrando"),
    (r"\bappear\b", "apparire"),
    (r"\bappears\b", "appare"),
    (r"\bappearing\b", "apparendo"),
    (r"\blook\b", "sembrare"),
    (r"\blooks\b", "sembra"),
    (r"\blooking\b", "sembrando"),
    (r"\bfeel\b", "sentire"),
    (r"\bfeels\b", "sente"),
    (r"\bfeeling\b", "sentendo"),
    (r"\bsound\b", "suonare"),
    (r"\bsounds\b", "suona"),
    (r"\bsounding\b", "suonando"),
    (r"\bsmell\b", "odorare"),
    (r"\bsmells\b", "odora"),
    (r"\bsmelling\b", "odorando"),
    (r"\btaste\b", "gustare"),
    (r"\btastes\b", "gusta"),
    (r"\btasting\b", "gustando"),
    (r"\btouch\b", "toccare"),
    (r"\btouches\b", "tocca"),
    (r"\btouching\b", "toccando"),
    (r"\bsee\b", "vedere"),
    (r"\bsees\b", "vede"),
    (r"\bseeing\b", "vedendo"),
    (r"\bhear\b", "sentire"),
    (r"\bhears\b", "sente"),
    (r"\bhearing\b", "sentendo"),
    (r"\bknow\b", "sapere"),
    (r"\bknows\b", "sa"),
    (r"\bknowing\b", "sapendo"),
    (r"\bthink\b", "pensare"),
    (r"\bthinks\b", "pensa"),
    (r"\bthinking\b", "pensando"),
    (r"\bbelieve\b", "credere"),
    (r"\bbelieves\b", "crede"),
    (r"\bbelieving\b", "credendo"),
    (r"\bunderstand\b", "capire"),
    (r"\bunderstands\b", "capisce"),
    (r"\bunderstanding\b", "capendo"),
    (r"\bremember\b", "ricordare"),
    (r"\bremembers\b", "ricorda"),
    (r"\bremembering\b", "ricordando"),
    (r"\bforget\b", "dimenticare"),
    (r"\bforgets\b", "dimentica"),
    (r"\bforgetting\b", "dimenticando"),
    (r"\bwant\b", "volere"),
    (r"\bwants\b", "vuole"),
    (r"\bwanting\b", "volendo"),
    (r"\bwish\b", "desiderare"),
    (r"\bwishes\b", "desidera"),
    (r"\bwishing\b", "desiderando"),
    (r"\bhope\b", "sperare"),
    (r"\bhopes\b", "spera"),
    (r"\bhoping\b", "sperando"),
    (r"\bexpect\b", "aspettarsi"),
    (r"\bexpects\b", "si aspetta"),
    (r"\bexpecting\b", "aspettandosi"),
    (r"\btry\b", "provare"),
    (r"\btries\b", "prova"),
    (r"\btrying\b", "provando"),
    (r"\bhelp\b", "aiutare"),
    (r"\bhelps\b", "aiuta"),
    (r"\bhelping\b", "aiutando"),
    (r"\bserve\b", "servire"),
    (r"\bserves\b", "serve"),
    (r"\bserving\b", "servendo"),
    (r"\bassist\b", "assistere"),
    (r"\bassists\b", "assiste"),
    (r"\bassisting\b", "assistendo"),
    (r"\bsupport\b", "sostenere"),
    (r"\bsupports\b", "sostiene"),
    (r"\bsupporting\b", "sostenendo"),
    (r"\bcare\b", "prendersi cura"),
    (r"\bcares\b", "si prende cura"),
    (r"\bcaring\b", "prendendosi cura"),
    (r"\bworry\b", "preoccuparsi"),
    (r"\bworries\b", "si preoccupa"),
    (r"\bworrying\b", "preoccupandosi"),
    (r"\bfear\b", "temere"),
    (r"\bfears\b", "teme"),
    (r"\bfearing\b", "temendo"),
    (r"\btrust\b", "fidarsi"),
    (r"\btrusts\b", "si fida"),
    (r"\btrusting\b", "fidandosi"),
    (r"\brespect\b", "rispettare"),
    (r"\brespects\b", "rispetta"),
    (r"\brespecting\b", "rispettando"),
    (r"\badmire\b", "ammirare"),
    (r"\badmires\b", "ammira"),
    (r"\badmiring\b", "ammirando"),
    (r"\bappreciate\b", "apprezzare"),
    (r"\bappreciates\b", "apprezza"),
    (r"\bappreciating\b", "apprezzando"),
    (r"\bvalue\b", "valutare"),
    (r"\bvalues\b", "valuta"),
    (r"\bvaluing\b", "valutando"),
    
    # Common words
    (r"\birresistible\b", "irresistibili"),
    (r"\bcompanion\b", "compagno"),
    (r"\bcompanions\b", "compagni"),
    (r"\battitude\b", "atteggiamento"),
    (r"\bfaces\b", "musi"),
    (r"\bexpressive\b", "espressivi"),
    (r"\bintelligence\b", "intelligenza"),
    (r"\bnature\b", "natura"),
    (r"\bsocialization\b", "socializzazione"),
    (r"\btraining\b", "addestramento"),
    (r"\bfamilies\b", "famiglie"),
    (r"\bchildren\b", "bambini"),
    (r"\byears\b", "anni"),
    (r"\bcentury\b", "secolo"),
    (r"\bduring\b", "durante"),
    (r"\btherapy\b", "terapia"),
    (r"\bworking\b", "da lavoro"),
    (r"\bterritorial\b", "territoriale"),
    (r"\baffection\b", "affetto"),
    
    # Function words
    (r"\bmany\b", "molti"),
    (r"\bwith a\b", "con un"),
    (r"\bwith\b", "con"),
    (r"\band\b", "e"),
    (r"\bfor\b", "per"),
    (r"\bof\b", "di"),
    (r"\bor\b", "o"),
    (r"\bin\b", "in"),
    (r"\bon\b", "su"),
    (r"\bas\b", "come"),
    (r"\bbut\b", "ma"),
    (r"\bfrom\b", "da"),
    (r"\bby\b", "da"),
    (r"\bhave\b", "hanno"),
    (r"\bhas\b", "ha"),
    (r"\bare\b", "sono"),
    (r"\bis\b", "è"),
    (r"\btheir\b", "il loro"),
    (r"\bits\b", "la sua"),
    (r"\bmedium-to-large\b", "di taglia medio-grande"),
    (r"\bmedium-to-large cane\b", "cane di taglia medio-grande"),
    (r"\ba medium-to-large cane\b", "un cane di taglia medio-grande"),
    
    # Additional phrases
    (r"\bform\b", "formano"),
    (r"\bfamily\b", "famiglia"),
    (r"\bcan cause\b", "può causare"),
    (r"\benjoy\b", "amano"),
    (r"\bgames\b", "giochi"),
    (r"\bideal\b", "ideale"),
    (r"\bsmall\b", "piccolo"),
    (r"\bshort\b", "breve"),
    (r"\bdaily\b", "giornaliero"),
    (r"\bwalks\b", "passeggiate"),
    (r"\bAmerica's\b", "d'America"),
]

def translate_text(text: str) -> str:
    """Apply all translations to text."""
    result = text
    
    for pattern, replacement in TRANSLATIONS:
        result = re.sub(pattern, replacement, result)
    
    # Post-processing fixes for common issues
    post_fixes = [
        (r"\bdi di\b", "di"),
        (r"\bè un un\b", "è un"),
        (r"'s\b", ""),  # Remove possessive 's
        (r"\bUn Un\b", "Un"),
        (r"\bper Un\b", "per un"),
        (r"\bcon Un\b", "con un"),
        (r"\bè Un\b", "è un"),
        (r"\bIl Il\b", "Il"),
        (r"\bin in\b", "in"),
        (r"\bcon con\b", "con"),
        (r"\be e\b", "e"),
        (r"\bda da\b", "da"),
        (r"\bcane cane\b", "cane"),
        (r"\bcani cani\b", "cani"),
    ]
    
    for pattern, replacement in post_fixes:
        result = re.sub(pattern, replacement, result)
    
    # Fix double spaces
    result = re.sub(r'\s+', ' ', result).strip()
    
    return result

def extract_jsonld_blocks(content: str) -> list:
    """Extract all JSON-LD script blocks from HTML content."""
    pattern = r'<script type="application/ld\+json">\s*(.*?)\s*</script>'
    return re.findall(pattern, content, re.DOTALL)

def fix_jsonld_in_file(filepath: Path) -> bool:
    """Fix JSON-LD in a single HTML file. Returns True if changes were made."""
    content = filepath.read_text(encoding='utf-8')
    original_content = content
    
    # Find all JSON-LD blocks
    pattern = r'(<script type="application/ld\+json">)\s*(.*?)\s*(</script>)'
    matches = list(re.finditer(pattern, content, re.DOTALL))
    
    for match in reversed(matches):  # Reverse to preserve positions
        json_str = match.group(2)
        
        try:
            data = json.loads(json_str)
        except json.JSONDecodeError:
            continue
        
        # Check if this has the about.description structure we need
        if 'about' not in data or 'description' not in data.get('about', {}):
            continue
        
        desc = data['about']['description']
        if not isinstance(desc, dict):
            continue
        
        changed = False
        
        # Translate each field
        for field in ['overview', 'temperament', 'health', 'exercise', 'history', 'grooming']:
            if field in desc and isinstance(desc[field], str):
                original = desc[field]
                translated = translate_text(original)
                if translated != original:
                    desc[field] = translated
                    changed = True
        
        if changed:
            # Reconstruct JSON with proper formatting
            new_json = json.dumps(data, ensure_ascii=False, indent=4)
            new_block = f'{match.group(1)}\n    {new_json}\n    {match.group(3)}'
            content = content[:match.start()] + new_block + content[match.end():]
    
    if content != original_content:
        filepath.write_text(content, encoding='utf-8')
        return True
    return False

def main():
    html_files = list(IT_BREEDS_DIR.glob("*.html"))
    print(f"Found {len(html_files)} HTML files in it/breeds/")
    
    fixed = 0
    for filepath in sorted(html_files):
        if fix_jsonld_in_file(filepath):
            print(f"  Fixed: {filepath.name}")
            fixed += 1
    
    print(f"\nFixed {fixed} files")

if __name__ == "__main__":
    main()
