#!/usr/bin/env python3
"""
Translation dictionaries for breed pages
"""

# Temperament traits translation
TRAITS = {
    'friendly': {'fi': 'ystävällinen', 'de': 'freundlich', 'es': 'amigable', 'fr': 'amical', 'it': 'amichevole', 'pt': 'amigável', 'nl': 'vriendelijk', 'pl': 'przyjazny', 'sv': 'vänlig', 'no': 'vennlig', 'da': 'venlig', 'zh': '友好', 'ja': 'フレンドリー', 'ru': 'дружелюбный'},
    'loyal': {'fi': 'uskollinen', 'de': 'treu', 'es': 'leal', 'fr': 'loyal', 'it': 'leale', 'pt': 'leal', 'nl': 'trouw', 'pl': 'lojalny', 'sv': 'lojal', 'no': 'lojal', 'da': 'loyal', 'zh': '忠诚', 'ja': '忠実', 'ru': 'верный'},
    'intelligent': {'fi': 'älykäs', 'de': 'intelligent', 'es': 'inteligente', 'fr': 'intelligent', 'it': 'intelligente', 'pt': 'inteligente', 'nl': 'intelligent', 'pl': 'inteligentny', 'sv': 'intelligent', 'no': 'intelligent', 'da': 'intelligent', 'zh': '聪明', 'ja': '賢い', 'ru': 'умный'},
    'active': {'fi': 'aktiivinen', 'de': 'aktiv', 'es': 'activo', 'fr': 'actif', 'it': 'attivo', 'pt': 'ativo', 'nl': 'actief', 'pl': 'aktywny', 'sv': 'aktiv', 'no': 'aktiv', 'da': 'aktiv', 'zh': '活跃', 'ja': '活発', 'ru': 'активный'},
    'gentle': {'fi': 'lempeä', 'de': 'sanft', 'es': 'gentil', 'fr': 'doux', 'it': 'gentile', 'pt': 'gentil', 'nl': 'zachtaardig', 'pl': 'łagodny', 'sv': 'mild', 'no': 'mild', 'da': 'blid', 'zh': '温柔', 'ja': '穏やか', 'ru': 'нежный'},
    'playful': {'fi': 'leikkisä', 'de': 'verspielt', 'es': 'juguetón', 'fr': 'joueur', 'it': 'giocherellone', 'pt': 'brincalhão', 'nl': 'speels', 'pl': 'zabawny', 'sv': 'lekfull', 'no': 'leken', 'da': 'legesyg', 'zh': '爱玩', 'ja': '遊び好き', 'ru': 'игривый'},
    'protective': {'fi': 'suojeleva', 'de': 'beschützend', 'es': 'protector', 'fr': 'protecteur', 'it': 'protettivo', 'pt': 'protetor', 'nl': 'beschermend', 'pl': 'opiekuńczy', 'sv': 'beskyddande', 'no': 'beskyttende', 'da': 'beskyttende', 'zh': '保护性', 'ja': '保護的', 'ru': 'защитный'},
    'calm': {'fi': 'rauhallinen', 'de': 'ruhig', 'es': 'tranquilo', 'fr': 'calme', 'it': 'calmo', 'pt': 'calmo', 'nl': 'kalm', 'pl': 'spokojny', 'sv': 'lugn', 'no': 'rolig', 'da': 'rolig', 'zh': '冷静', 'ja': '穏やか', 'ru': 'спокойный'},
    'affectionate': {'fi': 'hellä', 'de': 'liebevoll', 'es': 'cariñoso', 'fr': 'affectueux', 'it': 'affettuoso', 'pt': 'afetuoso', 'nl': 'aanhankelijk', 'pl': 'czuły', 'sv': 'kärleksfull', 'no': 'kjærlig', 'da': 'kærlig', 'zh': '深情', 'ja': '愛情深い', 'ru': 'ласковый'},
    'alert': {'fi': 'valpas', 'de': 'wachsam', 'es': 'alerta', 'fr': 'alerte', 'it': 'vigile', 'pt': 'alerta', 'nl': 'alert', 'pl': 'czujny', 'sv': 'vaksam', 'no': 'årvåken', 'da': 'vågen', 'zh': '警觉', 'ja': '警戒心', 'ru': 'бдительный'},
    'energetic': {'fi': 'energinen', 'de': 'energisch', 'es': 'enérgico', 'fr': 'énergique', 'it': 'energico', 'pt': 'energético', 'nl': 'energiek', 'pl': 'energiczny', 'sv': 'energisk', 'no': 'energisk', 'da': 'energisk', 'zh': '精力充沛', 'ja': '元気', 'ru': 'энергичный'},
    'independent': {'fi': 'itsenäinen', 'de': 'unabhängig', 'es': 'independiente', 'fr': 'indépendant', 'it': 'indipendente', 'pt': 'independente', 'nl': 'onafhankelijk', 'pl': 'niezależny', 'sv': 'självständig', 'no': 'uavhengig', 'da': 'uafhængig', 'zh': '独立', 'ja': '独立心', 'ru': 'независимый'},
    'stubborn': {'fi': 'itsepäinen', 'de': 'stur', 'es': 'terco', 'fr': 'têtu', 'it': 'testardo', 'pt': 'teimoso', 'nl': 'koppig', 'pl': 'uparty', 'sv': 'envis', 'no': 'sta', 'da': 'stædig', 'zh': '固执', 'ja': '頑固', 'ru': 'упрямый'},
    'confident': {'fi': 'itsevarma', 'de': 'selbstbewusst', 'es': 'confiado', 'fr': 'confiant', 'it': 'sicuro', 'pt': 'confiante', 'nl': 'zelfverzekerd', 'pl': 'pewny siebie', 'sv': 'självsäker', 'no': 'selvsikker', 'da': 'selvsikker', 'zh': '自信', 'ja': '自信のある', 'ru': 'уверенный'},
    'curious': {'fi': 'utelias', 'de': 'neugierig', 'es': 'curioso', 'fr': 'curieux', 'it': 'curioso', 'pt': 'curioso', 'nl': 'nieuwsgierig', 'pl': 'ciekawski', 'sv': 'nyfiken', 'no': 'nysgjerrig', 'da': 'nysgerrig', 'zh': '好奇', 'ja': '好奇心旺盛', 'ru': 'любопытный'},
    'outgoing': {'fi': 'ulospäinsuuntautunut', 'de': 'aufgeschlossen', 'es': 'extrovertido', 'fr': 'sociable', 'it': 'estroverso', 'pt': 'extrovertido', 'nl': 'extravert', 'pl': 'towarzyski', 'sv': 'utåtriktad', 'no': 'utadvendt', 'da': 'udadvendt', 'zh': '外向', 'ja': '社交的', 'ru': 'общительный'},
    'brave': {'fi': 'rohkea', 'de': 'mutig', 'es': 'valiente', 'fr': 'courageux', 'it': 'coraggioso', 'pt': 'corajoso', 'nl': 'dapper', 'pl': 'odważny', 'sv': 'modig', 'no': 'modig', 'da': 'modig', 'zh': '勇敢', 'ja': '勇敢', 'ru': 'храбрый'},
    'patient': {'fi': 'kärsivällinen', 'de': 'geduldig', 'es': 'paciente', 'fr': 'patient', 'it': 'paziente', 'pt': 'paciente', 'nl': 'geduldig', 'pl': 'cierpliwy', 'sv': 'tålmodig', 'no': 'tålmodig', 'da': 'tålmodig', 'zh': '耐心', 'ja': '忍耐強い', 'ru': 'терпеливый'},
    'devoted': {'fi': 'omistautunut', 'de': 'ergeben', 'es': 'devoto', 'fr': 'dévoué', 'it': 'devoto', 'pt': 'dedicado', 'nl': 'toegewijd', 'pl': 'oddany', 'sv': 'hängiven', 'no': 'hengiven', 'da': 'hengiven', 'zh': '忠心', 'ja': '献身的', 'ru': 'преданный'},
    'eager': {'fi': 'innokas', 'de': 'eifrig', 'es': 'ansioso', 'fr': 'enthousiaste', 'it': 'desideroso', 'pt': 'ansioso', 'nl': 'gretig', 'pl': 'chętny', 'sv': 'ivrig', 'no': 'ivrig', 'da': 'ivrig', 'zh': '渴望', 'ja': '熱心', 'ru': 'нетерпеливый'},
    'trainable': {'fi': 'koulutettava', 'de': 'trainierbar', 'es': 'entrenable', 'fr': 'dressable', 'it': 'addestrabile', 'pt': 'treinável', 'nl': 'trainbaar', 'pl': 'łatwy do szkolenia', 'sv': 'träningsbar', 'no': 'trenbar', 'da': 'trænbar', 'zh': '易训练', 'ja': '訓練しやすい', 'ru': 'обучаемый'},
    'adaptable': {'fi': 'sopeutuva', 'de': 'anpassungsfähig', 'es': 'adaptable', 'fr': 'adaptable', 'it': 'adattabile', 'pt': 'adaptável', 'nl': 'aanpasbaar', 'pl': 'adaptowalny', 'sv': 'anpassningsbar', 'no': 'tilpasningsdyktig', 'da': 'tilpasningsdygtig', 'zh': '适应性强', 'ja': '適応力', 'ru': 'приспособляемый'},
    'reserved': {'fi': 'varautunut', 'de': 'zurückhaltend', 'es': 'reservado', 'fr': 'réservé', 'it': 'riservato', 'pt': 'reservado', 'nl': 'gereserveerd', 'pl': 'powściągliwy', 'sv': 'reserverad', 'no': 'reservert', 'da': 'reserveret', 'zh': '内敛', 'ja': '控えめ', 'ru': 'сдержанный'},
    'dignified': {'fi': 'arvokas', 'de': 'würdevoll', 'es': 'digno', 'fr': 'digne', 'it': 'dignitoso', 'pt': 'digno', 'nl': 'waardig', 'pl': 'dostojny', 'sv': 'värdig', 'no': 'verdig', 'da': 'værdig', 'zh': '高贵', 'ja': '威厳のある', 'ru': 'достойный'},
    'sensitive': {'fi': 'herkkä', 'de': 'sensibel', 'es': 'sensible', 'fr': 'sensible', 'it': 'sensibile', 'pt': 'sensível', 'nl': 'gevoelig', 'pl': 'wrażliwy', 'sv': 'känslig', 'no': 'følsom', 'da': 'følsom', 'zh': '敏感', 'ja': '繊細', 'ru': 'чувствительный'},
    'fearless': {'fi': 'peloton', 'de': 'furchtlos', 'es': 'intrépido', 'fr': 'intrépide', 'it': 'impavido', 'pt': 'destemido', 'nl': 'onverschrokken', 'pl': 'nieustraszony', 'sv': 'orädd', 'no': 'fryktløs', 'da': 'frygtløs', 'zh': '无畏', 'ja': '恐れ知らず', 'ru': 'бесстрашный'},
    'spirited': {'fi': 'tulinen', 'de': 'temperamentvoll', 'es': 'animado', 'fr': 'vif', 'it': 'vivace', 'pt': 'animado', 'nl': 'levendig', 'pl': 'żywiołowy', 'sv': 'livlig', 'no': 'livlig', 'da': 'livlig', 'zh': '活泼', 'ja': '元気いっぱい', 'ru': 'энергичный'},
    'loving': {'fi': 'rakastava', 'de': 'liebend', 'es': 'amoroso', 'fr': 'aimant', 'it': 'amorevole', 'pt': 'amoroso', 'nl': 'liefdevol', 'pl': 'kochający', 'sv': 'älskande', 'no': 'kjærlig', 'da': 'kærlig', 'zh': '深爱的', 'ja': '愛情深い', 'ru': 'любящий'},
    'obedient': {'fi': 'kuuliainen', 'de': 'gehorsam', 'es': 'obediente', 'fr': 'obéissant', 'it': 'obbediente', 'pt': 'obediente', 'nl': 'gehoorzaam', 'pl': 'posłuszny', 'sv': 'lydig', 'no': 'lydig', 'da': 'lydig', 'zh': '听话', 'ja': '従順', 'ru': 'послушный'},
    'athletic': {'fi': 'urheilullinen', 'de': 'athletisch', 'es': 'atlético', 'fr': 'athlétique', 'it': 'atletico', 'pt': 'atlético', 'nl': 'atletisch', 'pl': 'atletyczny', 'sv': 'atletisk', 'no': 'atletisk', 'da': 'atletisk', 'zh': '运动型', 'ja': '運動的', 'ru': 'атлетичный'},
    'agile': {'fi': 'ketterä', 'de': 'wendig', 'es': 'ágil', 'fr': 'agile', 'it': 'agile', 'pt': 'ágil', 'nl': 'behendig', 'pl': 'zwinny', 'sv': 'smidig', 'no': 'smidig', 'da': 'smidig', 'zh': '敏捷', 'ja': '俊敏', 'ru': 'проворный'},
    'smart': {'fi': 'fiksu', 'de': 'klug', 'es': 'listo', 'fr': 'malin', 'it': 'furbo', 'pt': 'esperto', 'nl': 'slim', 'pl': 'bystry', 'sv': 'smart', 'no': 'smart', 'da': 'klog', 'zh': '聪明', 'ja': '頭がいい', 'ru': 'смышленый'},
    'charming': {'fi': 'hurmaava', 'de': 'charmant', 'es': 'encantador', 'fr': 'charmant', 'it': 'affascinante', 'pt': 'charmoso', 'nl': 'charmant', 'pl': 'czarujący', 'sv': 'charmig', 'no': 'sjarmerende', 'da': 'charmerende', 'zh': '迷人', 'ja': '魅力的', 'ru': 'очаровательный'},
    'lively': {'fi': 'eloisa', 'de': 'lebhaft', 'es': 'vivaz', 'fr': 'vif', 'it': 'vivace', 'pt': 'vivo', 'nl': 'levendig', 'pl': 'żywy', 'sv': 'livlig', 'no': 'livlig', 'da': 'livlig', 'zh': '活泼', 'ja': '活発', 'ru': 'живой'},
    'bold': {'fi': 'rohkea', 'de': 'kühn', 'es': 'audaz', 'fr': 'audacieux', 'it': 'audace', 'pt': 'ousado', 'nl': 'gedurfd', 'pl': 'śmiały', 'sv': 'djärv', 'no': 'dristig', 'da': 'dristig', 'zh': '大胆', 'ja': '大胆', 'ru': 'смелый'},
    'watchful': {'fi': 'tarkkaavainen', 'de': 'wachsam', 'es': 'vigilante', 'fr': 'vigilant', 'it': 'vigile', 'pt': 'vigilante', 'nl': 'waakzaam', 'pl': 'czujny', 'sv': 'vaksam', 'no': 'årvåken', 'da': 'årvågen', 'zh': '警惕', 'ja': '用心深い', 'ru': 'бдительный'},
    'powerful': {'fi': 'voimakas', 'de': 'kraftvoll', 'es': 'poderoso', 'fr': 'puissant', 'it': 'potente', 'pt': 'poderoso', 'nl': 'krachtig', 'pl': 'potężny', 'sv': 'kraftfull', 'no': 'kraftfull', 'da': 'kraftfuld', 'zh': '强壮', 'ja': '力強い', 'ru': 'мощный'},
    'mischievous': {'fi': 'vallaton', 'de': 'schelmisch', 'es': 'travieso', 'fr': 'espiègle', 'it': 'birichino', 'pt': 'travesso', 'nl': 'ondeugend', 'pl': 'psotny', 'sv': 'busig', 'no': 'rampete', 'da': 'drillesyg', 'zh': '淘气', 'ja': 'いたずら好き', 'ru': 'озорной'},
    'noble': {'fi': 'jalo', 'de': 'edel', 'es': 'noble', 'fr': 'noble', 'it': 'nobile', 'pt': 'nobre', 'nl': 'nobel', 'pl': 'szlachetny', 'sv': 'ädel', 'no': 'edel', 'da': 'ædel', 'zh': '高贵', 'ja': '高貴', 'ru': 'благородный'},
    'steady': {'fi': 'vakaa', 'de': 'beständig', 'es': 'estable', 'fr': 'stable', 'it': 'stabile', 'pt': 'estável', 'nl': 'stabiel', 'pl': 'zrównoważony', 'sv': 'stadig', 'no': 'stabil', 'da': 'stabil', 'zh': '稳定', 'ja': '安定した', 'ru': 'устойчивый'},
    'sweet': {'fi': 'suloinen', 'de': 'süß', 'es': 'dulce', 'fr': 'doux', 'it': 'dolce', 'pt': 'doce', 'nl': 'lief', 'pl': 'słodki', 'sv': 'söt', 'no': 'søt', 'da': 'sød', 'zh': '甜美', 'ja': '優しい', 'ru': 'милый'},
    'happy': {'fi': 'iloinen', 'de': 'fröhlich', 'es': 'feliz', 'fr': 'heureux', 'it': 'felice', 'pt': 'feliz', 'nl': 'vrolijk', 'pl': 'szczęśliwy', 'sv': 'glad', 'no': 'glad', 'da': 'glad', 'zh': '快乐', 'ja': '幸せ', 'ru': 'счастливый'},
    'cheerful': {'fi': 'pirteä', 'de': 'fröhlich', 'es': 'alegre', 'fr': 'joyeux', 'it': 'allegro', 'pt': 'alegre', 'nl': 'opgewekt', 'pl': 'wesoły', 'sv': 'glad', 'no': 'munter', 'da': 'munter', 'zh': '开朗', 'ja': '陽気', 'ru': 'жизнерадостный'},
    'determined': {'fi': 'päättäväinen', 'de': 'entschlossen', 'es': 'decidido', 'fr': 'déterminé', 'it': 'determinato', 'pt': 'determinado', 'nl': 'vastberaden', 'pl': 'zdeterminowany', 'sv': 'beslutsam', 'no': 'bestemt', 'da': 'bestemt', 'zh': '坚定', 'ja': '決意のある', 'ru': 'решительный'},
    'territorial': {'fi': 'reviirihakuinen', 'de': 'territorial', 'es': 'territorial', 'fr': 'territorial', 'it': 'territoriale', 'pt': 'territorial', 'nl': 'territoriaal', 'pl': 'terytorialny', 'sv': 'territoriell', 'no': 'territoriell', 'da': 'territorial', 'zh': '领地性', 'ja': '縄張り意識', 'ru': 'территориальный'},
    'hardworking': {'fi': 'ahkera', 'de': 'fleißig', 'es': 'trabajador', 'fr': 'travailleur', 'it': 'laborioso', 'pt': 'trabalhador', 'nl': 'hardwerkend', 'pl': 'pracowity', 'sv': 'hårt arbetande', 'no': 'hardtarbeidende', 'da': 'hårdtarbejdende', 'zh': '勤劳', 'ja': '働き者', 'ru': 'трудолюбивый'},
    'sociable': {'fi': 'seurallinen', 'de': 'gesellig', 'es': 'sociable', 'fr': 'sociable', 'it': 'socievole', 'pt': 'sociável', 'nl': 'sociaal', 'pl': 'towarzyski', 'sv': 'sällskaplig', 'no': 'sosial', 'da': 'selskabelig', 'zh': '善于交际', 'ja': '社交的', 'ru': 'общительный'},
    'docile': {'fi': 'kiltti', 'de': 'fügsam', 'es': 'dócil', 'fr': 'docile', 'it': 'docile', 'pt': 'dócil', 'nl': 'volgzaam', 'pl': 'potulny', 'sv': 'foglig', 'no': 'føyelig', 'da': 'føjelig', 'zh': '温顺', 'ja': 'おとなしい', 'ru': 'послушный'},
    'easygoing': {'fi': 'rento', 'de': 'unkompliziert', 'es': 'tranquilo', 'fr': 'facile à vivre', 'it': 'accomodante', 'pt': 'descontraído', 'nl': 'relaxed', 'pl': 'wyluzowany', 'sv': 'lättsam', 'no': 'avslappet', 'da': 'afslappet', 'zh': '随和', 'ja': 'のんびり', 'ru': 'спокойный'},
    'versatile': {'fi': 'monipuolinen', 'de': 'vielseitig', 'es': 'versátil', 'fr': 'polyvalent', 'it': 'versatile', 'pt': 'versátil', 'nl': 'veelzijdig', 'pl': 'wszechstronny', 'sv': 'mångsidig', 'no': 'allsidig', 'da': 'alsidig', 'zh': '多才多艺', 'ja': '万能', 'ru': 'универсальный'},
    'regal': {'fi': 'kuninkaallinen', 'de': 'königlich', 'es': 'regio', 'fr': 'royal', 'it': 'regale', 'pt': 'régio', 'nl': 'koninklijk', 'pl': 'królewski', 'sv': 'kunglig', 'no': 'kongelig', 'da': 'kongelig', 'zh': '高贵', 'ja': '堂々とした', 'ru': 'царственный'},
    'graceful': {'fi': 'sulava', 'de': 'anmutig', 'es': 'elegante', 'fr': 'gracieux', 'it': 'aggraziato', 'pt': 'gracioso', 'nl': 'gracieus', 'pl': 'pełen wdzięku', 'sv': 'graciös', 'no': 'grasiøs', 'da': 'yndefuld', 'zh': '优雅', 'ja': '優雅', 'ru': 'грациозный'},
    'elegant': {'fi': 'elegantti', 'de': 'elegant', 'es': 'elegante', 'fr': 'élégant', 'it': 'elegante', 'pt': 'elegante', 'nl': 'elegant', 'pl': 'elegancki', 'sv': 'elegant', 'no': 'elegant', 'da': 'elegant', 'zh': '优雅', 'ja': 'エレガント', 'ru': 'элегантный'},
}

# Best For translations
BEST_FOR = {
    'Families with children': {'fi': 'Lapsiperheet', 'de': 'Familien mit Kindern', 'es': 'Familias con niños', 'fr': 'Familles avec enfants', 'it': 'Famiglie con bambini', 'pt': 'Famílias com crianças', 'nl': 'Gezinnen met kinderen', 'pl': 'Rodziny z dziećmi', 'sv': 'Familjer med barn', 'no': 'Familier med barn', 'da': 'Familier med børn', 'zh': '有孩子的家庭', 'ja': '子供のいる家庭', 'ru': 'Семьи с детьми'},
    'Active individuals': {'fi': 'Aktiiviset ihmiset', 'de': 'Aktive Personen', 'es': 'Personas activas', 'fr': 'Personnes actives', 'it': 'Persone attive', 'pt': 'Pessoas ativas', 'nl': 'Actieve mensen', 'pl': 'Aktywni ludzie', 'sv': 'Aktiva personer', 'no': 'Aktive personer', 'da': 'Aktive personer', 'zh': '活跃的人', 'ja': 'アクティブな人', 'ru': 'Активные люди'},
    'First-time dog owners': {'fi': 'Ensikertalaiset koiranomistajat', 'de': 'Erstbesitzer', 'es': 'Dueños primerizos', 'fr': 'Premiers propriétaires', 'it': 'Proprietari alle prime armi', 'pt': 'Donos de primeira viagem', 'nl': 'Beginnende hondenbezitters', 'pl': 'Początkujący właściciele', 'sv': 'Förstagångsägare', 'no': 'Førstegangseiere', 'da': 'Førstegangsejere', 'zh': '首次养狗者', 'ja': '初めての飼い主', 'ru': 'Начинающие владельцы'},
    'Homes with yards': {'fi': 'Kodit pihoilla', 'de': 'Häuser mit Garten', 'es': 'Casas con jardín', 'fr': 'Maisons avec jardin', 'it': 'Case con giardino', 'pt': 'Casas com quintal', 'nl': 'Huizen met tuin', 'pl': 'Domy z ogrodem', 'sv': 'Hus med trädgård', 'no': 'Hus med hage', 'da': 'Huse med have', 'zh': '有院子的家庭', 'ja': '庭付きの家', 'ru': 'Дома с двором'},
    'People who enjoy outdoor activities': {'fi': 'Ulkoilua rakastavat', 'de': 'Outdoor-Liebhaber', 'es': 'Amantes del aire libre', 'fr': 'Amateurs de plein air', 'it': 'Amanti delle attività all\'aperto', 'pt': 'Amantes de atividades ao ar livre', 'nl': 'Buitenmensen', 'pl': 'Miłośnicy plenerowych aktywności', 'sv': 'Friluftsälskare', 'no': 'Friluftsfolk', 'da': 'Friluftsfolk', 'zh': '户外活动爱好者', 'ja': 'アウトドア好き', 'ru': 'Любители активного отдыха'},
    'Apartment dwellers': {'fi': 'Kerrostaloasukkaat', 'de': 'Wohnungsbewohner', 'es': 'Residentes de apartamentos', 'fr': 'Résidents d\'appartement', 'it': 'Residenti in appartamento', 'pt': 'Moradores de apartamento', 'nl': 'Appartementbewoners', 'pl': 'Mieszkańcy mieszkań', 'sv': 'Lägenhetsboende', 'no': 'Leilighetsbeboere', 'da': 'Lejlighedsbeboere', 'zh': '公寓居民', 'ja': 'マンション住まい', 'ru': 'Жители квартир'},
    'Seniors': {'fi': 'Seniorit', 'de': 'Senioren', 'es': 'Personas mayores', 'fr': 'Seniors', 'it': 'Anziani', 'pt': 'Idosos', 'nl': 'Senioren', 'pl': 'Seniorzy', 'sv': 'Seniorer', 'no': 'Seniorer', 'da': 'Seniorer', 'zh': '老年人', 'ja': '高齢者', 'ru': 'Пожилые люди'},
    'Experienced owners': {'fi': 'Kokeneet omistajat', 'de': 'Erfahrene Besitzer', 'es': 'Dueños experimentados', 'fr': 'Propriétaires expérimentés', 'it': 'Proprietari esperti', 'pt': 'Donos experientes', 'nl': 'Ervaren eigenaren', 'pl': 'Doświadczeni właściciele', 'sv': 'Erfarna ägare', 'no': 'Erfarne eiere', 'da': 'Erfarne ejere', 'zh': '有经验的主人', 'ja': '経験豊富な飼い主', 'ru': 'Опытные владельцы'},
    'Singles and couples': {'fi': 'Yksinasuvat ja pariskunnat', 'de': 'Singles und Paare', 'es': 'Solteros y parejas', 'fr': 'Célibataires et couples', 'it': 'Single e coppie', 'pt': 'Solteiros e casais', 'nl': 'Singles en stellen', 'pl': 'Single i pary', 'sv': 'Singlar och par', 'no': 'Single og par', 'da': 'Singler og par', 'zh': '单身和情侣', 'ja': '独身者とカップル', 'ru': 'Одинокие и пары'},
    'Working from home': {'fi': 'Kotona työskentelevät', 'de': 'Heimarbeiter', 'es': 'Teletrabajadores', 'fr': 'Télétravailleurs', 'it': 'Lavoratori da casa', 'pt': 'Trabalhadores remotos', 'nl': 'Thuiswerkers', 'pl': 'Pracujący zdalnie', 'sv': 'Hemmaarbetande', 'no': 'Hjemmearbeidende', 'da': 'Hjemmearbejdende', 'zh': '居家办公者', 'ja': '在宅勤務者', 'ru': 'Работающие на дому'},
    'Allergy sufferers': {'fi': 'Allergikot', 'de': 'Allergiker', 'es': 'Alérgicos', 'fr': 'Allergiques', 'it': 'Allergici', 'pt': 'Alérgicos', 'nl': 'Allergielijders', 'pl': 'Alergicy', 'sv': 'Allergiker', 'no': 'Allergikere', 'da': 'Allergikere', 'zh': '过敏者', 'ja': 'アレルギー体質の人', 'ru': 'Аллергики'},
    'Those wanting a guard dog': {'fi': 'Vartijakoiraa haluavat', 'de': 'Wachhundsucher', 'es': 'Quienes buscan perro guardián', 'fr': 'Ceux qui veulent un chien de garde', 'it': 'Chi cerca un cane da guardia', 'pt': 'Quem quer um cão de guarda', 'nl': 'Wie een waakhond wil', 'pl': 'Szukający psa stróżującego', 'sv': 'De som vill ha vakthund', 'no': 'De som ønsker vakthund', 'da': 'De der ønsker vagthund', 'zh': '想要看门狗的人', 'ja': '番犬を求める人', 'ru': 'Желающие сторожевую собаку'},
    'Runners and hikers': {'fi': 'Juoksijat ja retkeilijät', 'de': 'Läufer und Wanderer', 'es': 'Corredores y excursionistas', 'fr': 'Coureurs et randonneurs', 'it': 'Corridori ed escursionisti', 'pt': 'Corredores e caminhantes', 'nl': 'Hardlopers en wandelaars', 'pl': 'Biegacze i wędrowcy', 'sv': 'Löpare och vandrare', 'no': 'Løpere og turgåere', 'da': 'Løbere og vandrere', 'zh': '跑步和徒步爱好者', 'ja': 'ランナーとハイカー', 'ru': 'Бегуны и туристы'},
}

# Not Ideal translations
NOT_IDEAL = {
    'Sedentary lifestyles': {'fi': 'Passiivinen elämäntapa', 'de': 'Sitzender Lebensstil', 'es': 'Estilos de vida sedentarios', 'fr': 'Modes de vie sédentaires', 'it': 'Stili di vita sedentari', 'pt': 'Estilos de vida sedentários', 'nl': 'Sedentaire levensstijl', 'pl': 'Siedzący tryb życia', 'sv': 'Stillasittande livsstil', 'no': 'Stillesittende livsstil', 'da': 'Stillesiddende livsstil', 'zh': '久坐的生活方式', 'ja': '運動不足の生活', 'ru': 'Малоподвижный образ жизни'},
    'Those away from home often': {'fi': 'Usein poissaolevat', 'de': 'Häufig abwesend', 'es': 'Ausentes frecuentes', 'fr': 'Souvent absents', 'it': 'Spesso fuori casa', 'pt': 'Frequentemente ausentes', 'nl': 'Vaak van huis', 'pl': 'Często nieobecni', 'sv': 'Ofta borta hemifrån', 'no': 'Ofte borte hjemmefra', 'da': 'Ofte væk hjemmefra', 'zh': '经常不在家的人', 'ja': '留守がちな人', 'ru': 'Часто отсутствующие дома'},
    'Allergy sufferers': {'fi': 'Allergikot', 'de': 'Allergiker', 'es': 'Alérgicos', 'fr': 'Allergiques', 'it': 'Allergici', 'pt': 'Alérgicos', 'nl': 'Allergielijders', 'pl': 'Alergicy', 'sv': 'Allergiker', 'no': 'Allergikere', 'da': 'Allergikere', 'zh': '过敏者', 'ja': 'アレルギー体質の人', 'ru': 'Аллергики'},
    'Small apartment dwellers': {'fi': 'Pienissä asunnoissa asuvat', 'de': 'Kleine Wohnungen', 'es': 'Apartamentos pequeños', 'fr': 'Petits appartements', 'it': 'Piccoli appartamenti', 'pt': 'Apartamentos pequenos', 'nl': 'Kleine appartementen', 'pl': 'Małe mieszkania', 'sv': 'Små lägenheter', 'no': 'Små leiligheter', 'da': 'Små lejligheder', 'zh': '小公寓居民', 'ja': '狭いアパート', 'ru': 'Маленькие квартиры'},
    'First-time owners': {'fi': 'Ensikertalaiset', 'de': 'Erstbesitzer', 'es': 'Dueños primerizos', 'fr': 'Premiers propriétaires', 'it': 'Proprietari alle prime armi', 'pt': 'Donos de primeira viagem', 'nl': 'Beginnende eigenaren', 'pl': 'Początkujący właściciele', 'sv': 'Förstagångsägare', 'no': 'Førstegangseiere', 'da': 'Førstegangsejere', 'zh': '首次养狗者', 'ja': '初めての飼い主', 'ru': 'Начинающие владельцы'},
    'Families with very young children': {'fi': 'Pienten lasten perheet', 'de': 'Familien mit Kleinkindern', 'es': 'Familias con niños muy pequeños', 'fr': 'Familles avec très jeunes enfants', 'it': 'Famiglie con bambini molto piccoli', 'pt': 'Famílias com crianças muito pequenas', 'nl': 'Gezinnen met hele jonge kinderen', 'pl': 'Rodziny z bardzo małymi dziećmi', 'sv': 'Familjer med mycket små barn', 'no': 'Familier med veldig små barn', 'da': 'Familier med meget små børn', 'zh': '有幼儿的家庭', 'ja': '幼い子供のいる家庭', 'ru': 'Семьи с маленькими детьми'},
    'Hot climates': {'fi': 'Kuuma ilmasto', 'de': 'Heißes Klima', 'es': 'Climas calurosos', 'fr': 'Climats chauds', 'it': 'Climi caldi', 'pt': 'Climas quentes', 'nl': 'Warm klimaat', 'pl': 'Gorący klimat', 'sv': 'Varmt klimat', 'no': 'Varmt klima', 'da': 'Varmt klima', 'zh': '炎热气候', 'ja': '暑い気候', 'ru': 'Жаркий климат'},
    'Cold climates': {'fi': 'Kylmä ilmasto', 'de': 'Kaltes Klima', 'es': 'Climas fríos', 'fr': 'Climats froids', 'it': 'Climi freddi', 'pt': 'Climas frios', 'nl': 'Koud klimaat', 'pl': 'Zimny klimat', 'sv': 'Kallt klimat', 'no': 'Kaldt klima', 'da': 'Koldt klima', 'zh': '寒冷气候', 'ja': '寒い気候', 'ru': 'Холодный климат'},
    'Novice trainers': {'fi': 'Aloittelevat kouluttajat', 'de': 'Anfänger-Trainer', 'es': 'Entrenadores novatos', 'fr': 'Dresseurs novices', 'it': 'Addestratori principianti', 'pt': 'Treinadores novatos', 'nl': 'Beginnende trainers', 'pl': 'Początkujący treserzy', 'sv': 'Nybörjartränare', 'no': 'Nybegynnertrenere', 'da': 'Nybegyndere', 'zh': '新手训练师', 'ja': '初心者トレーナー', 'ru': 'Начинающие дрессировщики'},
    'Homes with small pets': {'fi': 'Kodit pienien lemmikkien kanssa', 'de': 'Haushalte mit Kleintieren', 'es': 'Hogares con mascotas pequeñas', 'fr': 'Foyers avec petits animaux', 'it': 'Case con piccoli animali', 'pt': 'Casas com animais pequenos', 'nl': 'Huizen met kleine huisdieren', 'pl': 'Domy z małymi zwierzętami', 'sv': 'Hem med små husdjur', 'no': 'Hjem med små kjæledyr', 'da': 'Hjem med små kæledyr', 'zh': '有小宠物的家庭', 'ja': '小動物のいる家', 'ru': 'Дома с мелкими питомцами'},
    'Those who dislike grooming': {'fi': 'Turkinhoitoa välttelevät', 'de': 'Pflegemuffel', 'es': 'Quienes no les gusta el aseo', 'fr': 'Ceux qui n\'aiment pas le toilettage', 'it': 'Chi non ama la toelettatura', 'pt': 'Quem não gosta de tosa', 'nl': 'Wie niet van verzorgen houdt', 'pl': 'Niechętni do pielęgnacji', 'sv': 'De som ogillar pälsvård', 'no': 'De som misliker stell', 'da': 'De der ikke bryder sig om pleje', 'zh': '不喜欢美容的人', 'ja': 'グルーミングが苦手な人', 'ru': 'Не любящие уход'},
    'Quiet neighborhoods required': {'fi': 'Hiljaisuutta vaativat', 'de': 'Ruhige Nachbarschaft erforderlich', 'es': 'Vecindarios tranquilos requeridos', 'fr': 'Quartiers calmes requis', 'it': 'Quartieri tranquilli richiesti', 'pt': 'Bairros silenciosos necessários', 'nl': 'Stille buurten vereist', 'pl': 'Wymagane ciche sąsiedztwo', 'sv': 'Tysta grannskap krävs', 'no': 'Rolige nabolag kreves', 'da': 'Rolige nabolag påkrævet', 'zh': '需要安静的社区', 'ja': '静かな環境が必要', 'ru': 'Требуется тихий район'},
}

# "years" translation
YEARS = {'fi': 'vuotta', 'de': 'Jahre', 'es': 'años', 'fr': 'ans', 'it': 'anni', 'pt': 'anos', 'nl': 'jaar', 'pl': 'lat', 'sv': 'år', 'no': 'år', 'da': 'år', 'zh': '年', 'ja': '年', 'ru': 'лет'}

def translate_trait(trait, lang):
    """Translate a single temperament trait"""
    trait_lower = trait.lower().strip()
    if trait_lower in TRAITS and lang in TRAITS[trait_lower]:
        return TRAITS[trait_lower][lang]
    return trait  # Return original if no translation

def translate_best_for(item, lang):
    """Translate a Best For item"""
    if item in BEST_FOR and lang in BEST_FOR[item]:
        return BEST_FOR[item][lang]
    return item

def translate_not_ideal(item, lang):
    """Translate a Not Ideal item"""
    if item in NOT_IDEAL and lang in NOT_IDEAL[item]:
        return NOT_IDEAL[item][lang]
    return item

def translate_years(text, lang):
    """Replace 'years' with translated version"""
    if lang in YEARS:
        return text.replace(' years', ' ' + YEARS[lang]).replace(' year', ' ' + YEARS[lang])
    return text
