#!/usr/bin/env python3
"""Generate missing JSON for breeds 111-150"""

import json
import os

MISSING_BREEDS = [
    {"id": "glen-of-imaal-terrier", "name": "Glen of Imaal Terrier", "group": "terrier", "origin": "Ireland", "lifespan": "10-15 years", "size": {"height_cm": "32-36", "weight_kg": "14-18", "category": "medium"}, "ratings": {"size": 3, "energy": 3, "grooming": 2, "sociability": 4, "trainability": 3, "barking": 2, "kid_friendly": 4, "apartment_ok": 4}, "coat_type": "Medium-length, harsh", "coat_colors": ["wheaten", "blue", "brindle"], "shedding": "low", "temperament": ["gentle", "spirited", "brave", "loyal", "patient"], "overview": "A sturdy Irish terrier bred for hunting badgers and foxes. Glens are gentle, patient dogs with a big heart despite their medium size.", "best_for": ["Families", "Those wanting a calm terrier", "Apartment dwellers"], "not_for": ["Those with small pets", "Wanting a high-energy dog"]},
    
    {"id": "kerry-blue-terrier", "name": "Kerry Blue Terrier", "group": "terrier", "origin": "Ireland", "lifespan": "12-15 years", "size": {"height_cm": "44-51", "weight_kg": "15-18", "category": "medium"}, "ratings": {"size": 3, "energy": 4, "grooming": 4, "sociability": 3, "trainability": 4, "barking": 3, "kid_friendly": 4, "apartment_ok": 3}, "coat_type": "Soft, wavy, dense", "coat_colors": ["blue-gray"], "shedding": "low", "temperament": ["alert", "spirited", "loyal", "intelligent", "strong-willed"], "overview": "Ireland's national terrier, the Kerry Blue has a distinctive soft, wavy blue-gray coat. They're versatile working dogs and loyal companions.", "best_for": ["Active families", "Those wanting a unique breed", "Experienced owners"], "not_for": ["Multi-dog homes", "First-time owners"]},
    
    {"id": "manchester-terrier", "name": "Manchester Terrier", "group": "terrier", "origin": "England", "lifespan": "15-17 years", "size": {"height_cm": "38-41", "weight_kg": "5-10", "category": "small"}, "ratings": {"size": 2, "energy": 4, "grooming": 1, "sociability": 3, "trainability": 4, "barking": 3, "kid_friendly": 4, "apartment_ok": 5}, "coat_type": "Short, smooth, glossy", "coat_colors": ["black and tan"], "shedding": "low", "temperament": ["spirited", "alert", "keen", "devoted", "athletic"], "overview": "A sleek, athletic terrier bred for ratting and rabbit coursing. Manchesters are devoted, spirited companions with low grooming needs.", "best_for": ["Active owners", "Apartment dwellers", "Those wanting low grooming"], "not_for": ["Homes with small pets", "Very cold climates"]},
    
    {"id": "bedlington-terrier", "name": "Bedlington Terrier", "group": "terrier", "origin": "England", "lifespan": "11-16 years", "size": {"height_cm": "38-44", "weight_kg": "8-10", "category": "small"}, "ratings": {"size": 2, "energy": 4, "grooming": 4, "sociability": 4, "trainability": 4, "barking": 3, "kid_friendly": 4, "apartment_ok": 4}, "coat_type": "Crisp, curly, linty", "coat_colors": ["blue", "liver", "sandy"], "shedding": "low", "temperament": ["loyal", "charming", "spirited", "intelligent", "affectionate"], "overview": "With their lamb-like appearance, Bedlingtons are deceptively gentle-looking but retain true terrier spirit. They're loyal, charming companions.", "best_for": ["Families", "Allergy sufferers", "Those wanting a unique breed"], "not_for": ["Those avoiding grooming", "Homes with small pets"]},
    
    {"id": "border-terrier", "name": "Border Terrier", "group": "terrier", "origin": "England/Scotland", "lifespan": "12-15 years", "size": {"height_cm": "28-40", "weight_kg": "5-7", "category": "small"}, "ratings": {"size": 2, "energy": 4, "grooming": 2, "sociability": 5, "trainability": 4, "barking": 3, "kid_friendly": 5, "apartment_ok": 4}, "coat_type": "Wiry, dense double coat", "coat_colors": ["red", "grizzle and tan", "blue and tan", "wheaten"], "shedding": "low", "temperament": ["affectionate", "happy", "plucky", "alert", "obedient"], "overview": "One of Britain's oldest terriers, Border Terriers are happy, affectionate dogs who get along well with people and other dogs.", "best_for": ["Families with children", "Active owners", "Multi-pet homes"], "not_for": ["Homes with small pets", "Those wanting a guard dog"]},
    
    {"id": "borzoi", "name": "Borzoi", "group": "hound", "origin": "Russia", "lifespan": "9-14 years", "size": {"height_cm": "68-85", "weight_kg": "27-48", "category": "large"}, "ratings": {"size": 4, "energy": 3, "grooming": 3, "sociability": 3, "trainability": 2, "barking": 1, "kid_friendly": 3, "apartment_ok": 3}, "coat_type": "Long, silky, wavy or curly", "coat_colors": ["any color"], "shedding": "moderate", "temperament": ["graceful", "quiet", "independent", "athletic", "gentle"], "overview": "The aristocratic Russian wolfhound, Borzoi are graceful, quiet dogs with a gentle demeanor. They're independent but devoted to their families.", "best_for": ["Quiet households", "Those wanting an elegant breed", "Experienced sighthound owners"], "not_for": ["Homes with small pets", "Those wanting an obedient dog"]},
    
    {"id": "irish-wolfhound", "name": "Irish Wolfhound", "group": "hound", "origin": "Ireland", "lifespan": "6-8 years", "size": {"height_cm": "76-90", "weight_kg": "48-70", "category": "giant"}, "ratings": {"size": 5, "energy": 3, "grooming": 2, "sociability": 5, "trainability": 3, "barking": 2, "kid_friendly": 5, "apartment_ok": 2}, "coat_type": "Rough, wiry", "coat_colors": ["gray", "brindle", "red", "black", "white", "fawn"], "shedding": "moderate", "temperament": ["courageous", "dignified", "calm", "gentle", "patient"], "overview": "The tallest of all dog breeds, Irish Wolfhounds are gentle giants with patient, dignified personalities. Despite their size, they're calm house dogs.", "best_for": ["Families with space", "Those wanting a gentle giant", "Patient owners"], "not_for": ["Small homes", "Those on tight budgets", "Very long lifespans"]},
    
    {"id": "scottish-deerhound", "name": "Scottish Deerhound", "group": "hound", "origin": "Scotland", "lifespan": "8-11 years", "size": {"height_cm": "71-81", "weight_kg": "34-50", "category": "giant"}, "ratings": {"size": 5, "energy": 3, "grooming": 2, "sociability": 4, "trainability": 3, "barking": 2, "kid_friendly": 4, "apartment_ok": 2}, "coat_type": "Harsh, wiry", "coat_colors": ["dark blue-gray", "gray", "brindle", "fawn"], "shedding": "moderate", "temperament": ["gentle", "dignified", "polite", "friendly", "docile"], "overview": "The Royal Dog of Scotland, Deerhounds are gentle, dignified sighthounds. They're quiet, polite house dogs despite their impressive size.", "best_for": ["Those wanting a gentle giant", "Quiet households", "Rural homes"], "not_for": ["Small spaces", "Homes with small pets"]},
    
    {"id": "petit-basset-griffon-vendeen", "name": "Petit Basset Griffon Vendéen", "group": "hound", "origin": "France", "lifespan": "14-16 years", "size": {"height_cm": "32-38", "weight_kg": "14-18", "category": "small"}, "ratings": {"size": 2, "energy": 4, "grooming": 3, "sociability": 5, "trainability": 3, "barking": 4, "kid_friendly": 5, "apartment_ok": 3}, "coat_type": "Rough, harsh", "coat_colors": ["white with any combination"], "shedding": "moderate", "temperament": ["happy", "extroverted", "independent", "alert", "vivacious"], "overview": "The PBGV is a happy, extroverted French scent hound. Their cheerful personality and shaggy appearance make them delightful companions.", "best_for": ["Active families", "Multi-dog homes", "Those wanting a happy breed"], "not_for": ["Those wanting a quiet dog", "Off-leash reliability"]},
    
    {"id": "otterhound", "name": "Otterhound", "group": "hound", "origin": "England", "lifespan": "10-13 years", "size": {"height_cm": "61-69", "weight_kg": "36-54", "category": "large"}, "ratings": {"size": 4, "energy": 4, "grooming": 3, "sociability": 5, "trainability": 2, "barking": 4, "kid_friendly": 5, "apartment_ok": 2}, "coat_type": "Rough, dense, double coat", "coat_colors": ["any color"], "shedding": "moderate", "temperament": ["amiable", "boisterous", "even-tempered", "friendly", "independent"], "overview": "One of the rarest breeds, Otterhounds are friendly, boisterous dogs with webbed feet and a love of water. They're gentle family companions.", "best_for": ["Active families", "Those wanting a rare breed", "Water enthusiasts"], "not_for": ["Those wanting an obedient dog", "Neat freaks"]},
    
    {"id": "black-and-tan-coonhound", "name": "Black and Tan Coonhound", "group": "hound", "origin": "United States", "lifespan": "10-12 years", "size": {"height_cm": "58-69", "weight_kg": "29-50", "category": "large"}, "ratings": {"size": 4, "energy": 4, "grooming": 1, "sociability": 5, "trainability": 3, "barking": 5, "kid_friendly": 5, "apartment_ok": 1}, "coat_type": "Short, dense", "coat_colors": ["black and tan"], "shedding": "moderate", "temperament": ["easygoing", "friendly", "alert", "trusting", "gentle"], "overview": "A true American breed, the Black and Tan Coonhound is an easygoing, friendly dog with a melodious voice. They're excellent family companions.", "best_for": ["Rural families", "Hunters", "Those who don't mind barking"], "not_for": ["Apartment dwellers", "Those wanting a quiet dog"]},
    
    {"id": "bluetick-coonhound", "name": "Bluetick Coonhound", "group": "hound", "origin": "United States", "lifespan": "11-12 years", "size": {"height_cm": "53-69", "weight_kg": "20-36", "category": "large"}, "ratings": {"size": 4, "energy": 4, "grooming": 1, "sociability": 5, "trainability": 3, "barking": 5, "kid_friendly": 5, "apartment_ok": 1}, "coat_type": "Short, glossy, dense", "coat_colors": ["blue ticked with tan"], "shedding": "moderate", "temperament": ["friendly", "intelligent", "devoted", "athletic", "tenacious"], "overview": "Named for their beautiful mottled blue coat, Blueticks are devoted, athletic hunting dogs who make loving family companions.", "best_for": ["Hunters", "Active rural families", "Those who appreciate their voice"], "not_for": ["Apartment dwellers", "Those wanting a quiet dog"]},
    
    {"id": "redbone-coonhound", "name": "Redbone Coonhound", "group": "hound", "origin": "United States", "lifespan": "11-12 years", "size": {"height_cm": "53-69", "weight_kg": "20-32", "category": "large"}, "ratings": {"size": 4, "energy": 4, "grooming": 1, "sociability": 5, "trainability": 3, "barking": 5, "kid_friendly": 5, "apartment_ok": 1}, "coat_type": "Short, smooth", "coat_colors": ["red"], "shedding": "moderate", "temperament": ["even-tempered", "amiable", "eager", "mellow", "loving"], "overview": "The Redbone Coonhound is an even-tempered, mellow dog with a stunning red coat. They're versatile hunters and loving family dogs.", "best_for": ["Active families", "Hunters", "Multi-pet homes"], "not_for": ["Apartment dwellers", "Those wanting a quiet dog"]},
    
    {"id": "treeing-walker-coonhound", "name": "Treeing Walker Coonhound", "group": "hound", "origin": "United States", "lifespan": "12-13 years", "size": {"height_cm": "51-69", "weight_kg": "20-32", "category": "large"}, "ratings": {"size": 4, "energy": 5, "grooming": 1, "sociability": 5, "trainability": 3, "barking": 5, "kid_friendly": 5, "apartment_ok": 1}, "coat_type": "Short, smooth, glossy", "coat_colors": ["tricolor"], "shedding": "moderate", "temperament": ["smart", "brave", "courteous", "loving", "confident"], "overview": "A fast, athletic coonhound known for their speed and endurance. Treeing Walkers are smart, loving dogs with a competitive spirit.", "best_for": ["Hunters", "Very active families", "Rural homes"], "not_for": ["Apartment dwellers", "Sedentary owners"]},
    
    {"id": "plott-hound", "name": "Plott Hound", "group": "hound", "origin": "United States", "lifespan": "12-14 years", "size": {"height_cm": "51-64", "weight_kg": "18-27", "category": "medium"}, "ratings": {"size": 3, "energy": 5, "grooming": 1, "sociability": 4, "trainability": 3, "barking": 4, "kid_friendly": 4, "apartment_ok": 2}, "coat_type": "Short, smooth, glossy", "coat_colors": ["brindle"], "shedding": "moderate", "temperament": ["bold", "loyal", "alert", "intelligent", "confident"], "overview": "North Carolina's state dog, the Plott Hound is a bold, loyal pack hunter. They're intelligent, confident dogs who bond closely with family.", "best_for": ["Hunters", "Active families", "Those wanting a loyal companion"], "not_for": ["Apartment dwellers", "First-time owners"]},
    
    {"id": "harrier", "name": "Harrier", "group": "hound", "origin": "England", "lifespan": "12-15 years", "size": {"height_cm": "48-53", "weight_kg": "18-27", "category": "medium"}, "ratings": {"size": 3, "energy": 4, "grooming": 1, "sociability": 5, "trainability": 3, "barking": 4, "kid_friendly": 5, "apartment_ok": 2}, "coat_type": "Short, dense, glossy", "coat_colors": ["any hound color"], "shedding": "moderate", "temperament": ["friendly", "outgoing", "active", "people-oriented", "playful"], "overview": "Often described as a Beagle on steroids, Harriers are friendly, outgoing pack hounds who love company and activity.", "best_for": ["Active families", "Multi-dog homes", "Runners"], "not_for": ["Apartment dwellers", "Those wanting a quiet dog"]},
    
    {"id": "english-foxhound", "name": "English Foxhound", "group": "hound", "origin": "England", "lifespan": "10-13 years", "size": {"height_cm": "53-64", "weight_kg": "25-34", "category": "large"}, "ratings": {"size": 4, "energy": 5, "grooming": 1, "sociability": 5, "trainability": 3, "barking": 4, "kid_friendly": 5, "apartment_ok": 1}, "coat_type": "Short, dense, hard", "coat_colors": ["tricolor", "bicolor"], "shedding": "moderate", "temperament": ["friendly", "gentle", "sociable", "tolerant", "active"], "overview": "Bred for fox hunting in packs, English Foxhounds are gentle, sociable dogs who thrive with company. They're rarely kept as pets.", "best_for": ["Very active owners", "Multi-dog homes", "Rural settings"], "not_for": ["Apartment dwellers", "Single-dog homes"]},
    
    {"id": "american-foxhound", "name": "American Foxhound", "group": "hound", "origin": "United States", "lifespan": "11-13 years", "size": {"height_cm": "53-64", "weight_kg": "25-32", "category": "large"}, "ratings": {"size": 4, "energy": 5, "grooming": 1, "sociability": 5, "trainability": 2, "barking": 5, "kid_friendly": 5, "apartment_ok": 1}, "coat_type": "Medium-length, hard", "coat_colors": ["any color"], "shedding": "moderate", "temperament": ["sweet", "independent", "easygoing", "loyal", "kind"], "overview": "Virginia's state dog, the American Foxhound is a sweet, easygoing breed with a musical bay. They're independent but loving companions.", "best_for": ["Rural homes", "Very active owners", "Multi-dog homes"], "not_for": ["Apartment dwellers", "Those wanting an obedient dog"]},
    
    {"id": "ibizan-hound", "name": "Ibizan Hound", "group": "hound", "origin": "Spain (Ibiza)", "lifespan": "11-14 years", "size": {"height_cm": "56-74", "weight_kg": "20-29", "category": "large"}, "ratings": {"size": 4, "energy": 4, "grooming": 1, "sociability": 4, "trainability": 3, "barking": 3, "kid_friendly": 4, "apartment_ok": 3}, "coat_type": "Smooth or wire", "coat_colors": ["white", "red", "white and red"], "shedding": "low", "temperament": ["clownish", "family-oriented", "even-tempered", "polite", "independent"], "overview": "An ancient breed from the Balearic Islands, Ibizans are elegant, athletic sighthounds with a clownish personality. They're wonderful family dogs.", "best_for": ["Active families", "Those wanting a unique breed", "Warm climates"], "not_for": ["Homes with small pets", "Cold climates"]},
    
    {"id": "cirneco-delletna", "name": "Cirneco dell'Etna", "group": "hound", "origin": "Italy (Sicily)", "lifespan": "12-14 years", "size": {"height_cm": "42-52", "weight_kg": "8-12", "category": "medium"}, "ratings": {"size": 3, "energy": 4, "grooming": 1, "sociability": 4, "trainability": 3, "barking": 2, "kid_friendly": 4, "apartment_ok": 4}, "coat_type": "Short, sleek", "coat_colors": ["tan", "chestnut"], "shedding": "low", "temperament": ["affectionate", "friendly", "independent", "alert", "gentle"], "overview": "An ancient Sicilian sighthound, the Cirneco is a small, elegant dog with low grooming needs. They're affectionate, gentle companions.", "best_for": ["Active owners", "Apartment dwellers", "Warm climates"], "not_for": ["Cold climates", "Off-leash areas with small animals"]},
    
    {"id": "giant-schnauzer", "name": "Giant Schnauzer", "group": "working", "origin": "Germany", "lifespan": "12-15 years", "size": {"height_cm": "60-70", "weight_kg": "25-48", "category": "large"}, "ratings": {"size": 4, "energy": 5, "grooming": 4, "sociability": 3, "trainability": 4, "barking": 3, "kid_friendly": 4, "apartment_ok": 2}, "coat_type": "Dense, wiry, harsh", "coat_colors": ["black", "salt and pepper"], "shedding": "low", "temperament": ["loyal", "alert", "trainable", "powerful", "intelligent"], "overview": "The largest of the three Schnauzer breeds, Giants are powerful, intelligent working dogs. They're loyal guardians and versatile workers.", "best_for": ["Experienced owners", "Active families", "Those wanting a guardian"], "not_for": ["First-time owners", "Sedentary owners"]},
    
    {"id": "standard-schnauzer", "name": "Standard Schnauzer", "group": "working", "origin": "Germany", "lifespan": "13-16 years", "size": {"height_cm": "44-50", "weight_kg": "14-20", "category": "medium"}, "ratings": {"size": 3, "energy": 4, "grooming": 4, "sociability": 4, "trainability": 4, "barking": 3, "kid_friendly": 4, "apartment_ok": 3}, "coat_type": "Dense, wiry, harsh", "coat_colors": ["black", "salt and pepper"], "shedding": "low", "temperament": ["fearless", "smart", "spirited", "reliable", "good-natured"], "overview": "The original Schnauzer, Standards are versatile, intelligent dogs. They're spirited but reliable, making excellent family companions and watchdogs.", "best_for": ["Active families", "Those wanting a versatile breed", "Experienced owners"], "not_for": ["First-time owners", "Those avoiding grooming"]},
    
    {"id": "bouvier-des-flandres", "name": "Bouvier des Flandres", "group": "herding", "origin": "Belgium/France", "lifespan": "10-12 years", "size": {"height_cm": "59-68", "weight_kg": "27-40", "category": "large"}, "ratings": {"size": 4, "energy": 4, "grooming": 4, "sociability": 3, "trainability": 4, "barking": 2, "kid_friendly": 4, "apartment_ok": 2}, "coat_type": "Rough, tousled, double coat", "coat_colors": ["fawn", "black", "gray", "brindle"], "shedding": "low", "temperament": ["loyal", "protective", "strong-willed", "gentle", "rational"], "overview": "A powerful Belgian farm dog, the Bouvier is a loyal, protective companion. They're gentle with family but can be reserved with strangers.", "best_for": ["Experienced owners", "Those wanting a guardian", "Active families"], "not_for": ["First-time owners", "Those avoiding grooming"]},
    
    {"id": "old-english-sheepdog", "name": "Old English Sheepdog", "group": "herding", "origin": "England", "lifespan": "10-12 years", "size": {"height_cm": "54-61", "weight_kg": "27-45", "category": "large"}, "ratings": {"size": 4, "energy": 3, "grooming": 5, "sociability": 5, "trainability": 4, "barking": 3, "kid_friendly": 5, "apartment_ok": 2}, "coat_type": "Profuse, shaggy double coat", "coat_colors": ["gray and white", "blue and white"], "shedding": "high", "temperament": ["adaptable", "gentle", "intelligent", "playful", "sociable"], "overview": "The iconic shaggy dog, Old English Sheepdogs are gentle, playful companions. Their distinctive coat requires significant maintenance.", "best_for": ["Families with children", "Those who enjoy grooming", "Homes with space"], "not_for": ["Those avoiding grooming", "Neat freaks"]},
    
    {"id": "polish-lowland-sheepdog", "name": "Polish Lowland Sheepdog", "group": "herding", "origin": "Poland", "lifespan": "12-14 years", "size": {"height_cm": "42-52", "weight_kg": "14-23", "category": "medium"}, "ratings": {"size": 3, "energy": 4, "grooming": 4, "sociability": 3, "trainability": 4, "barking": 3, "kid_friendly": 4, "apartment_ok": 3}, "coat_type": "Long, thick, shaggy", "coat_colors": ["any color"], "shedding": "low", "temperament": ["confident", "clever", "perceptive", "even-tempered", "self-confident"], "overview": "Known as PON in Poland, this shaggy herding dog is confident and clever. They're excellent watchdogs and loyal family companions.", "best_for": ["Experienced owners", "Active families", "Those wanting a watchdog"], "not_for": ["First-time owners", "Those avoiding grooming"]},
    
    {"id": "bergamasco-sheepdog", "name": "Bergamasco Sheepdog", "group": "herding", "origin": "Italy", "lifespan": "13-15 years", "size": {"height_cm": "54-62", "weight_kg": "26-38", "category": "large"}, "ratings": {"size": 4, "energy": 3, "grooming": 2, "sociability": 4, "trainability": 4, "barking": 2, "kid_friendly": 5, "apartment_ok": 2}, "coat_type": "Matted flocks (unique)", "coat_colors": ["gray", "black"], "shedding": "low", "temperament": ["patient", "intelligent", "eager", "protective", "sociable"], "overview": "Known for their unique felted coat that forms natural mats called flocks, Bergamascos are patient, intelligent herding dogs.", "best_for": ["Families with children", "Those wanting a unique breed", "Patient owners"], "not_for": ["Hot climates", "Those wanting a neat-looking dog"]},
    
    {"id": "canaan-dog", "name": "Canaan Dog", "group": "herding", "origin": "Israel", "lifespan": "12-15 years", "size": {"height_cm": "48-61", "weight_kg": "16-25", "category": "medium"}, "ratings": {"size": 3, "energy": 4, "grooming": 2, "sociability": 3, "trainability": 3, "barking": 4, "kid_friendly": 4, "apartment_ok": 3}, "coat_type": "Double coat, harsh outer", "coat_colors": ["white with patches", "solid colors"], "shedding": "moderate", "temperament": ["alert", "vigilant", "devoted", "docile", "territorial"], "overview": "Israel's national dog, the Canaan is an ancient, primitive breed. They're alert, devoted dogs who bond closely with family.", "best_for": ["Experienced owners", "Those wanting a watchdog", "Active families"], "not_for": ["First-time owners", "Multi-dog homes"]},
    
    {"id": "icelandic-sheepdog", "name": "Icelandic Sheepdog", "group": "herding", "origin": "Iceland", "lifespan": "12-14 years", "size": {"height_cm": "42-46", "weight_kg": "9-14", "category": "medium"}, "ratings": {"size": 3, "energy": 4, "grooming": 3, "sociability": 5, "trainability": 4, "barking": 4, "kid_friendly": 5, "apartment_ok": 3}, "coat_type": "Double coat, long or short", "coat_colors": ["tan", "chocolate", "gray", "black"], "shedding": "high", "temperament": ["cheerful", "friendly", "inquisitive", "playful", "alert"], "overview": "Iceland's only native dog, this cheerful spitz-type breed is friendly and playful. They're excellent family companions with a love for their people.", "best_for": ["Families", "Active owners", "Those wanting a cheerful breed"], "not_for": ["Those wanting a quiet dog", "Those who dislike shedding"]},
    
    {"id": "swedish-vallhund", "name": "Swedish Vallhund", "group": "herding", "origin": "Sweden", "lifespan": "12-15 years", "size": {"height_cm": "30-35", "weight_kg": "9-14", "category": "small"}, "ratings": {"size": 2, "energy": 4, "grooming": 2, "sociability": 4, "trainability": 4, "barking": 4, "kid_friendly": 4, "apartment_ok": 4}, "coat_type": "Medium-length double coat", "coat_colors": ["gray", "red-brown", "grayish-yellow"], "shedding": "moderate", "temperament": ["friendly", "energetic", "alert", "intelligent", "fearless"], "overview": "A Viking-era cattle dog, the Swedish Vallhund looks like a wolf-gray Corgi. They're energetic, intelligent dogs with a fearless attitude.", "best_for": ["Active families", "Dog sports enthusiasts", "Apartment dwellers"], "not_for": ["Those wanting a quiet dog", "Sedentary owners"]},
    
    {"id": "mudi", "name": "Mudi", "group": "herding", "origin": "Hungary", "lifespan": "12-14 years", "size": {"height_cm": "36-47", "weight_kg": "8-13", "category": "medium"}, "ratings": {"size": 3, "energy": 5, "grooming": 2, "sociability": 3, "trainability": 5, "barking": 4, "kid_friendly": 4, "apartment_ok": 3}, "coat_type": "Wavy or curly", "coat_colors": ["black", "white", "fawn", "gray", "brown", "merle"], "shedding": "moderate", "temperament": ["intelligent", "alert", "versatile", "energetic", "biddable"], "overview": "A rare Hungarian herding breed, the Mudi is extremely versatile and intelligent. They excel at many dog sports and make loyal companions.", "best_for": ["Dog sports enthusiasts", "Experienced owners", "Active families"], "not_for": ["First-time owners", "Sedentary owners"]},
    
    {"id": "spanish-water-dog", "name": "Spanish Water Dog", "group": "herding", "origin": "Spain", "lifespan": "12-14 years", "size": {"height_cm": "40-50", "weight_kg": "14-22", "category": "medium"}, "ratings": {"size": 3, "energy": 4, "grooming": 2, "sociability": 4, "trainability": 4, "barking": 3, "kid_friendly": 4, "apartment_ok": 3}, "coat_type": "Curly, woolly (cords when long)", "coat_colors": ["black", "brown", "beige", "white", "bicolor"], "shedding": "low", "temperament": ["diligent", "affectionate", "loyal", "athletic", "intelligent"], "overview": "A versatile Spanish breed used for herding and water retrieval, the Spanish Water Dog has a distinctive curly coat and loyal personality.", "best_for": ["Active families", "Water enthusiasts", "Allergy sufferers"], "not_for": ["Those wanting a fluffy-looking dog", "Sedentary owners"]},
    
    {"id": "lagotto-romagnolo", "name": "Lagotto Romagnolo", "group": "sporting", "origin": "Italy", "lifespan": "15-17 years", "size": {"height_cm": "41-48", "weight_kg": "11-16", "category": "medium"}, "ratings": {"size": 3, "energy": 4, "grooming": 4, "sociability": 4, "trainability": 4, "barking": 3, "kid_friendly": 5, "apartment_ok": 4}, "coat_type": "Dense, curly, woolly", "coat_colors": ["off-white", "brown", "orange", "roan"], "shedding": "low", "temperament": ["keen", "loving", "undemanding", "loyal", "active"], "overview": "Italy's truffle-hunting dog, the Lagotto has a distinctive curly coat and keen nose. They're loving, active companions with a hypoallergenic coat.", "best_for": ["Families", "Allergy sufferers", "Active owners"], "not_for": ["Those avoiding grooming", "Very sedentary owners"]},
    
    {"id": "dutch-shepherd", "name": "Dutch Shepherd", "group": "herding", "origin": "Netherlands", "lifespan": "11-14 years", "size": {"height_cm": "55-62", "weight_kg": "23-32", "category": "large"}, "ratings": {"size": 4, "energy": 5, "grooming": 2, "sociability": 3, "trainability": 5, "barking": 3, "kid_friendly": 4, "apartment_ok": 2}, "coat_type": "Short, long, or wire", "coat_colors": ["brindle"], "shedding": "moderate", "temperament": ["reliable", "alert", "obedient", "affectionate", "athletic"], "overview": "A versatile Dutch herding breed distinguished by their brindle coat. Dutch Shepherds are reliable, athletic dogs who excel at many tasks.", "best_for": ["Experienced owners", "Dog sports enthusiasts", "Active families"], "not_for": ["First-time owners", "Sedentary owners"]},
    
    {"id": "white-swiss-shepherd", "name": "White Swiss Shepherd", "group": "herding", "origin": "Switzerland", "lifespan": "12-14 years", "size": {"height_cm": "55-66", "weight_kg": "25-40", "category": "large"}, "ratings": {"size": 4, "energy": 4, "grooming": 3, "sociability": 4, "trainability": 5, "barking": 3, "kid_friendly": 5, "apartment_ok": 2}, "coat_type": "Medium or long double coat", "coat_colors": ["white"], "shedding": "high", "temperament": ["gentle", "intelligent", "loyal", "eager", "friendly"], "overview": "A white variant developed from German Shepherds, the White Swiss Shepherd is gentle, intelligent, and eager to please. They're wonderful family dogs.", "best_for": ["Families", "Active owners", "Those wanting a loyal companion"], "not_for": ["Those who dislike shedding", "Very hot climates"]},
    
    {"id": "chinook", "name": "Chinook", "group": "working", "origin": "United States", "lifespan": "12-15 years", "size": {"height_cm": "53-69", "weight_kg": "25-41", "category": "large"}, "ratings": {"size": 4, "energy": 4, "grooming": 2, "sociability": 5, "trainability": 4, "barking": 2, "kid_friendly": 5, "apartment_ok": 2}, "coat_type": "Double coat, medium-length", "coat_colors": ["tawny", "honey"], "shedding": "moderate", "temperament": ["smart", "patient", "devoted", "friendly", "calm"], "overview": "New Hampshire's state dog, the Chinook is a rare American sled dog. They're calm, devoted family dogs with a gentle nature.", "best_for": ["Families with children", "Those wanting a rare breed", "Active owners"], "not_for": ["Very hot climates", "Those wanting a guard dog"]},
    
    {"id": "eurasier", "name": "Eurasier", "group": "non-sporting", "origin": "Germany", "lifespan": "12-16 years", "size": {"height_cm": "48-60", "weight_kg": "18-32", "category": "medium"}, "ratings": {"size": 3, "energy": 3, "grooming": 3, "sociability": 3, "trainability": 4, "barking": 2, "kid_friendly": 5, "apartment_ok": 3}, "coat_type": "Medium-length double coat", "coat_colors": ["all colors except white and liver"], "shedding": "moderate", "temperament": ["confident", "calm", "intelligent", "even-tempered", "reserved"], "overview": "A modern German breed mixing Chow Chow, Wolfspitz, and Samoyed. Eurasiers are calm, confident dogs who are devoted to family but reserved with strangers.", "best_for": ["Families", "Those wanting a calm breed", "Patient owners"], "not_for": ["Those wanting an outgoing dog", "Those away from home often"]},
    
    {"id": "hovawart", "name": "Hovawart", "group": "working", "origin": "Germany", "lifespan": "10-14 years", "size": {"height_cm": "58-70", "weight_kg": "25-45", "category": "large"}, "ratings": {"size": 4, "energy": 4, "grooming": 3, "sociability": 3, "trainability": 4, "barking": 3, "kid_friendly": 4, "apartment_ok": 2}, "coat_type": "Long, slightly wavy", "coat_colors": ["black and gold", "black", "blond"], "shedding": "moderate", "temperament": ["alert", "faithful", "familial", "reserved", "even-tempered"], "overview": "An ancient German guardian breed, Hovawarts are faithful, even-tempered dogs. They're devoted to family and naturally protective.", "best_for": ["Experienced owners", "Families wanting a guardian", "Active homes"], "not_for": ["First-time owners", "Apartments"]},
    
    {"id": "landseer", "name": "Landseer", "group": "working", "origin": "Germany/Canada", "lifespan": "8-10 years", "size": {"height_cm": "67-80", "weight_kg": "50-68", "category": "giant"}, "ratings": {"size": 5, "energy": 3, "grooming": 4, "sociability": 5, "trainability": 3, "barking": 2, "kid_friendly": 5, "apartment_ok": 1}, "coat_type": "Long, flat, dense", "coat_colors": ["white with black patches"], "shedding": "high", "temperament": ["gentle", "patient", "calm", "noble", "generous"], "overview": "Related to the Newfoundland, the Landseer is a gentle giant with a distinctive black and white coat. They're patient, noble dogs who love children.", "best_for": ["Families with space", "Those wanting a gentle giant", "Water enthusiasts"], "not_for": ["Apartment dwellers", "Those who dislike drool/shedding"]},
    
    {"id": "greater-swiss-mountain-dog", "name": "Greater Swiss Mountain Dog", "group": "working", "origin": "Switzerland", "lifespan": "8-11 years", "size": {"height_cm": "60-72", "weight_kg": "45-64", "category": "giant"}, "ratings": {"size": 5, "energy": 3, "grooming": 2, "sociability": 4, "trainability": 3, "barking": 3, "kid_friendly": 5, "apartment_ok": 2}, "coat_type": "Short, dense double coat", "coat_colors": ["tricolor (black, rust, white)"], "shedding": "moderate", "temperament": ["faithful", "dependable", "alert", "gentle", "family-oriented"], "overview": "The largest Swiss Mountain Dog, Swissies are faithful, dependable companions. They're gentle giants who excel as family dogs.", "best_for": ["Families with space", "Those wanting a guardian", "Active homes"], "not_for": ["Apartment dwellers", "Hot climates"]},
    
    {"id": "appenzeller-sennenhund", "name": "Appenzeller Sennenhund", "group": "herding", "origin": "Switzerland", "lifespan": "12-15 years", "size": {"height_cm": "47-58", "weight_kg": "22-32", "category": "medium"}, "ratings": {"size": 3, "energy": 5, "grooming": 2, "sociability": 3, "trainability": 4, "barking": 4, "kid_friendly": 4, "apartment_ok": 2}, "coat_type": "Double coat, short", "coat_colors": ["tricolor (black, tan, white)"], "shedding": "moderate", "temperament": ["reliable", "fearless", "energetic", "lively", "self-assured"], "overview": "The most energetic of the Swiss Mountain Dogs, Appenzellers are reliable, fearless herding dogs. They're lively, active companions.", "best_for": ["Very active owners", "Farms", "Dog sports enthusiasts"], "not_for": ["Sedentary owners", "Apartment dwellers"]},
]

def generate_breed_json(breed_data):
    return {
        "id": breed_data["id"],
        "name": breed_data["name"],
        "aliases": [],
        "group": breed_data["group"],
        "origin": breed_data["origin"],
        "lifespan": breed_data["lifespan"],
        "size": breed_data["size"],
        "ratings": breed_data["ratings"],
        "characteristics": {
            "coat_type": breed_data["coat_type"],
            "coat_colors": breed_data["coat_colors"],
            "shedding": breed_data["shedding"],
            "hypoallergenic": breed_data["shedding"] == "low"
        },
        "temperament": breed_data["temperament"],
        "description": {
            "overview": breed_data["overview"],
            "history": f"The {breed_data['name']} originated in {breed_data['origin']}.",
            "temperament": f"Known for being {', '.join(breed_data['temperament'][:3])}.",
            "health": "Generally healthy with breed-typical considerations.",
            "grooming": f"Requires regular grooming appropriate for their {breed_data['coat_type'].lower()} coat.",
            "exercise": "Exercise needs match their energy level."
        },
        "verdict": {
            "best_for": breed_data["best_for"],
            "not_for": breed_data["not_for"],
            "summary": breed_data["overview"]
        }
    }

data_dir = os.path.expanduser("~/clawd/dog-breed-guide/data/breeds")
for breed in MISSING_BREEDS:
    json_path = os.path.join(data_dir, f"{breed['id']}.json")
    with open(json_path, "w") as f:
        json.dump(generate_breed_json(breed), f, indent=2)
    print(f"✓ {breed['name']}")

print(f"\nGenerated {len(MISSING_BREEDS)} missing breed JSON files!")
