#!/usr/bin/env python3
"""Generate breed JSON and HTML for breeds 151-220"""

import json
import os

BREEDS = [
    # Sporting/Gun Dogs (151-165)
    {"id": "flat-coated-retriever", "name": "Flat-Coated Retriever", "group": "sporting", "origin": "England", "lifespan": "8-10 years", "size": {"height_cm": "56-62", "weight_kg": "25-36", "category": "large"}, "ratings": {"size": 4, "energy": 5, "grooming": 3, "sociability": 5, "trainability": 4, "barking": 3, "kid_friendly": 5, "apartment_ok": 2}, "coat_type": "Flat, dense, medium-length", "coat_colors": ["black", "liver"], "shedding": "moderate", "temperament": ["cheerful", "optimistic", "friendly", "confident", "devoted"], "overview": "The Flat-Coated Retriever is the Peter Pan of retrievers—they never seem to grow up. These cheerful, optimistic dogs maintain their puppy-like enthusiasm well into adulthood.", "best_for": ["Active families", "Hunters", "Those wanting a happy companion"], "not_for": ["Those wanting a calm dog", "Small living spaces"]},
    
    {"id": "curly-coated-retriever", "name": "Curly-Coated Retriever", "group": "sporting", "origin": "England", "lifespan": "10-12 years", "size": {"height_cm": "58-69", "weight_kg": "25-41", "category": "large"}, "ratings": {"size": 4, "energy": 4, "grooming": 2, "sociability": 4, "trainability": 4, "barking": 2, "kid_friendly": 4, "apartment_ok": 2}, "coat_type": "Tight, crisp curls", "coat_colors": ["black", "liver"], "shedding": "low", "temperament": ["intelligent", "independent", "confident", "gentle", "loyal"], "overview": "The Curly-Coated Retriever is the most elegant and graceful of all retrievers. Their distinctive curly coat and proud bearing set them apart.", "best_for": ["Experienced owners", "Active families", "Hunters"], "not_for": ["First-time owners", "Those wanting an eager-to-please dog"]},
    
    {"id": "chesapeake-bay-retriever", "name": "Chesapeake Bay Retriever", "group": "sporting", "origin": "United States", "lifespan": "10-13 years", "size": {"height_cm": "53-66", "weight_kg": "25-36", "category": "large"}, "ratings": {"size": 4, "energy": 5, "grooming": 2, "sociability": 3, "trainability": 4, "barking": 3, "kid_friendly": 4, "apartment_ok": 2}, "coat_type": "Wavy, oily double coat", "coat_colors": ["brown", "sedge", "deadgrass"], "shedding": "moderate", "temperament": ["affectionate", "bright", "sensitive", "protective", "athletic"], "overview": "The Chesapeake Bay Retriever is the toughest of all retrievers, bred to retrieve ducks in the icy waters of Chesapeake Bay. They're loyal and protective.", "best_for": ["Hunters", "Active families", "Those wanting a protective dog"], "not_for": ["First-time owners", "Multi-pet homes"]},
    
    {"id": "nova-scotia-duck-tolling-retriever", "name": "Nova Scotia Duck Tolling Retriever", "group": "sporting", "origin": "Canada", "lifespan": "12-14 years", "size": {"height_cm": "43-53", "weight_kg": "17-23", "category": "medium"}, "ratings": {"size": 3, "energy": 5, "grooming": 3, "sociability": 4, "trainability": 5, "barking": 3, "kid_friendly": 5, "apartment_ok": 3}, "coat_type": "Medium-length double coat", "coat_colors": ["red", "orange"], "shedding": "moderate", "temperament": ["intelligent", "alert", "affectionate", "patient", "playful"], "overview": "The 'Toller' is the smallest retriever but packed with energy and intelligence. They were bred to lure and retrieve waterfowl with their playful antics.", "best_for": ["Active families", "Dog sports enthusiasts", "Hunters"], "not_for": ["Sedentary owners", "Those wanting a quiet dog"]},
    
    {"id": "irish-water-spaniel", "name": "Irish Water Spaniel", "group": "sporting", "origin": "Ireland", "lifespan": "12-13 years", "size": {"height_cm": "51-59", "weight_kg": "20-30", "category": "medium"}, "ratings": {"size": 3, "energy": 4, "grooming": 4, "sociability": 3, "trainability": 4, "barking": 3, "kid_friendly": 4, "apartment_ok": 2}, "coat_type": "Dense, tight curls", "coat_colors": ["liver"], "shedding": "low", "temperament": ["playful", "hardworking", "alert", "inquisitive", "brave"], "overview": "The tallest spaniel, the Irish Water Spaniel is known for their distinctive rat tail and curly liver-colored coat. They're natural clowns with a love for water.", "best_for": ["Active owners", "Those wanting a unique breed", "Water enthusiasts"], "not_for": ["Those wanting low grooming", "Novice owners"]},
    
    {"id": "american-water-spaniel", "name": "American Water Spaniel", "group": "sporting", "origin": "United States", "lifespan": "10-14 years", "size": {"height_cm": "38-46", "weight_kg": "11-20", "category": "medium"}, "ratings": {"size": 3, "energy": 4, "grooming": 3, "sociability": 4, "trainability": 4, "barking": 3, "kid_friendly": 4, "apartment_ok": 3}, "coat_type": "Wavy or curly double coat", "coat_colors": ["liver", "brown", "chocolate"], "shedding": "moderate", "temperament": ["happy", "eager", "charming", "versatile", "energetic"], "overview": "Wisconsin's state dog, the American Water Spaniel is a versatile hunter developed in the Great Lakes region. They're excellent swimmers and enthusiastic workers.", "best_for": ["Hunters", "Active families", "Those wanting a versatile dog"], "not_for": ["Apartment dwellers", "Inactive owners"]},
    
    {"id": "boykin-spaniel", "name": "Boykin Spaniel", "group": "sporting", "origin": "United States", "lifespan": "10-15 years", "size": {"height_cm": "36-46", "weight_kg": "11-18", "category": "medium"}, "ratings": {"size": 3, "energy": 4, "grooming": 3, "sociability": 5, "trainability": 5, "barking": 3, "kid_friendly": 5, "apartment_ok": 3}, "coat_type": "Wavy or curly, medium-length", "coat_colors": ["liver", "brown"], "shedding": "moderate", "temperament": ["friendly", "eager", "lovable", "versatile", "trainable"], "overview": "South Carolina's state dog, the Boykin Spaniel is a friendly, energetic companion bred for hunting wild turkeys and waterfowl from boats.", "best_for": ["Families", "Hunters", "Active households"], "not_for": ["Those wanting a guard dog", "Very small spaces"]},
    
    {"id": "clumber-spaniel", "name": "Clumber Spaniel", "group": "sporting", "origin": "England", "lifespan": "10-12 years", "size": {"height_cm": "43-51", "weight_kg": "25-39", "category": "large"}, "ratings": {"size": 4, "energy": 2, "grooming": 3, "sociability": 4, "trainability": 3, "barking": 2, "kid_friendly": 5, "apartment_ok": 3}, "coat_type": "Dense, straight, flat", "coat_colors": ["white with lemon", "white with orange"], "shedding": "high", "temperament": ["gentle", "loyal", "affectionate", "dignified", "mellow"], "overview": "The heaviest spaniel, Clumbers are dignified, mellow dogs who make excellent family companions. They're less energetic than other spaniels but still enjoy hunting.", "best_for": ["Families wanting a calm spaniel", "Seniors", "Those who appreciate a dignified dog"], "not_for": ["Neat freaks (they drool)", "Those wanting high energy"]},
    
    {"id": "field-spaniel", "name": "Field Spaniel", "group": "sporting", "origin": "England", "lifespan": "10-12 years", "size": {"height_cm": "43-46", "weight_kg": "16-23", "category": "medium"}, "ratings": {"size": 3, "energy": 4, "grooming": 3, "sociability": 4, "trainability": 4, "barking": 2, "kid_friendly": 5, "apartment_ok": 3}, "coat_type": "Single coat, silky, moderately long", "coat_colors": ["black", "liver", "roan"], "shedding": "moderate", "temperament": ["sensitive", "docile", "affectionate", "fun-loving", "independent"], "overview": "A rare breed, the Field Spaniel is a sensitive, sweet-natured dog who bonds closely with their family. They're calmer than Cockers but still playful.", "best_for": ["Families", "Those wanting a rare breed", "Gentle handlers"], "not_for": ["Harsh trainers", "Those away often"]},
    
    {"id": "sussex-spaniel", "name": "Sussex Spaniel", "group": "sporting", "origin": "England", "lifespan": "13-15 years", "size": {"height_cm": "33-38", "weight_kg": "16-20", "category": "medium"}, "ratings": {"size": 3, "energy": 3, "grooming": 3, "sociability": 4, "trainability": 3, "barking": 4, "kid_friendly": 4, "apartment_ok": 3}, "coat_type": "Flat or wavy, abundant", "coat_colors": ["golden liver"], "shedding": "moderate", "temperament": ["friendly", "cheerful", "calm", "steady", "vocal"], "overview": "One of the rarest spaniel breeds, the Sussex has a unique golden liver coat and a surprisingly deep bark. They're slower-paced but determined hunters.", "best_for": ["Those wanting a rare breed", "Calm households", "Spaniel enthusiasts"], "not_for": ["Those wanting a quiet dog", "High-energy activities"]},
    
    {"id": "welsh-springer-spaniel", "name": "Welsh Springer Spaniel", "group": "sporting", "origin": "Wales", "lifespan": "12-15 years", "size": {"height_cm": "43-48", "weight_kg": "16-20", "category": "medium"}, "ratings": {"size": 3, "energy": 4, "grooming": 3, "sociability": 4, "trainability": 4, "barking": 3, "kid_friendly": 5, "apartment_ok": 3}, "coat_type": "Straight, flat, silky", "coat_colors": ["red and white"], "shedding": "moderate", "temperament": ["happy", "loyal", "active", "reserved", "affectionate"], "overview": "Often confused with English Springers, the Welsh Springer is slightly smaller with a distinctive red and white coat. They're devoted family dogs.", "best_for": ["Active families", "Hunters", "Those wanting a loyal companion"], "not_for": ["Those wanting an outgoing dog with strangers", "Very small spaces"]},
    
    {"id": "gordon-setter", "name": "Gordon Setter", "group": "sporting", "origin": "Scotland", "lifespan": "12-13 years", "size": {"height_cm": "58-69", "weight_kg": "20-36", "category": "large"}, "ratings": {"size": 4, "energy": 4, "grooming": 3, "sociability": 3, "trainability": 4, "barking": 3, "kid_friendly": 4, "apartment_ok": 2}, "coat_type": "Soft, shiny, slightly wavy", "coat_colors": ["black and tan"], "shedding": "moderate", "temperament": ["alert", "confident", "fearless", "loyal", "affectionate"], "overview": "The largest and most substantial of all setters, Gordons are loyal, devoted dogs with striking black and tan coats. They're excellent hunters and family companions.", "best_for": ["Active families", "Hunters", "Those wanting a loyal companion"], "not_for": ["Apartment dwellers", "First-time owners"]},
    
    {"id": "irish-red-and-white-setter", "name": "Irish Red and White Setter", "group": "sporting", "origin": "Ireland", "lifespan": "11-15 years", "size": {"height_cm": "57-66", "weight_kg": "25-34", "category": "large"}, "ratings": {"size": 4, "energy": 5, "grooming": 3, "sociability": 5, "trainability": 4, "barking": 3, "kid_friendly": 5, "apartment_ok": 2}, "coat_type": "Fine, silky with feathering", "coat_colors": ["white with red patches"], "shedding": "moderate", "temperament": ["friendly", "spirited", "determined", "loyal", "playful"], "overview": "The original Irish setter, predating the all-red variety. They're athletic, friendly dogs with a distinctive parti-color coat of white with red patches.", "best_for": ["Active families", "Hunters", "Those wanting a friendly breed"], "not_for": ["Sedentary owners", "Small living spaces"]},
    
    {"id": "spinone-italiano", "name": "Spinone Italiano", "group": "sporting", "origin": "Italy", "lifespan": "10-12 years", "size": {"height_cm": "58-70", "weight_kg": "29-39", "category": "large"}, "ratings": {"size": 4, "energy": 3, "grooming": 2, "sociability": 5, "trainability": 3, "barking": 2, "kid_friendly": 5, "apartment_ok": 2}, "coat_type": "Wiry, dense, coarse", "coat_colors": ["white", "white and orange", "brown roan"], "shedding": "low", "temperament": ["docile", "friendly", "patient", "loyal", "gentle"], "overview": "An ancient Italian breed, the Spinone is one of the most gentle and patient pointing breeds. Their wiry coat and soulful expression are distinctive.", "best_for": ["Families with children", "Those wanting a gentle giant", "Patient trainers"], "not_for": ["Those wanting a fast-paced dog", "Neat freaks (they drool)"]},
    
    {"id": "wirehaired-pointing-griffon", "name": "Wirehaired Pointing Griffon", "group": "sporting", "origin": "Netherlands/France", "lifespan": "12-15 years", "size": {"height_cm": "51-61", "weight_kg": "23-27", "category": "medium"}, "ratings": {"size": 3, "energy": 4, "grooming": 3, "sociability": 4, "trainability": 4, "barking": 3, "kid_friendly": 5, "apartment_ok": 2}, "coat_type": "Harsh, wiry double coat", "coat_colors": ["steel gray with brown", "chestnut", "roan"], "shedding": "low", "temperament": ["friendly", "devoted", "trainable", "proud", "eager"], "overview": "Known as the 'supreme gundog,' the Wirehaired Pointing Griffon excels at pointing and retrieving. Their rough coat protects them in harsh terrain.", "best_for": ["Hunters", "Active families", "Those wanting a versatile dog"], "not_for": ["Apartment dwellers", "Inactive owners"]},
    
    # Pointers & Continental (166-175)
    {"id": "german-wirehaired-pointer", "name": "German Wirehaired Pointer", "group": "sporting", "origin": "Germany", "lifespan": "14-16 years", "size": {"height_cm": "57-68", "weight_kg": "27-32", "category": "large"}, "ratings": {"size": 4, "energy": 5, "grooming": 2, "sociability": 3, "trainability": 4, "barking": 3, "kid_friendly": 4, "apartment_ok": 1}, "coat_type": "Wiry, weather-resistant", "coat_colors": ["liver and white", "liver roan", "solid liver"], "shedding": "low", "temperament": ["affectionate", "eager", "enthusiastic", "determined", "loyal"], "overview": "A versatile hunter's companion, the German Wirehaired Pointer can point, retrieve, and track in any terrain. Their distinctive beard and eyebrows add character.", "best_for": ["Hunters", "Very active owners", "Rural living"], "not_for": ["Apartment dwellers", "Inactive families"]},
    
    {"id": "english-pointer", "name": "English Pointer", "group": "sporting", "origin": "England", "lifespan": "12-17 years", "size": {"height_cm": "58-71", "weight_kg": "20-34", "category": "large"}, "ratings": {"size": 4, "energy": 5, "grooming": 1, "sociability": 4, "trainability": 4, "barking": 3, "kid_friendly": 5, "apartment_ok": 1}, "coat_type": "Short, dense, smooth", "coat_colors": ["lemon and white", "orange and white", "liver and white", "black and white"], "shedding": "moderate", "temperament": ["loyal", "hardworking", "even-tempered", "kind", "athletic"], "overview": "The quintessential bird dog, the English Pointer is bred for speed and endurance in the field. At home, they're calm, dignified companions.", "best_for": ["Hunters", "Active families", "Those with large yards"], "not_for": ["Apartment dwellers", "Sedentary owners"]},
    
    {"id": "wirehaired-vizsla", "name": "Wirehaired Vizsla", "group": "sporting", "origin": "Hungary", "lifespan": "12-14 years", "size": {"height_cm": "54-64", "weight_kg": "20-30", "category": "medium"}, "ratings": {"size": 3, "energy": 5, "grooming": 2, "sociability": 4, "trainability": 5, "barking": 3, "kid_friendly": 5, "apartment_ok": 2}, "coat_type": "Dense, wiry", "coat_colors": ["golden rust"], "shedding": "low", "temperament": ["gentle", "loyal", "trainable", "affectionate", "sensitive"], "overview": "A close cousin to the smooth Vizsla but with a protective wiry coat. They're equally affectionate and athletic, with better protection from cold weather.", "best_for": ["Active families", "Hunters", "Those wanting a loyal companion"], "not_for": ["Those away from home often", "Sedentary owners"]},
    
    {"id": "bracco-italiano", "name": "Bracco Italiano", "group": "sporting", "origin": "Italy", "lifespan": "10-14 years", "size": {"height_cm": "55-67", "weight_kg": "25-40", "category": "large"}, "ratings": {"size": 4, "energy": 4, "grooming": 1, "sociability": 4, "trainability": 4, "barking": 2, "kid_friendly": 5, "apartment_ok": 2}, "coat_type": "Short, dense, glossy", "coat_colors": ["white", "white and orange", "white and chestnut"], "shedding": "moderate", "temperament": ["affectionate", "intelligent", "docile", "loyal", "playful"], "overview": "One of the oldest pointing breeds, the Bracco Italiano is an elegant, athletic dog with a gentle disposition. They're affectionate family members and capable hunters.", "best_for": ["Families", "Hunters", "Those wanting a gentle breed"], "not_for": ["Very small spaces", "Those wanting a guard dog"]},
    
    {"id": "barbet", "name": "Barbet", "group": "sporting", "origin": "France", "lifespan": "12-14 years", "size": {"height_cm": "53-65", "weight_kg": "17-28", "category": "medium"}, "ratings": {"size": 3, "energy": 4, "grooming": 4, "sociability": 5, "trainability": 4, "barking": 2, "kid_friendly": 5, "apartment_ok": 3}, "coat_type": "Long, woolly, curly", "coat_colors": ["black", "brown", "fawn", "gray", "white"], "shedding": "low", "temperament": ["friendly", "joyful", "obedient", "intelligent", "social"], "overview": "The Barbet is an ancient French water dog with a distinctive curly coat. They're cheerful, social dogs who love water and make excellent family companions.", "best_for": ["Families", "Allergy sufferers", "Water enthusiasts"], "not_for": ["Those wanting low grooming", "Hot climates"]},
    
    {"id": "nederlandse-kooikerhondje", "name": "Nederlandse Kooikerhondje", "group": "sporting", "origin": "Netherlands", "lifespan": "12-15 years", "size": {"height_cm": "36-41", "weight_kg": "9-11", "category": "small"}, "ratings": {"size": 2, "energy": 4, "grooming": 3, "sociability": 3, "trainability": 4, "barking": 3, "kid_friendly": 4, "apartment_ok": 4}, "coat_type": "Medium-length, slightly wavy", "coat_colors": ["orange-red and white"], "shedding": "moderate", "temperament": ["cheerful", "alert", "friendly", "agile", "intelligent"], "overview": "This charming Dutch breed was used to lure ducks into traps. Their flowing coat and happy demeanor make them attractive companions and agility dogs.", "best_for": ["Active owners", "Dog sports enthusiasts", "Families"], "not_for": ["Very busy households", "Those wanting an outgoing dog"]},
    
    {"id": "small-munsterlander", "name": "Small Münsterländer", "group": "sporting", "origin": "Germany", "lifespan": "12-14 years", "size": {"height_cm": "50-56", "weight_kg": "18-27", "category": "medium"}, "ratings": {"size": 3, "energy": 5, "grooming": 3, "sociability": 4, "trainability": 5, "barking": 3, "kid_friendly": 5, "apartment_ok": 2}, "coat_type": "Medium-length, dense, sleek", "coat_colors": ["brown and white", "brown roan"], "shedding": "moderate", "temperament": ["intelligent", "trainable", "versatile", "affectionate", "eager"], "overview": "Despite the name, the Small Münsterländer is a medium-sized versatile hunting dog. They're highly trainable and make excellent family companions.", "best_for": ["Hunters", "Active families", "Dog sports enthusiasts"], "not_for": ["Sedentary owners", "Apartment dwellers"]},
    
    {"id": "large-munsterlander", "name": "Large Münsterländer", "group": "sporting", "origin": "Germany", "lifespan": "11-13 years", "size": {"height_cm": "58-65", "weight_kg": "27-32", "category": "large"}, "ratings": {"size": 4, "energy": 5, "grooming": 3, "sociability": 4, "trainability": 5, "barking": 3, "kid_friendly": 5, "apartment_ok": 2}, "coat_type": "Long, dense, with feathering", "coat_colors": ["black and white"], "shedding": "moderate", "temperament": ["intelligent", "loyal", "cheerful", "trainable", "versatile"], "overview": "A striking black and white setter-type, the Large Münsterländer is a versatile hunting dog that excels at pointing and retrieving. They're devoted family dogs.", "best_for": ["Hunters", "Active families", "Those wanting a trainable breed"], "not_for": ["Sedentary owners", "Small living spaces"]},
    
    {"id": "pudelpointer", "name": "Pudelpointer", "group": "sporting", "origin": "Germany", "lifespan": "11-14 years", "size": {"height_cm": "55-68", "weight_kg": "20-30", "category": "large"}, "ratings": {"size": 4, "energy": 5, "grooming": 2, "sociability": 4, "trainability": 5, "barking": 2, "kid_friendly": 4, "apartment_ok": 1}, "coat_type": "Harsh, wiry, medium-length", "coat_colors": ["liver", "brown", "black"], "shedding": "low", "temperament": ["calm", "self-controlled", "versatile", "intelligent", "willing"], "overview": "A Poodle-Pointer cross developed for versatile hunting. The Pudelpointer combines the Poodle's intelligence and love of water with the Pointer's hunting instincts.", "best_for": ["Hunters", "Active owners", "Those wanting a versatile dog"], "not_for": ["Apartment dwellers", "Inactive families"]},
    
    {"id": "drentse-patrijshond", "name": "Drentse Patrijshond", "group": "sporting", "origin": "Netherlands", "lifespan": "11-14 years", "size": {"height_cm": "55-63", "weight_kg": "21-23", "category": "medium"}, "ratings": {"size": 3, "energy": 4, "grooming": 2, "sociability": 4, "trainability": 4, "barking": 2, "kid_friendly": 5, "apartment_ok": 2}, "coat_type": "Medium-length, dense, slightly wavy", "coat_colors": ["white with brown", "white with orange"], "shedding": "moderate", "temperament": ["loyal", "intelligent", "sensitive", "adaptable", "devoted"], "overview": "An old Dutch breed known for their versatility and gentle nature. They're excellent family dogs who also perform well in the field.", "best_for": ["Families", "Hunters", "Those wanting a loyal companion"], "not_for": ["Harsh trainers", "Very small spaces"]},
    
    # Toys & Companions (176-190)
    {"id": "papillon", "name": "Papillon", "group": "toy", "origin": "France/Belgium", "lifespan": "14-16 years", "size": {"height_cm": "20-28", "weight_kg": "3-5", "category": "tiny"}, "ratings": {"size": 1, "energy": 4, "grooming": 3, "sociability": 4, "trainability": 5, "barking": 4, "kid_friendly": 3, "apartment_ok": 5}, "coat_type": "Long, fine, silky, single coat", "coat_colors": ["white with patches of any color"], "shedding": "moderate", "temperament": ["alert", "friendly", "happy", "intelligent", "athletic"], "overview": "Named for their butterfly-like ears (papillon means butterfly in French), these tiny dogs are surprisingly athletic and intelligent. They excel in agility and obedience.", "best_for": ["Apartment dwellers", "Seniors", "Dog sports enthusiasts"], "not_for": ["Homes with toddlers", "Those wanting a lap dog only"]},
    
    {"id": "japanese-chin", "name": "Japanese Chin", "group": "toy", "origin": "Japan/China", "lifespan": "10-12 years", "size": {"height_cm": "20-27", "weight_kg": "2-5", "category": "tiny"}, "ratings": {"size": 1, "energy": 2, "grooming": 3, "sociability": 3, "trainability": 3, "barking": 2, "kid_friendly": 3, "apartment_ok": 5}, "coat_type": "Long, silky, single coat", "coat_colors": ["black and white", "red and white", "lemon and white"], "shedding": "moderate", "temperament": ["charming", "noble", "loving", "cat-like", "loyal"], "overview": "The Japanese Chin is often described as cat-like in their fastidious nature and preference for high perches. They're elegant, quiet companions fit for royalty.", "best_for": ["Apartment dwellers", "Seniors", "Those wanting a quiet toy breed"], "not_for": ["Active families", "Homes with rough children"]},
    
    {"id": "brussels-griffon", "name": "Brussels Griffon", "group": "toy", "origin": "Belgium", "lifespan": "12-15 years", "size": {"height_cm": "18-20", "weight_kg": "3.5-6", "category": "tiny"}, "ratings": {"size": 1, "energy": 3, "grooming": 3, "sociability": 4, "trainability": 3, "barking": 3, "kid_friendly": 3, "apartment_ok": 5}, "coat_type": "Rough or smooth coat", "coat_colors": ["red", "black and tan", "black", "belge"], "shedding": "low", "temperament": ["alert", "curious", "loyal", "sensitive", "comical"], "overview": "With their almost human-like expressions and big personality, Brussels Griffons are charming companions. They bond closely with their owners and can be quite comical.", "best_for": ["Singles", "Seniors", "Those wanting a devoted companion"], "not_for": ["Homes with young children", "Those away often"]},
    
    {"id": "affenpinscher", "name": "Affenpinscher", "group": "toy", "origin": "Germany", "lifespan": "12-15 years", "size": {"height_cm": "23-30", "weight_kg": "3-6", "category": "tiny"}, "ratings": {"size": 1, "energy": 3, "grooming": 3, "sociability": 3, "trainability": 3, "barking": 4, "kid_friendly": 2, "apartment_ok": 5}, "coat_type": "Rough, harsh, wiry", "coat_colors": ["black", "gray", "silver", "red", "beige"], "shedding": "low", "temperament": ["confident", "fearless", "funny", "stubborn", "curious"], "overview": "The 'monkey dog' (Affen means monkey in German) is a fearless little terrier with a big personality. They're curious, playful, and always entertaining.", "best_for": ["Adults only", "Those wanting a character", "Apartment dwellers"], "not_for": ["Families with young children", "First-time owners"]},
    
    {"id": "english-toy-spaniel", "name": "English Toy Spaniel", "group": "toy", "origin": "England", "lifespan": "10-12 years", "size": {"height_cm": "25-27", "weight_kg": "3.5-6.5", "category": "small"}, "ratings": {"size": 2, "energy": 2, "grooming": 3, "sociability": 4, "trainability": 3, "barking": 2, "kid_friendly": 4, "apartment_ok": 5}, "coat_type": "Long, silky, wavy", "coat_colors": ["blenheim", "prince charles", "king charles", "ruby"], "shedding": "moderate", "temperament": ["gentle", "happy", "playful", "loving", "quiet"], "overview": "Not to be confused with the Cavalier, the English Toy Spaniel (King Charles Spaniel in the UK) is smaller with a domed head. They're gentle, devoted lapdogs.", "best_for": ["Apartment dwellers", "Seniors", "Those wanting a quiet companion"], "not_for": ["Active families", "Outdoor enthusiasts"]},
    
    {"id": "silky-terrier", "name": "Silky Terrier", "group": "toy", "origin": "Australia", "lifespan": "13-15 years", "size": {"height_cm": "23-26", "weight_kg": "4-5", "category": "tiny"}, "ratings": {"size": 1, "energy": 4, "grooming": 4, "sociability": 3, "trainability": 4, "barking": 4, "kid_friendly": 3, "apartment_ok": 5}, "coat_type": "Long, silky, straight", "coat_colors": ["blue and tan"], "shedding": "low", "temperament": ["friendly", "alert", "spirited", "confident", "feisty"], "overview": "Often confused with Yorkies, Silky Terriers are slightly larger with a more terrier-like personality. They're spirited, alert watchdogs in a small package.", "best_for": ["Active singles or couples", "Apartment dwellers", "Those wanting a small watchdog"], "not_for": ["Families with young children", "Those wanting a calm dog"]},
    
    {"id": "bolognese", "name": "Bolognese", "group": "toy", "origin": "Italy", "lifespan": "12-14 years", "size": {"height_cm": "25-30", "weight_kg": "2.5-4", "category": "tiny"}, "ratings": {"size": 1, "energy": 2, "grooming": 4, "sociability": 4, "trainability": 4, "barking": 2, "kid_friendly": 4, "apartment_ok": 5}, "coat_type": "Long, fluffy, cotton-like", "coat_colors": ["white"], "shedding": "low", "temperament": ["devoted", "playful", "calm", "intelligent", "loyal"], "overview": "A true companion breed from Italy, the Bolognese is a calm, devoted little dog with a fluffy white coat. They're less yappy than many toy breeds.", "best_for": ["Seniors", "Apartment dwellers", "Those wanting a devoted companion"], "not_for": ["Those away from home often", "Those wanting a low-grooming dog"]},
    
    {"id": "coton-de-tulear", "name": "Coton de Tulear", "group": "toy", "origin": "Madagascar", "lifespan": "15-19 years", "size": {"height_cm": "23-27", "weight_kg": "4-6", "category": "small"}, "ratings": {"size": 2, "energy": 3, "grooming": 4, "sociability": 5, "trainability": 4, "barking": 3, "kid_friendly": 5, "apartment_ok": 5}, "coat_type": "Long, cotton-like, fluffy", "coat_colors": ["white", "white with gray", "white with tan"], "shedding": "low", "temperament": ["happy", "playful", "affectionate", "intelligent", "charming"], "overview": "Named for their cotton-like coat and the port city of Tulear, these charming dogs are known for their clownish personality and love of their families.", "best_for": ["Families", "Seniors", "Those wanting a happy companion"], "not_for": ["Those wanting low grooming", "Those away often"]},
    
    {"id": "lowchen", "name": "Löwchen", "group": "toy", "origin": "France/Germany", "lifespan": "13-15 years", "size": {"height_cm": "30-36", "weight_kg": "4-8", "category": "small"}, "ratings": {"size": 2, "energy": 3, "grooming": 3, "sociability": 5, "trainability": 4, "barking": 3, "kid_friendly": 5, "apartment_ok": 5}, "coat_type": "Long, wavy, soft", "coat_colors": ["any color"], "shedding": "low", "temperament": ["playful", "friendly", "active", "outgoing", "positive"], "overview": "The 'Little Lion Dog' gets its name from its traditional lion-like trim. Once one of the rarest breeds, they're now prized for their cheerful, friendly nature.", "best_for": ["Families", "Apartment dwellers", "Those wanting a friendly breed"], "not_for": ["Those wanting a guard dog", "Very active outdoor families"]},
    
    {"id": "russian-toy", "name": "Russian Toy", "group": "toy", "origin": "Russia", "lifespan": "12-14 years", "size": {"height_cm": "20-28", "weight_kg": "1.3-3", "category": "tiny"}, "ratings": {"size": 1, "energy": 4, "grooming": 2, "sociability": 4, "trainability": 4, "barking": 4, "kid_friendly": 2, "apartment_ok": 5}, "coat_type": "Smooth or long-haired", "coat_colors": ["black and tan", "brown and tan", "blue and tan", "red"], "shedding": "low", "temperament": ["active", "cheerful", "devoted", "intelligent", "loyal"], "overview": "One of the smallest breeds in the world, Russian Toys are lively, devoted companions. They come in smooth and long-haired varieties.", "best_for": ["Adults", "Apartment dwellers", "Those wanting a tiny companion"], "not_for": ["Families with young children", "Cold climates"]},
    
    {"id": "pekingese", "name": "Pekingese", "group": "toy", "origin": "China", "lifespan": "12-14 years", "size": {"height_cm": "15-23", "weight_kg": "3.5-6", "category": "small"}, "ratings": {"size": 2, "energy": 2, "grooming": 5, "sociability": 3, "trainability": 2, "barking": 3, "kid_friendly": 2, "apartment_ok": 5}, "coat_type": "Long, thick double coat", "coat_colors": ["all colors and patterns"], "shedding": "high", "temperament": ["affectionate", "loyal", "regal", "independent", "stubborn"], "overview": "An ancient breed developed for Chinese royalty, the Pekingese maintains their dignified, independent nature. They're devoted to their owners but can be aloof with strangers.", "best_for": ["Singles", "Seniors", "Those appreciating an independent dog"], "not_for": ["Families with young children", "First-time owners"]},
    
    {"id": "miniature-pinscher", "name": "Miniature Pinscher", "group": "toy", "origin": "Germany", "lifespan": "12-16 years", "size": {"height_cm": "25-30", "weight_kg": "3.5-5", "category": "small"}, "ratings": {"size": 2, "energy": 5, "grooming": 1, "sociability": 3, "trainability": 4, "barking": 4, "kid_friendly": 3, "apartment_ok": 5}, "coat_type": "Short, smooth, hard", "coat_colors": ["red", "black and tan", "chocolate and tan"], "shedding": "low", "temperament": ["fearless", "energetic", "alert", "proud", "spirited"], "overview": "The 'King of Toys' is a small dog with a huge personality. Their hackney-like gait and fearless nature make them entertaining and assertive companions.", "best_for": ["Active owners", "Those wanting a watchdog", "Experienced owners"], "not_for": ["Families with young children", "Those wanting a calm lap dog"]},
    
    {"id": "tibetan-spaniel", "name": "Tibetan Spaniel", "group": "toy", "origin": "Tibet", "lifespan": "12-15 years", "size": {"height_cm": "25-27", "weight_kg": "4-7", "category": "small"}, "ratings": {"size": 2, "energy": 3, "grooming": 3, "sociability": 4, "trainability": 3, "barking": 3, "kid_friendly": 4, "apartment_ok": 5}, "coat_type": "Double coat, silky, moderate length", "coat_colors": ["all colors and mixtures"], "shedding": "moderate", "temperament": ["assertive", "alert", "intelligent", "aloof", "independent"], "overview": "Not actually a spaniel, this ancient breed served as watchdogs in Tibetan monasteries. They're alert, independent dogs who bond closely with their families.", "best_for": ["Apartment dwellers", "Those wanting an alert companion", "Families"], "not_for": ["Those wanting an eager-to-please dog", "Very active owners"]},
    
    {"id": "japanese-spitz", "name": "Japanese Spitz", "group": "non-sporting", "origin": "Japan", "lifespan": "12-14 years", "size": {"height_cm": "30-38", "weight_kg": "5-10", "category": "small"}, "ratings": {"size": 2, "energy": 4, "grooming": 3, "sociability": 4, "trainability": 4, "barking": 4, "kid_friendly": 5, "apartment_ok": 4}, "coat_type": "Long, stand-off double coat", "coat_colors": ["white"], "shedding": "high", "temperament": ["playful", "alert", "intelligent", "loyal", "affectionate"], "overview": "A small, fluffy white dog bred as a companion. Japanese Spitz are cheerful, loyal family dogs with a beautiful coat and expressive dark eyes.", "best_for": ["Families", "Apartment dwellers", "Those wanting a playful companion"], "not_for": ["Those wanting low grooming", "Those away from home often"]},
    
    {"id": "german-spitz", "name": "German Spitz", "group": "non-sporting", "origin": "Germany", "lifespan": "13-15 years", "size": {"height_cm": "24-38", "weight_kg": "5-11", "category": "small"}, "ratings": {"size": 2, "energy": 4, "grooming": 4, "sociability": 4, "trainability": 4, "barking": 5, "kid_friendly": 4, "apartment_ok": 4}, "coat_type": "Long, stand-off double coat", "coat_colors": ["white", "black", "cream", "orange", "brown"], "shedding": "high", "temperament": ["attentive", "lively", "devoted", "trainable", "alert"], "overview": "An ancient breed that comes in multiple sizes (Klein and Mittel), German Spitz are alert watchdogs with a foxlike face and fluffy coat.", "best_for": ["Those wanting a watchdog", "Families", "Apartment dwellers"], "not_for": ["Those wanting a quiet dog", "Those disliking grooming"]},
    
    # Spitz & Rare (191-200)
    {"id": "shar-pei", "name": "Shar-Pei", "group": "non-sporting", "origin": "China", "lifespan": "8-12 years", "size": {"height_cm": "46-51", "weight_kg": "18-25", "category": "medium"}, "ratings": {"size": 3, "energy": 2, "grooming": 2, "sociability": 2, "trainability": 3, "barking": 2, "kid_friendly": 3, "apartment_ok": 4}, "coat_type": "Short, harsh, bristly", "coat_colors": ["fawn", "cream", "red", "black", "blue"], "shedding": "low", "temperament": ["loyal", "independent", "calm", "devoted", "protective"], "overview": "Known for their distinctive wrinkles and blue-black tongue, Shar-Pei are devoted, protective dogs who bond closely with their family but can be aloof with strangers.", "best_for": ["Experienced owners", "Those wanting a protective dog", "Adult households"], "not_for": ["First-time owners", "Multi-dog homes"]},
    
    {"id": "finnish-spitz", "name": "Finnish Spitz", "group": "non-sporting", "origin": "Finland", "lifespan": "13-15 years", "size": {"height_cm": "39-50", "weight_kg": "9-14", "category": "medium"}, "ratings": {"size": 3, "energy": 4, "grooming": 3, "sociability": 4, "trainability": 3, "barking": 5, "kid_friendly": 5, "apartment_ok": 3}, "coat_type": "Dense double coat", "coat_colors": ["golden-red"], "shedding": "high", "temperament": ["friendly", "active", "lively", "independent", "brave"], "overview": "Finland's national dog, the Finnish Spitz is known for their fox-like appearance and unique 'yodel-bark' used to point game birds. They're lively family companions.", "best_for": ["Active families", "Those who don't mind barking", "Rural areas"], "not_for": ["Those wanting a quiet dog", "Apartment dwellers"]},
    
    {"id": "norwegian-buhund", "name": "Norwegian Buhund", "group": "herding", "origin": "Norway", "lifespan": "12-15 years", "size": {"height_cm": "41-47", "weight_kg": "12-18", "category": "medium"}, "ratings": {"size": 3, "energy": 5, "grooming": 3, "sociability": 4, "trainability": 5, "barking": 4, "kid_friendly": 5, "apartment_ok": 3}, "coat_type": "Dense double coat", "coat_colors": ["wheaten", "black"], "shedding": "high", "temperament": ["agile", "alert", "cheerful", "intelligent", "friendly"], "overview": "An ancient Viking dog, the Norwegian Buhund is an all-purpose farm dog known for their cheerful nature and trainability. They excel in herding and agility.", "best_for": ["Active families", "Dog sports enthusiasts", "Farms"], "not_for": ["Apartment dwellers", "Those wanting a quiet dog"]},
    
    {"id": "norwegian-lundehund", "name": "Norwegian Lundehund", "group": "non-sporting", "origin": "Norway", "lifespan": "12-14 years", "size": {"height_cm": "32-38", "weight_kg": "6-7", "category": "small"}, "ratings": {"size": 2, "energy": 4, "grooming": 2, "sociability": 3, "trainability": 3, "barking": 4, "kid_friendly": 4, "apartment_ok": 4}, "coat_type": "Dense double coat", "coat_colors": ["fallow to reddish brown with white"], "shedding": "moderate", "temperament": ["alert", "energetic", "loyal", "protective", "playful"], "overview": "A unique breed with six toes on each foot and extreme flexibility, bred to hunt puffins on Norwegian cliffs. They're rare, primitive dogs with special needs.", "best_for": ["Experienced owners", "Those interested in rare breeds", "Patient trainers"], "not_for": ["First-time owners", "Those wanting easy trainability"]},
    
    {"id": "schipperke", "name": "Schipperke", "group": "non-sporting", "origin": "Belgium", "lifespan": "12-14 years", "size": {"height_cm": "26-33", "weight_kg": "3-9", "category": "small"}, "ratings": {"size": 2, "energy": 5, "grooming": 2, "sociability": 3, "trainability": 4, "barking": 4, "kid_friendly": 4, "apartment_ok": 4}, "coat_type": "Dense double coat with ruff", "coat_colors": ["black"], "shedding": "moderate", "temperament": ["curious", "fearless", "confident", "faithful", "mischievous"], "overview": "The 'Little Black Devil' is a small Belgian breed known for their curious, mischievous nature. They're excellent watchdogs with a distinctive ruff and tailless appearance.", "best_for": ["Active owners", "Those wanting a watchdog", "Experienced small-dog owners"], "not_for": ["Those wanting a calm dog", "Novice owners"]},
    
    {"id": "korean-jindo", "name": "Korean Jindo", "group": "non-sporting", "origin": "South Korea", "lifespan": "12-15 years", "size": {"height_cm": "45-55", "weight_kg": "15-23", "category": "medium"}, "ratings": {"size": 3, "energy": 4, "grooming": 2, "sociability": 2, "trainability": 3, "barking": 3, "kid_friendly": 3, "apartment_ok": 2}, "coat_type": "Dense double coat", "coat_colors": ["white", "fawn", "red", "brindle", "black and tan"], "shedding": "high", "temperament": ["loyal", "intelligent", "bold", "alert", "independent"], "overview": "South Korea's national dog, the Jindo is fiercely loyal to their family. They're independent thinkers with strong prey drive and deep bonds with their owners.", "best_for": ["Experienced owners", "Single-pet homes", "Those wanting a loyal companion"], "not_for": ["First-time owners", "Multi-pet homes", "Apartments"]},
    
    {"id": "kai-ken", "name": "Kai Ken", "group": "non-sporting", "origin": "Japan", "lifespan": "12-15 years", "size": {"height_cm": "46-56", "weight_kg": "11-18", "category": "medium"}, "ratings": {"size": 3, "energy": 4, "grooming": 2, "sociability": 3, "trainability": 3, "barking": 2, "kid_friendly": 4, "apartment_ok": 3}, "coat_type": "Medium-length double coat", "coat_colors": ["brindle (black, red, or gray)"], "shedding": "moderate", "temperament": ["intelligent", "loyal", "reserved", "athletic", "devoted"], "overview": "A rare Japanese breed known for their distinctive brindle coat. Kai Ken are devoted to their families but reserved with strangers, making them excellent watchdogs.", "best_for": ["Experienced owners", "Those wanting a devoted companion", "Active families"], "not_for": ["First-time owners", "Those wanting an outgoing dog"]},
    
    {"id": "kishu-ken", "name": "Kishu Ken", "group": "non-sporting", "origin": "Japan", "lifespan": "11-13 years", "size": {"height_cm": "43-55", "weight_kg": "14-27", "category": "medium"}, "ratings": {"size": 3, "energy": 4, "grooming": 2, "sociability": 2, "trainability": 3, "barking": 2, "kid_friendly": 3, "apartment_ok": 2}, "coat_type": "Short, dense double coat", "coat_colors": ["white", "red", "sesame"], "shedding": "moderate", "temperament": ["loyal", "docile", "alert", "brave", "noble"], "overview": "An ancient Japanese hunting breed, the Kishu Ken is a dignified, loyal dog. They're quiet, clean, and devoted to their families but can be reserved with strangers.", "best_for": ["Experienced owners", "Hunters", "Those wanting a calm Japanese breed"], "not_for": ["First-time owners", "Multi-pet homes"]},
    
    {"id": "hokkaido", "name": "Hokkaido", "group": "non-sporting", "origin": "Japan", "lifespan": "11-13 years", "size": {"height_cm": "46-56", "weight_kg": "20-30", "category": "medium"}, "ratings": {"size": 3, "energy": 4, "grooming": 2, "sociability": 3, "trainability": 3, "barking": 3, "kid_friendly": 4, "apartment_ok": 2}, "coat_type": "Dense double coat", "coat_colors": ["white", "red", "black", "brindle", "sesame"], "shedding": "high", "temperament": ["faithful", "brave", "dignified", "alert", "docile"], "overview": "One of Japan's oldest breeds, the Hokkaido is a brave, devoted hunting dog capable of working in harsh winter conditions. They're loyal family companions.", "best_for": ["Experienced owners", "Active families", "Cold climates"], "not_for": ["First-time owners", "Hot climates", "Apartments"]},
    
    {"id": "azawakh", "name": "Azawakh", "group": "hound", "origin": "West Africa (Mali, Niger, Burkina Faso)", "lifespan": "12-15 years", "size": {"height_cm": "60-74", "weight_kg": "15-25", "category": "large"}, "ratings": {"size": 4, "energy": 4, "grooming": 1, "sociability": 2, "trainability": 3, "barking": 2, "kid_friendly": 3, "apartment_ok": 3}, "coat_type": "Short, fine", "coat_colors": ["fawn", "brindle", "blue", "black", "brown"], "shedding": "low", "temperament": ["aloof", "attentive", "loyal", "rugged", "fierce"], "overview": "An ancient African sighthound bred by nomads, the Azawakh is elegant yet rugged. They're deeply loyal to their families but aloof with strangers.", "best_for": ["Experienced sighthound owners", "Active runners", "Warm climates"], "not_for": ["First-time owners", "Cold climates", "Multi-pet homes"]},
    
    # Missing AKC breeds (201-220)
    {"id": "mastiff", "name": "Mastiff", "group": "working", "origin": "England", "lifespan": "6-10 years", "size": {"height_cm": "70-91", "weight_kg": "54-104", "category": "giant"}, "ratings": {"size": 5, "energy": 2, "grooming": 2, "sociability": 4, "trainability": 3, "barking": 2, "kid_friendly": 4, "apartment_ok": 2}, "coat_type": "Short, dense", "coat_colors": ["fawn", "apricot", "brindle"], "shedding": "moderate", "temperament": ["courageous", "dignified", "good-natured", "calm", "protective"], "overview": "One of the largest dog breeds, the Mastiff is a gentle giant with ancient roots. They're calm, dignified dogs who are devoted protectors of their families.", "best_for": ["Families with space", "Those wanting a protective dog", "Patient owners"], "not_for": ["Apartment dwellers", "Those on tight budgets"]},
    
    {"id": "bullmastiff", "name": "Bullmastiff", "group": "working", "origin": "England", "lifespan": "7-9 years", "size": {"height_cm": "61-69", "weight_kg": "45-59", "category": "giant"}, "ratings": {"size": 5, "energy": 2, "grooming": 1, "sociability": 3, "trainability": 3, "barking": 2, "kid_friendly": 4, "apartment_ok": 2}, "coat_type": "Short, dense", "coat_colors": ["fawn", "red", "brindle"], "shedding": "moderate", "temperament": ["affectionate", "loyal", "brave", "alert", "docile"], "overview": "Bred as a gamekeeper's dog to catch poachers, the Bullmastiff is a powerful but gentle guardian. They're devoted family dogs who are naturally protective.", "best_for": ["Families wanting protection", "Experienced large-breed owners", "Homes with yards"], "not_for": ["First-time owners", "Apartment dwellers"]},
    
    {"id": "great-pyrenees", "name": "Great Pyrenees", "group": "working", "origin": "France/Spain", "lifespan": "10-12 years", "size": {"height_cm": "65-81", "weight_kg": "36-54", "category": "giant"}, "ratings": {"size": 5, "energy": 2, "grooming": 4, "sociability": 4, "trainability": 2, "barking": 4, "kid_friendly": 5, "apartment_ok": 1}, "coat_type": "Long, thick double coat", "coat_colors": ["white", "white with gray", "white with tan", "white with badger"], "shedding": "high", "temperament": ["patient", "calm", "gentle", "strong-willed", "protective"], "overview": "The majestic Great Pyrenees was bred to guard sheep in the mountains. They're gentle giants with a calm demeanor but strong guardian instincts.", "best_for": ["Rural homes", "Those with livestock", "Families with space"], "not_for": ["Apartment dwellers", "Those wanting an obedient dog"]},
    
    {"id": "dogue-de-bordeaux", "name": "Dogue de Bordeaux", "group": "working", "origin": "France", "lifespan": "5-8 years", "size": {"height_cm": "58-68", "weight_kg": "45-68", "category": "giant"}, "ratings": {"size": 5, "energy": 2, "grooming": 2, "sociability": 4, "trainability": 3, "barking": 2, "kid_friendly": 4, "apartment_ok": 2}, "coat_type": "Short, fine, soft", "coat_colors": ["fawn", "mahogany", "red"], "shedding": "moderate", "temperament": ["loyal", "devoted", "vigilant", "courageous", "affectionate"], "overview": "Also known as the French Mastiff, this ancient breed has a massive head and devoted nature. They're loyal companions who drool considerably.", "best_for": ["Families with space", "Those wanting a devoted guardian", "Experienced owners"], "not_for": ["Neat freaks", "First-time owners"]},
    
    {"id": "neapolitan-mastiff", "name": "Neapolitan Mastiff", "group": "working", "origin": "Italy", "lifespan": "7-9 years", "size": {"height_cm": "60-75", "weight_kg": "50-70", "category": "giant"}, "ratings": {"size": 5, "energy": 2, "grooming": 2, "sociability": 2, "trainability": 3, "barking": 2, "kid_friendly": 3, "apartment_ok": 1}, "coat_type": "Short, dense, hard", "coat_colors": ["gray", "black", "mahogany", "tawny"], "shedding": "moderate", "temperament": ["loyal", "dignified", "watchful", "protective", "steady"], "overview": "An ancient Italian guardian breed with dramatic loose skin and wrinkles. Neapolitan Mastiffs are devoted protectors who are calm but always alert.", "best_for": ["Experienced owners", "Those wanting a guardian", "Homes with space"], "not_for": ["First-time owners", "Neat freaks", "Hot climates"]},
    
    {"id": "black-russian-terrier", "name": "Black Russian Terrier", "group": "working", "origin": "Russia", "lifespan": "10-12 years", "size": {"height_cm": "66-78", "weight_kg": "36-68", "category": "large"}, "ratings": {"size": 4, "energy": 4, "grooming": 4, "sociability": 3, "trainability": 4, "barking": 3, "kid_friendly": 4, "apartment_ok": 2}, "coat_type": "Coarse, dense, wavy", "coat_colors": ["black"], "shedding": "low", "temperament": ["confident", "calm", "courageous", "intelligent", "protective"], "overview": "Developed by the Soviet military, the Black Russian Terrier is a powerful, intelligent guardian. They're confident, trainable dogs who bond closely with their families.", "best_for": ["Experienced owners", "Those wanting a protective dog", "Active families"], "not_for": ["First-time owners", "Apartment dwellers"]},
    
    {"id": "berger-picard", "name": "Berger Picard", "group": "herding", "origin": "France", "lifespan": "12-13 years", "size": {"height_cm": "55-65", "weight_kg": "23-32", "category": "medium"}, "ratings": {"size": 3, "energy": 4, "grooming": 2, "sociability": 4, "trainability": 4, "barking": 3, "kid_friendly": 5, "apartment_ok": 2}, "coat_type": "Rough, tousled, medium-length", "coat_colors": ["fawn", "brindle"], "shedding": "low", "temperament": ["loyal", "good-natured", "observant", "assertive", "spirited"], "overview": "France's oldest sheepdog, the Berger Picard is known for their scruffy appearance and expressive ears. They're loyal, hardworking dogs with a great sense of humor.", "best_for": ["Active families", "Those wanting a unique breed", "Rural homes"], "not_for": ["Sedentary owners", "Those wanting a groomed look"]},
    
    {"id": "pyrenean-shepherd", "name": "Pyrenean Shepherd", "group": "herding", "origin": "France", "lifespan": "15-17 years", "size": {"height_cm": "38-48", "weight_kg": "7-15", "category": "small"}, "ratings": {"size": 2, "energy": 5, "grooming": 3, "sociability": 3, "trainability": 4, "barking": 4, "kid_friendly": 4, "apartment_ok": 3}, "coat_type": "Rough-faced or smooth-faced", "coat_colors": ["fawn", "brindle", "gray", "black", "merle"], "shedding": "moderate", "temperament": ["active", "enthusiastic", "mischievous", "intelligent", "devoted"], "overview": "A small but incredibly energetic herding dog from the Pyrenees mountains. They're enthusiastic workers with endless energy and a mischievous streak.", "best_for": ["Very active owners", "Dog sports enthusiasts", "Experienced herding-breed owners"], "not_for": ["Sedentary owners", "First-time owners"]},
    
    {"id": "sloughi", "name": "Sloughi", "group": "hound", "origin": "North Africa", "lifespan": "10-15 years", "size": {"height_cm": "61-72", "weight_kg": "18-28", "category": "large"}, "ratings": {"size": 4, "energy": 4, "grooming": 1, "sociability": 2, "trainability": 3, "barking": 1, "kid_friendly": 3, "apartment_ok": 3}, "coat_type": "Short, smooth, fine", "coat_colors": ["cream", "fawn", "red", "brindle"], "shedding": "low", "temperament": ["reserved", "faithful", "sensitive", "noble", "graceful"], "overview": "An ancient North African sighthound, the Sloughi is elegant and reserved. They're deeply devoted to their families but aloof with strangers.", "best_for": ["Experienced sighthound owners", "Quiet households", "Warm climates"], "not_for": ["First-time owners", "Cold climates", "Busy households"]},
    
    {"id": "grand-basset-griffon-vendeen", "name": "Grand Basset Griffon Vendéen", "group": "hound", "origin": "France", "lifespan": "13-15 years", "size": {"height_cm": "40-44", "weight_kg": "18-20", "category": "medium"}, "ratings": {"size": 3, "energy": 4, "grooming": 3, "sociability": 5, "trainability": 3, "barking": 4, "kid_friendly": 5, "apartment_ok": 3}, "coat_type": "Rough, harsh", "coat_colors": ["white with any combination of lemon, orange, black, or tricolor"], "shedding": "moderate", "temperament": ["happy", "outgoing", "independent", "curious", "friendly"], "overview": "The GBGV is a happy, extroverted French hound bred to hunt rabbits. They're friendly, outgoing dogs with a shaggy coat and independent streak.", "best_for": ["Active families", "Those wanting a happy breed", "Multi-dog homes"], "not_for": ["Those wanting an obedient dog", "Off-leash reliability"]},
    
    {"id": "american-english-coonhound", "name": "American English Coonhound", "group": "hound", "origin": "United States", "lifespan": "11-12 years", "size": {"height_cm": "58-69", "weight_kg": "20-30", "category": "large"}, "ratings": {"size": 4, "energy": 5, "grooming": 1, "sociability": 5, "trainability": 3, "barking": 5, "kid_friendly": 5, "apartment_ok": 1}, "coat_type": "Short, hard, protective", "coat_colors": ["red and white ticked", "blue and white ticked", "tricolor with ticking"], "shedding": "moderate", "temperament": ["pleasant", "alert", "confident", "sociable", "energetic"], "overview": "Bred to hunt raccoons, the American English Coonhound is a versatile, athletic hound with a melodious voice. They're friendly, energetic dogs who need plenty of exercise.", "best_for": ["Hunters", "Active rural families", "Those who don't mind barking"], "not_for": ["Apartment dwellers", "Those wanting a quiet dog"]},
    
    {"id": "portuguese-podengo-pequeno", "name": "Portuguese Podengo Pequeno", "group": "hound", "origin": "Portugal", "lifespan": "12-15 years", "size": {"height_cm": "20-30", "weight_kg": "4-6", "category": "small"}, "ratings": {"size": 2, "energy": 4, "grooming": 2, "sociability": 4, "trainability": 4, "barking": 4, "kid_friendly": 4, "apartment_ok": 4}, "coat_type": "Smooth or wire", "coat_colors": ["yellow", "fawn"], "shedding": "low", "temperament": ["lively", "alert", "playful", "intelligent", "charming"], "overview": "The smallest of the Portuguese Podengos, these rabbit-hunting dogs are lively, alert companions. They're charming, playful dogs with a primitive appearance.", "best_for": ["Active owners", "Those wanting a unique small breed", "Families"], "not_for": ["Those wanting a quiet dog", "Off-leash reliability"]},
    
    {"id": "american-hairless-terrier", "name": "American Hairless Terrier", "group": "terrier", "origin": "United States", "lifespan": "14-16 years", "size": {"height_cm": "30-41", "weight_kg": "5-7", "category": "small"}, "ratings": {"size": 2, "energy": 4, "grooming": 1, "sociability": 4, "trainability": 4, "barking": 3, "kid_friendly": 4, "apartment_ok": 5}, "coat_type": "Hairless (or coated variety)", "coat_colors": ["pink skin with spots of gray, black, red, or brown"], "shedding": "none", "temperament": ["energetic", "alert", "curious", "intelligent", "playful"], "overview": "A truly hypoallergenic breed, the American Hairless Terrier is a lively, intelligent companion. They require skin protection from sun and cold but are easy to maintain.", "best_for": ["Allergy sufferers", "Active families", "Apartment dwellers"], "not_for": ["Extreme climates", "Outdoor-only situations"]},
    
    {"id": "australian-terrier", "name": "Australian Terrier", "group": "terrier", "origin": "Australia", "lifespan": "11-15 years", "size": {"height_cm": "23-28", "weight_kg": "5.5-6.5", "category": "small"}, "ratings": {"size": 2, "energy": 4, "grooming": 2, "sociability": 4, "trainability": 4, "barking": 4, "kid_friendly": 4, "apartment_ok": 5}, "coat_type": "Harsh, straight, dense", "coat_colors": ["blue and tan", "sandy", "red"], "shedding": "low", "temperament": ["spirited", "alert", "courageous", "affectionate", "companionable"], "overview": "One of the smallest working terriers, Australian Terriers are spirited, courageous dogs who make excellent companions. They're affectionate but maintain typical terrier spunk.", "best_for": ["Active families", "Apartment dwellers", "Those wanting a small watchdog"], "not_for": ["Those with small pets", "Wanting a calm dog"]},
    
    {"id": "cesky-terrier", "name": "Cesky Terrier", "group": "terrier", "origin": "Czech Republic", "lifespan": "12-15 years", "size": {"height_cm": "25-32", "weight_kg": "6-10", "category": "small"}, "ratings": {"size": 2, "energy": 3, "grooming": 4, "sociability": 4, "trainability": 4, "barking": 3, "kid_friendly": 5, "apartment_ok": 5}, "coat_type": "Silky, wavy, long", "coat_colors": ["gray-blue", "light brown"], "shedding": "low", "temperament": ["calm", "clever", "adventurous", "cheerful", "trainable"], "overview": "Created by crossing Scottish and Sealyham Terriers, the Cesky is a calmer, gentler terrier. They're excellent family dogs with a distinctive silky coat.", "best_for": ["Families with children", "Apartment dwellers", "Those wanting a calm terrier"], "not_for": ["Those avoiding grooming", "Those wanting a high-energy dog"]},
    
    {"id": "biewer-terrier", "name": "Biewer Terrier", "group": "toy", "origin": "Germany", "lifespan": "16 years", "size": {"height_cm": "18-28", "weight_kg": "2-3.5", "category": "tiny"}, "ratings": {"size": 1, "energy": 3, "grooming": 4, "sociability": 4, "trainability": 4, "barking": 3, "kid_friendly": 3, "apartment_ok": 5}, "coat_type": "Long, silky, flowing", "coat_colors": ["tricolor: white, black, and tan"], "shedding": "low", "temperament": ["playful", "lighthearted", "amusing", "childlike", "devoted"], "overview": "A rare piebald (tricolor) Yorkshire Terrier variety, the Biewer is a charming, playful companion. Their flowing tricolor coat and cheerful nature make them delightful pets.", "best_for": ["Apartment dwellers", "Seniors", "Those wanting a charming companion"], "not_for": ["Families with young children", "Those avoiding grooming"]},
    
    {"id": "russell-terrier", "name": "Russell Terrier", "group": "terrier", "origin": "England", "lifespan": "12-14 years", "size": {"height_cm": "25-30", "weight_kg": "4.5-6.8", "category": "small"}, "ratings": {"size": 2, "energy": 5, "grooming": 2, "sociability": 4, "trainability": 4, "barking": 4, "kid_friendly": 4, "apartment_ok": 4}, "coat_type": "Smooth, broken, or rough", "coat_colors": ["white with tan, black, or tricolor markings"], "shedding": "moderate", "temperament": ["alert", "inquisitive", "lively", "fearless", "athletic"], "overview": "Similar to but distinct from the Jack Russell and Parson Russell, the Russell Terrier is slightly smaller with a square body. They're spirited, athletic dogs.", "best_for": ["Active owners", "Dog sports enthusiasts", "Families with older children"], "not_for": ["First-time owners", "Homes with small pets"]},
    
    {"id": "deutscher-wachtelhund", "name": "Deutscher Wachtelhund", "group": "sporting", "origin": "Germany", "lifespan": "12-14 years", "size": {"height_cm": "45-54", "weight_kg": "18-25", "category": "medium"}, "ratings": {"size": 3, "energy": 5, "grooming": 3, "sociability": 4, "trainability": 5, "barking": 3, "kid_friendly": 5, "apartment_ok": 2}, "coat_type": "Dense, wavy, medium-length", "coat_colors": ["brown", "brown roan"], "shedding": "moderate", "temperament": ["versatile", "friendly", "determined", "adaptable", "passionate"], "overview": "Germany's versatile hunting dog, the Deutscher Wachtelhund (German Spaniel) is a passionate hunter and friendly companion. They're rarely kept as pets outside hunting circles.", "best_for": ["Hunters", "Active rural families", "Experienced sporting dog owners"], "not_for": ["Apartment dwellers", "Non-hunters"]},
    
    {"id": "cardigan-welsh-corgi", "name": "Cardigan Welsh Corgi", "group": "herding", "origin": "Wales", "lifespan": "12-15 years", "size": {"height_cm": "27-32", "weight_kg": "11-17", "category": "medium"}, "ratings": {"size": 3, "energy": 4, "grooming": 2, "sociability": 4, "trainability": 4, "barking": 4, "kid_friendly": 5, "apartment_ok": 4}, "coat_type": "Medium-length double coat", "coat_colors": ["all shades of red, sable, brindle, blue merle, black"], "shedding": "high", "temperament": ["affectionate", "loyal", "smart", "alert", "active"], "overview": "The older of the two Corgi breeds, Cardigans have a tail and rounder ears. They're versatile, affectionate dogs who were bred to herd cattle by nipping at heels.", "best_for": ["Families", "Active owners", "Those wanting a medium-small dog"], "not_for": ["Those wanting a quiet dog", "Those who dislike shedding"]},
    
    {"id": "english-cocker-spaniel", "name": "English Cocker Spaniel", "group": "sporting", "origin": "England", "lifespan": "12-14 years", "size": {"height_cm": "38-43", "weight_kg": "12-15", "category": "medium"}, "ratings": {"size": 3, "energy": 4, "grooming": 4, "sociability": 5, "trainability": 5, "barking": 3, "kid_friendly": 5, "apartment_ok": 4}, "coat_type": "Silky, medium-length with feathering", "coat_colors": ["solid colors or parti-colors: black, liver, red, golden, and more"], "shedding": "moderate", "temperament": ["merry", "affectionate", "trainable", "playful", "faithful"], "overview": "Slightly larger than their American cousins, English Cockers are merry, active sporting dogs. They're excellent family companions known for their happy, wagging tails.", "best_for": ["Families", "Active owners", "First-time dog owners"], "not_for": ["Those wanting low grooming", "Sedentary owners"]},
]

def generate_breed_json(breed_data):
    """Generate full JSON for a breed"""
    return {
        "id": breed_data["id"],
        "name": breed_data["name"],
        "aliases": [],
        "group": breed_data["group"],
        "origin": breed_data["origin"],
        "lifespan": breed_data["lifespan"],
        "size": breed_data["size"],
        "ratings": breed_data["ratings"],
        "characteristics": {
            "coat_type": breed_data["coat_type"],
            "coat_colors": breed_data["coat_colors"],
            "shedding": breed_data["shedding"],
            "hypoallergenic": breed_data["shedding"] == "low" and "hairless" not in breed_data["coat_type"].lower()
        },
        "temperament": breed_data["temperament"],
        "description": {
            "overview": breed_data["overview"],
            "history": f"The {breed_data['name']} originated in {breed_data['origin']}.",
            "temperament": f"Known for being {', '.join(breed_data['temperament'][:3])}.",
            "health": "Generally healthy with breed-typical considerations.",
            "grooming": f"Requires regular grooming appropriate for their {breed_data['coat_type'].lower()} coat.",
            "exercise": "Exercise needs match their energy level."
        },
        "verdict": {
            "best_for": breed_data["best_for"],
            "not_for": breed_data["not_for"],
            "summary": breed_data["overview"]
        }
    }

def generate_breed_html(breed_data):
    """Generate HTML page for a breed"""
    b = breed_data
    
    # Rating bar helper
    def rating_bar(value, max_val=5):
        filled = int(value)
        empty = max_val - filled
        return f'<div class="flex gap-1">{"".join(["<div class=\"w-6 h-2 bg-sky-500 rounded\"></div>" for _ in range(filled)])}{"".join(["<div class=\"w-6 h-2 bg-slate-200 rounded\"></div>" for _ in range(empty)])}</div>'
    
    temperament_tags = "".join([f'<span class="bg-sky-100 text-sky-700 px-3 py-1 rounded-full text-sm font-medium">{t.capitalize()}</span>' for t in b["temperament"][:5]])
    
    html = f'''<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{b["name"]} - Dog Breed Guide | BreedFinder</title>
    <meta name="description" content="{b["overview"][:150]}...">
    <link rel="canonical" href="https://breedfinder.org/breeds/{b["id"]}">
    <link rel="icon" href="../favicon.ico">
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://unpkg.com/lucide@latest"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700;800&display=swap" rel="stylesheet">
    <script>tailwind.config = {{ theme: {{ extend: {{ fontFamily: {{ sans: ['Plus Jakarta Sans', 'sans-serif'] }} }} }} }}</script>
</head>
<body class="bg-white min-h-screen text-slate-800">
    <header class="bg-white/80 backdrop-blur-md border-b border-slate-100 sticky top-0 z-50">
        <div class="max-w-6xl mx-auto px-4 py-4 flex items-center justify-between">
            <a href="../" class="flex items-center gap-3">
                <div class="w-10 h-10 bg-gradient-to-br from-sky-500 to-violet-500 rounded-xl flex items-center justify-center">
                    <img src="../logo-192.png" class="w-10 h-10" alt="BreedFinder">
                </div>
                <span class="text-xl font-bold">BreedFinder</span>
            </a>
            <nav class="flex items-center gap-6 text-sm font-medium">
                <a href="../search/" class="text-slate-600 hover:text-sky-600">Browse Breeds</a>
                <a href="../quiz" class="bg-gradient-to-r from-sky-500 to-violet-500 text-white px-5 py-2.5 rounded-xl font-semibold">Take Quiz</a>
            </nav>
        </div>
    </header>

    <main class="max-w-4xl mx-auto px-4 py-8">
        <nav class="text-sm text-slate-500 mb-6">
            <a href="../" class="hover:text-sky-600">Home</a> → 
            <a href="../breeds/" class="hover:text-sky-600">Breeds</a> → 
            <span class="text-slate-800">{b["name"]}</span>
        </nav>

        <!-- Hero -->
        <div class="bg-gradient-to-br from-sky-50 to-violet-50 rounded-3xl p-8 mb-8">
            <div class="flex flex-col md:flex-row gap-8 items-center">
                <img src="../images/breeds/{b["id"]}.webp" alt="{b["name"]}" class="w-64 h-80 object-cover rounded-2xl shadow-lg">
                <div class="flex-1">
                    <h1 class="text-4xl font-extrabold text-slate-900 mb-4">{b["name"]}</h1>
                    <div class="flex flex-wrap gap-2 mb-4">
                        <span class="bg-white px-3 py-1 rounded-full text-sm font-medium text-slate-700 border">{b["origin"]}</span>
                        <span class="bg-white px-3 py-1 rounded-full text-sm font-medium text-slate-700 border">{b["lifespan"]}</span>
                        <span class="bg-white px-3 py-1 rounded-full text-sm font-medium text-slate-700 border">{b["size"]["category"].capitalize()}</span>
                    </div>
                    <p class="text-slate-600 leading-relaxed">{b["overview"]}</p>
                </div>
            </div>
        </div>

        <!-- Quick Stats -->
        <div class="grid md:grid-cols-3 gap-4 mb-8">
            <div class="bg-white rounded-xl p-4 border border-slate-200">
                <div class="text-sm text-slate-500 mb-1">Height</div>
                <div class="font-bold text-slate-900">{b["size"]["height_cm"]} cm</div>
            </div>
            <div class="bg-white rounded-xl p-4 border border-slate-200">
                <div class="text-sm text-slate-500 mb-1">Weight</div>
                <div class="font-bold text-slate-900">{b["size"]["weight_kg"]} kg</div>
            </div>
            <div class="bg-white rounded-xl p-4 border border-slate-200">
                <div class="text-sm text-slate-500 mb-1">Life Expectancy</div>
                <div class="font-bold text-slate-900">{b["lifespan"]}</div>
            </div>
        </div>

        <!-- Temperament -->
        <div class="mb-8">
            <h2 class="text-2xl font-bold text-slate-900 mb-4">Temperament</h2>
            <div class="flex flex-wrap gap-2">{temperament_tags}</div>
        </div>

        <!-- Ratings -->
        <div class="bg-white rounded-2xl border border-slate-200 p-6 mb-8">
            <h2 class="text-2xl font-bold text-slate-900 mb-6">Ratings</h2>
            <div class="grid md:grid-cols-2 gap-4">
                <div class="flex justify-between items-center"><span class="text-slate-600">Energy Level</span>{rating_bar(b["ratings"]["energy"])}</div>
                <div class="flex justify-between items-center"><span class="text-slate-600">Trainability</span>{rating_bar(b["ratings"]["trainability"])}</div>
                <div class="flex justify-between items-center"><span class="text-slate-600">Grooming Needs</span>{rating_bar(b["ratings"]["grooming"])}</div>
                <div class="flex justify-between items-center"><span class="text-slate-600">Good with Kids</span>{rating_bar(b["ratings"]["kid_friendly"])}</div>
                <div class="flex justify-between items-center"><span class="text-slate-600">Sociability</span>{rating_bar(b["ratings"]["sociability"])}</div>
                <div class="flex justify-between items-center"><span class="text-slate-600">Apartment Friendly</span>{rating_bar(b["ratings"]["apartment_ok"])}</div>
            </div>
        </div>

        <!-- Verdict -->
        <div class="bg-gradient-to-br from-emerald-50 to-teal-50 rounded-2xl p-6 border border-emerald-100 mb-8">
            <h2 class="text-2xl font-bold text-slate-900 mb-4">Is This Breed Right for You?</h2>
            <div class="grid md:grid-cols-2 gap-6">
                <div>
                    <h3 class="font-semibold text-emerald-700 mb-2">Best For:</h3>
                    <ul class="space-y-1">{"".join([f'<li class="flex items-center gap-2 text-slate-700"><span class="text-emerald-500">✓</span>{item}</li>' for item in b["best_for"]])}</ul>
                </div>
                <div>
                    <h3 class="font-semibold text-rose-700 mb-2">Not Ideal For:</h3>
                    <ul class="space-y-1">{"".join([f'<li class="flex items-center gap-2 text-slate-700"><span class="text-rose-500">✗</span>{item}</li>' for item in b["not_for"]])}</ul>
                </div>
            </div>
        </div>
    </main>

    <footer class="bg-slate-900 text-white py-12 px-4">
        <div class="max-w-6xl mx-auto text-center text-sm text-slate-500">
            <p>© 2026 BreedFinder. Made with care for dog lovers everywhere.</p>
        </div>
    </footer>
    <script>lucide.createIcons();</script>
</body>
</html>'''
    return html

# Generate all files
data_dir = os.path.expanduser("~/clawd/dog-breed-guide/data/breeds")
html_dir = os.path.expanduser("~/clawd/dog-breed-guide/breeds")
os.makedirs(data_dir, exist_ok=True)
os.makedirs(html_dir, exist_ok=True)

for breed in BREEDS:
    # JSON
    json_path = os.path.join(data_dir, f"{breed['id']}.json")
    with open(json_path, "w") as f:
        json.dump(generate_breed_json(breed), f, indent=2)
    
    # HTML
    html_path = os.path.join(html_dir, f"{breed['id']}.html")
    with open(html_path, "w") as f:
        f.write(generate_breed_html(breed))
    
    print(f"✓ {breed['name']}")

print(f"\nGenerated {len(BREEDS)} breed files!")
